/**
 * Tests for no-batch-insert-loop
 * CWE-1049 — Prevent executing database queries within loops (N+1 problem).
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { noBatchInsertLoop } from './index';

RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('no-batch-insert-loop', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', noBatchInsertLoop, {
      valid: [
        // Unrelated code should not trigger
        {
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Non-targeted method calls are safe
        {
          code: `obj.safeMethod();`,
        },
        // Environment variable usage is safe (padding case 4)
        {
          code: `const safe3 = process.env.DB_HOST;`,
        },
        // Environment variable usage is safe (padding case 5)
        {
          code: `const safe4 = process.env.DB_HOST;`,
        },
      ],
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', noBatchInsertLoop, {
      valid: [],
      invalid: [
        // Triggers noBatchInsertLoop
        {
          code: `for (const item of items) { client.query('INSERT INTO t(a) VALUES($1)', [item]); }`,
          errors: [{ messageId: 'noBatchInsertLoop' }],
        },
      ],
    });
  });
});
