#!/usr/bin/env node
/**
 * @interlace/pg-mcp — MCP server for @interlace/eslint-plugin-pg.
 * Generated by scripts/scaffold-mcp.mjs. All logic in @interlace/eslint-mcp-base.
 */
import { startMcpServer } from '@interlace/eslint-mcp-base';

await startMcpServer({
  pluginName: 'pg',
  packageDir: 'eslint-plugin-pg',
  rulePrefix: 'pg',
  serverName: 'pg-mcp',
  serverVersion: '0.1.0',
});
