#!/usr/bin/env node
/**
 * @interlace/express-security-mcp — MCP server for @interlace/eslint-plugin-express-security.
 * Generated by scripts/scaffold-mcp.mjs. All logic in @interlace/eslint-mcp-base.
 */
import { startMcpServer } from '@interlace/eslint-mcp-base';

await startMcpServer({
  pluginName: 'express-security',
  packageDir: 'eslint-plugin-express-security',
  rulePrefix: 'express-security',
  serverName: 'express-security-mcp',
  serverVersion: '0.1.0',
});
