/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * `skipGeneratedFiles` is set on these rules. This pins it.
 *
 * Measured on the pinned 8-repository corpus, generated files were 32% of
 * `cognitive-complexity`'s 1,409 findings and 27% of `max-parameters`' 407 —
 * almost all of it twilio-node's OpenAPI-generated `src/rest/**`, whose header
 * says "Do not edit the class manually". Applying the skip removed exactly 32%
 * and 27%, so the predicate silenced the generated set and nothing else.
 *
 * Each rule gets a positive control. Without one, "quiet in generated files"
 * also passes on a rule that has stopped firing entirely.
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { cognitiveComplexity } from '../../rules/maintainability/cognitive-complexity';
import { maxParameters } from '../../rules/maintainability/max-parameters';

RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: { parser, ecmaVersion: 2022, sourceType: 'module' },
});

const BANNER = `/*
 * This code was generated by OpenAPI Generator.
 * NOTE: This class is auto generated. Do not edit the class manually.
 */`;

/** Nested branching well past any sane threshold. */
const COMPLEX = `
  function handle(a, b, c) {
    if (a) {
      if (b) {
        for (const x of c) {
          if (x > 1) { if (x > 2) { if (x > 3) { return x; } } }
        }
      } else if (c) {
        while (a) { if (b && c) { break; } else if (a || b) { continue; } }
      }
    }
    return a && b ? (c || a) : (b && c);
  }
`;

const MANY_PARAMS = 'function build(a, b, c, d, e, f, g, h) { return a; }';

describe('maintainability — generated files', () => {
  ruleTester.run('cognitive-complexity', cognitiveComplexity, {
    valid: [{ code: `${BANNER}\n${COMPLEX}`, filename: '/repo/src/rest/v1/bulk.ts' }],
    invalid: [
      {
        // POSITIVE CONTROL.
        code: COMPLEX,
        filename: '/repo/src/rest/v1/bulk.ts',
        errors: [{ messageId: 'highCognitiveComplexity' }],
      },
      {
        // A banner is a header, not a licence to suppress from anywhere.
        code: `${COMPLEX}\n// this code was generated by hand`,
        filename: '/repo/src/handler.ts',
        errors: [{ messageId: 'highCognitiveComplexity' }],
      },
    ],
  });

  ruleTester.run('max-parameters', maxParameters, {
    valid: [{ code: `${BANNER}\n${MANY_PARAMS}`, filename: '/repo/src/rest/v1/bulk.ts' }],
    invalid: [
      {
        // POSITIVE CONTROL.
        code: MANY_PARAMS,
        filename: '/repo/src/rest/v1/bulk.ts',
        errors: [{ messageId: 'tooManyParameters' }],
      },
      {
        // `src/generated-reports/` is a NAME. The predicate reads the file's
        // own header, and this file has none.
        code: MANY_PARAMS,
        filename: '/repo/src/generated-reports/summary.ts',
        errors: [{ messageId: 'tooManyParameters' }],
      },
    ],
  });
});
