/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * Where `identical-functions` declines to look, and why.
 *
 * On the pinned 8-repository corpus the rule reported 3,707 findings. 1,961 of
 * them (52.9%) were test code and 1,320 more were twilio-node's OpenAPI-
 * generated `src/rest/**`. Both classes are correct detections of real
 * duplication and neither is actionable, which under the effective-FP standard
 * costs the rule exactly what a wrong finding would. After both skips: 371.
 *
 * Every fixture below is a lock. The two `false` cases are the FN guards — turn
 * an option off and the finding must come back, so neither skip can quietly
 * grow into a blanket suppression.
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { identicalFunctions } from '../../rules/maintainability/identical-functions';

RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: { parser, ecmaVersion: 2022, sourceType: 'module' },
});

/** A pair the rule reports on. Proven by the first invalid fixture below. */
const DUPLICATE_PAIR = `
  function alpha(items) {
    const total = items.reduce((sum, x) => sum + x, 0);
    const scaled = total * 100;
    return scaled;
  }
  function beta(values) {
    const total = values.reduce((sum, x) => sum + x, 0);
    const scaled = total * 100;
    return scaled;
  }
`;

const GENERATED_BANNER = `/*
 * This code was generated by Twilio's OpenAPI Generator.
 * NOTE: This class is auto generated. Do not edit the class manually.
 */`;

describe('identical-functions — where it declines to look', () => {
  ruleTester.run('skipped scopes', identicalFunctions, {
    valid: [
      {
        // The whole point of the change: okta-auth-js keeps its suite in
        // `test/spec/**` with PLAIN filenames, so the old basename-only
        // `/\.(test|spec)\.[jt]sx?$/` never matched and the option that is on
        // by default did nothing. 1,961 findings lived behind this line.
        code: DUPLICATE_PAIR,
        filename: '/repo/test/spec/TokenManager/browser.ts',
      },
      {
        code: DUPLICATE_PAIR,
        filename: '/repo/src/__tests__/manager.ts',
      },
      {
        // The basename case still works.
        code: DUPLICATE_PAIR,
        filename: '/repo/src/manager.test.ts',
      },
      {
        // A file that declares itself generated, by its own header.
        code: `${GENERATED_BANNER}\n${DUPLICATE_PAIR}`,
        filename: '/repo/src/rest/memory/v1/bulk.ts',
      },
      {
        // The `@generated` docblock annotation, on its own.
        code: `/** @generated */\n${DUPLICATE_PAIR}`,
        filename: '/repo/src/client.ts',
      },
    ],
    invalid: [
      {
        // POSITIVE CONTROL. Without it every `valid` case above proves nothing:
        // a rule that never fires passes all of them.
        code: DUPLICATE_PAIR,
        filename: '/repo/src/manager.ts',
        errors: [{ messageId: 'identicalFunctions' }],
      },
      {
        // FN GUARD: `ignoreTestFiles: false` restores the finding, so the skip
        // is a scope decision the user owns and not a hole in the rule.
        code: DUPLICATE_PAIR,
        filename: '/repo/test/spec/TokenManager/browser.ts',
        options: [{ ignoreTestFiles: false }],
        errors: [{ messageId: 'identicalFunctions' }],
      },
      {
        // FN GUARD: same for generated files.
        code: `${GENERATED_BANNER}\n${DUPLICATE_PAIR}`,
        filename: '/repo/src/rest/memory/v1/bulk.ts',
        options: [{ ignoreGeneratedFiles: false }],
        errors: [{ messageId: 'identicalFunctions' }],
      },
      {
        // A banner is a HEADER. A generation phrase further down the file must
        // not silence the module — otherwise any comment anywhere buys a
        // whole-file suppression for free.
        code: `${DUPLICATE_PAIR}\n// this code was generated by hand, honestly`,
        filename: '/repo/src/manager.ts',
        errors: [{ messageId: 'identicalFunctions' }],
      },
      {
        // `src/generated-reports/summary.ts` is a NAME, not a declaration. The
        // predicate reads the file's own header and this file has none.
        code: DUPLICATE_PAIR,
        filename: '/repo/src/generated-reports/summary.ts',
        errors: [{ messageId: 'identicalFunctions' }],
      },
    ],
  });
});
