/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * The two defects a census of this rule's real findings exposed.
 *
 * All 11 findings on the pinned corpus were in twilio's auto-generated OpenAPI
 * SDK, and none of the 11 was a value object. Two independent causes:
 *
 *   1. `className.includes(pattern)` matched anything CONTAINING "Value" —
 *      `CountyCarrierValueCarriers`, `…SettingsValueCaptureRules`.
 *   2. Generated files were linted at all, where "add readonly" is advice the
 *      next generator run erases.
 *
 * Each is locked separately, because either alone would still have produced
 * findings on that corpus.
 */

import { describe, it, expect } from 'vitest';
import { Linter } from 'eslint';
import tsParser from '@typescript-eslint/parser';
import { dddValueObjectImmutability } from './ddd-value-object-immutability';

const lint = (code: string): number => {
  const linter = new Linter({ configType: 'flat' });
  return linter
    .verify(
      code,
      [
        {
          files: ['**/*.ts'],
          languageOptions: { parser: tsParser as never, ecmaVersion: 2022, sourceType: 'module' },
          plugins: { m: { rules: { 'ddd-value-object-immutability': dddValueObjectImmutability as never } } },
          rules: { 'm/ddd-value-object-immutability': 'error' },
        },
      ],
      'src/subject.ts',
    )
    .filter((m) => m.ruleId === 'm/ddd-value-object-immutability').length;
};

const MUTABLE = (name: string) => `export class ${name} {\n  amount: number = 1;\n}\n`;

describe('naming convention is a suffix, not a substring', () => {
  it('reports a class whose name ENDS with the marker — the control', () => {
    // Without this, the silences below prove nothing.
    expect(lint(MUTABLE('MoneyValue'))).toBeGreaterThan(0);
  });

  it('reports the VO suffix too', () => {
    expect(lint(MUTABLE('EmailVO'))).toBeGreaterThan(0);
  });

  it('ignores a name that merely CONTAINS the marker', () => {
    // Both of these were real findings on the corpus.
    expect(lint(MUTABLE('CountyCarrierValueCarriers'))).toBe(0);
    expect(lint(MUTABLE('CreateConfigurationRequestChannelSettingsValueCaptureRules'))).toBe(0);
  });

  it('ignores a word that happens to contain VO', () => {
    // `CONVOY` and `PIVOT` contain "VO" once casing lines up — the substring
    // form would have reported both.
    expect(lint(MUTABLE('ConVOyRoute'))).toBe(0);
    expect(lint(MUTABLE('PiVOtTable'))).toBe(0);
  });
});

describe('generated files', () => {
  // The wording twilio's SDK actually opens with. NOT "auto generated by"
  // alone — the detector matches `auto-?generated`, so the spaced form does not
  // hit on its own, and a fixture built on it fails for a reason unrelated to
  // this rule. Every file in the corpus carrying the spaced form also carries
  // this phrase, which is why the detector still catches all of them.
  const BANNER = '/*\n * This code was generated by the OpenAPI Generator.\n * Do not edit the class manually.\n */\n';

  it('stays silent on a value object in generated output', () => {
    expect(lint(BANNER + MUTABLE('MoneyValue'))).toBe(0);
  });

  it('still reports the same class in hand-written source — the control', () => {
    expect(lint(MUTABLE('MoneyValue'))).toBeGreaterThan(0);
  });
});
