/**
 * Tests for prevent-double-release
 * Prevent releasing a pg client multiple times.
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { preventDoubleRelease } from './index';

/**
 * Every fixture imports a PostgreSQL client, because the rule now abstains in
 * files that use no PostgreSQL at all. Wrapping the arrays rather than editing
 * each fixture means one cannot be left behind — a fixture missing the import
 * would pass vacuously on the gate instead of exercising the detection it was
 * written for.
 */
const withPg = (code: string): string => `import { Pool } from 'pg';\n${code}`;
const pg = <T,>(cases: T[]): T[] =>
  cases.map((c) =>
    typeof c === 'string'
      ? (withPg(c) as T)
      : ({ ...c, code: withPg((c as { code: string }).code) } as T),
  );


RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('prevent-double-release', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', preventDoubleRelease, {
      valid: pg([
        // Unrelated code should not trigger
        {
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Non-targeted method calls are safe
        {
          code: `obj.safeMethod();`,
        },
        // Properly configured connection
        {
          code: `mongoose.connect(uri, { tls: true });`,
        },
        // Environment variable usage is safe (padding case 5)
        {
          code: `const safe4 = process.env.DB_HOST;`,
        },
      ]),
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', preventDoubleRelease, {
      valid: [],
      invalid: pg([
        // Triggers doubleRelease
        {
          code: `async function test() { const client = await pool.connect(); try { await client.query('SELECT 1'); client.release(); } catch(e) { client.release(); } }`,
          errors: [{ messageId: 'doubleRelease' }],
        },
      ]),
    });
  });

  /**
   * Regression locks for the defects
   * `benchmarks/rule-corpus/postgresql-security__prevent-double-release`
   * proved. The rule scored 72.7% F1 on that corpus.
   */
  describe('corpus regressions', () => {
    /**
     * `doubleReleaseCallback` was DECLARED and never reported once — the
     * ledger flagged it as an orphan message and this file carried a note
     * deferring it ("requires complex scope analysis"). It was not dead
     * metadata: it was a report path that had never been built, so the entire
     * legacy `pool.connect(cb)` API was a blind spot.
     */
    ruleTester.run('the callback form is a release too', preventDoubleRelease, {
      valid: pg([
        // The error path RETURNS, so `done` runs exactly once on every path.
        "pool.connect((err, client, done) => { if (err) { done(err); return; } client.query('SELECT 1', () => { done(); }); });",
        // A throw terminates it just as well.
        'pool.connect((err, client, done) => { if (err) { done(err); throw err; } done(); });',
        // Only one call.
        'pool.connect((err, client, done) => { done(); });',
        // No calls at all — that is no-missing-client-release\'s business.
        "pool.connect((err, client, done) => { client.query('SELECT 1'); });",
        // Fewer than three parameters: there is no release callback.
        'pool.connect((err, client) => { client.query("SELECT 1"); });',
        // A destructured third parameter is not an identifier to follow.
        'pool.connect((err, client, { done }) => { done(); done(); });',
        // Not a `connect` call.
        'pool.on((err, client, done) => { done(); done(); });',
        // A callback argument to something that is not a member call.
        'register((err, client, done) => { done(); done(); });',
      ]),
      invalid: pg([
        // FN — the error path calls `done(err)` and then falls THROUGH.
        {
          code: "pool.connect((err, client, done) => { if (err) { done(err); } client.query('SELECT 1', () => { done(); }); });",
          errors: [{ messageId: 'doubleReleaseCallback' }],
        },
        // The `function` expression spelling of the same callback.
        {
          code: 'pool.connect(function (err, client, done) { if (err) { done(err); } done(); });',
          errors: [{ messageId: 'doubleReleaseCallback' }],
        },
        // Two calls in a row.
        {
          code: 'pool.connect((err, client, done) => { done(); done(); });',
          errors: [{ messageId: 'doubleReleaseCallback' }],
        },
        // A `done` that is not inside a block statement cannot be shown to be
        // terminated, so the fall-through stands.
        {
          code: 'pool.connect((err, client, done) => { if (err) done(err); done(); });',
          errors: [{ messageId: 'doubleReleaseCallback' }],
        },
        // A `done` whose result is USED is not a bare expression statement,
        // so there is no enclosing statement list to look for a return in.
        {
          code: 'pool.connect((err, client, done) => { if (err) { const r = done(err); } done(); });',
          errors: [{ messageId: 'doubleReleaseCallback' }],
        },
      ]),
    });

    /**
     * ONE checkout, a release INSIDE a loop. Every iteration after the first
     * releases a client this scope no longer owns — and the pairwise
     * comparison can never see it, because there is only one release call in
     * the source. Two fixtures asserting exactly this as correct behaviour
     * lived in `index.spec.ts` under the name "documented FN"; they are now
     * invalid cases there.
     */
    ruleTester.run('a release inside a loop repeats', preventDoubleRelease, {
      valid: pg([
        // The checkout is inside the loop, so each iteration owns its client.
        'async function f(ids) { for (const id of ids) { const client = await pool.connect(); try { await client.query("SELECT 1"); } finally { client.release(); } } }',
        'async function f(n) { while (n--) { const client = await pool.connect(); client.release(); } }',
        // No loop at all.
        'async function f() { const client = await pool.connect(); client.release(); }',
        // The release is in a loop inside a DIFFERENT function.
        'async function f(ids) { const client = await pool.connect(); const g = () => { for (const id of ids) { client.release(); } }; }',
      ]),
      invalid: pg([
        {
          code: 'async function f(ids) { const client = await pool.connect(); for (const id of ids) { client.release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
        {
          code: 'async function f() { const client = await pool.connect(); for (let i = 0; i < 3; i++) { client.release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
        {
          code: 'async function f(o) { const client = await pool.connect(); for (const k in o) { client.release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
        {
          code: 'async function f(n) { const client = await pool.connect(); while (n--) { client.release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
        {
          code: 'async function f(n) { const client = await pool.connect(); do { client.release(); } while (n--); }',
          errors: [{ messageId: 'doubleRelease' }],
        },
        // The destructured-release spelling.
        {
          code: 'async function f(ids) { const { release } = await pool.connect(); for (const id of ids) { release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
      ]),
    });

    /**
     * A guard guards when the guarded block SETS the flag it tested. The old
     * test asked whether the flag was SPELLED `released`, `done` or `closed` —
     * control-flow state inferred from a variable name, and this rule's
     * registered name-inference debt.
     */
    ruleTester.run('a guard is proven by its assignment, not its name', preventDoubleRelease, {
      valid: pg([
        // A neutrally-named flag that IS set. The old rule reported this.
        'async function f() { const client = await pool.connect(); let settled = false; if (!settled) { settled = true; client.release(); } if (!settled) { settled = true; client.release(); } }',
        'async function f(state) { const client = await pool.connect(); if (!state.finished) { state.finished = true; client.release(); } if (!state.finished) { state.finished = true; client.release(); } }',
      ]),
      invalid: pg([
        // A flag that is never assigned guards nothing — both branches run.
        {
          code: 'async function f() { const client = await pool.connect(); if (!client.released) { client.release(); } if (!client.released) { client.release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
        // A test that is not a negation is not a release-once guard.
        {
          code: 'async function f(a) { const client = await pool.connect(); if (a) { client.release(); } if (a) { client.release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
        // A negation of something with no knowable name.
        {
          code: 'async function f(a) { const client = await pool.connect(); if (!a[k]) { client.release(); } if (!a[k]) { client.release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
        // The flag is assigned something other than `true`.
        {
          code: 'async function f() { const client = await pool.connect(); let settled = false; if (!settled) { settled = maybe; client.release(); } if (!settled) { settled = maybe; client.release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
        // A DIFFERENT flag is set than the one tested.
        {
          code: 'async function f() { const client = await pool.connect(); let settled = false; let other = false; if (!settled) { other = true; client.release(); } if (!settled) { other = true; client.release(); } }',
          errors: [{ messageId: 'doubleRelease' }],
        },
      ]),
    });

    // NOT wrapped — a file with no PostgreSQL client does no work at all.
    ruleTester.run('the module gate still abstains', preventDoubleRelease, {
      valid: [
        'async function f() { const client = await pool.connect(); client.release(); client.release(); }',
        'pool.connect((err, client, done) => { done(); done(); });',
      ],
      invalid: [],
    });
  });
});
