import numbers from '@/data/interlace-numbers.json';
import pluginStats from '@/data/plugin-stats.json';

/**
 * Render a number from the generated numbers manifest inside MDX prose.
 *
 * Usage:
 *   <Stat of="plugins.total" />          → e.g. 19
 *   <Stat of="rules.security" />         → e.g. 238
 *   <Stat plugin="secure-coding" />      → that plugin's rule count
 *
 * Never hand-type plugin/rule counts in docs content — they drift. This
 * component reads apps/docs/src/data/interlace-numbers.json (generated by
 * scripts/sync-plugin-stats.ts from the actual package registry), so the
 * prose updates whenever the registry changes. Unknown keys throw at
 * build time so typos can't silently render nothing.
 */
const AGGREGATES: Record<string, number> = {
  'plugins.total': numbers.plugins.total,
  'plugins.security': numbers.plugins.security,
  'plugins.quality': numbers.plugins.quality,
  'plugins.react': numbers.plugins.react,
  'rules.total': numbers.rules.total,
  'rules.security': numbers.rules.security,
  'rules.quality': numbers.rules.quality,
  'rules.react': numbers.rules.react,
};

export function Stat({ of, plugin }: { of?: string; plugin?: string }) {
  if (plugin) {
    const entry = pluginStats.plugins.find(
      (p) => p.name === `eslint-plugin-${plugin}`,
    );
    if (!entry || !entry.published) {
      throw new Error(
        `<Stat plugin="${plugin}"> — unknown or unpublished plugin`,
      );
    }
    return <>{entry.rules}</>;
  }
  if (!of || !(of in AGGREGATES)) {
    throw new Error(
      `<Stat of="${of}"> — unknown key (valid: ${Object.keys(AGGREGATES).join(', ')})`,
    );
  }
  return <>{AGGREGATES[of]}</>;
}
