/**
 * Tests for no-insecure-ssl
 * CWE-319 — Prevent the use of insecure SSL configurations (rejectUnauthorized: false).
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { noInsecureSsl } from './index';

RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('no-insecure-ssl', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', noInsecureSsl, {
      valid: [
        // Unrelated code should not trigger
        {
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Static property values are safe
        {
          code: `const config = { key: "static-value" };`,
        },
        // Environment variable usage is safe (padding case 4)
        {
          code: `const safe3 = process.env.DB_HOST;`,
        },
        // Environment variable usage is safe (padding case 5)
        {
          code: `const safe4 = process.env.DB_HOST;`,
        },
      ],
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', noInsecureSsl, {
      valid: [],
      invalid: [
        // Triggers noInsecureSsl: rejectUnauthorized disabled in SSL config
        {
          code: `new Client({ host: 'db.example.com', ssl: { rejectUnauthorized: false } })`,
          errors: [{ messageId: 'noInsecureSsl' }],
        },
      ],
    });
  });
});
