/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

import { describe, expect, it } from 'vitest';
import { Linter } from 'eslint';
import { isGeneratedFile } from './generated-file';

/**
 * Run the predicate against real source by asking ESLint for a real SourceCode.
 * A hand-built stub would let the leading-comment logic pass without ever
 * meeting a token, which is the half the bound depends on.
 */
function check(code: string): boolean {
  let seen: boolean | undefined;
  const linter = new Linter();
  linter.verify(code, {
    plugins: {
      probe: {
        rules: {
          check: {
            create(context) {
              seen = isGeneratedFile(context.sourceCode);
              return {};
            },
          },
        },
      },
    },
    rules: { 'probe/check': 'error' },
  });
  if (seen === undefined) throw new Error('rule never ran');
  return seen;
}

describe('isGeneratedFile', () => {
  it('reads the OpenAPI Generator banner twilio-node ships', () => {
    expect(
      check(`/*
 * This code was generated by
 * Twilio Memory API
 * NOTE: This class is auto generated by OpenAPI Generator.
 * Do not edit the class manually.
 */
const x = 1;`),
    ).toBe(true);
  });

  it('reads the @generated docblock annotation', () => {
    expect(check('/** @generated */\nconst x = 1;')).toBe(true);
  });

  it('reads the Go convention', () => {
    expect(check('// Code generated by protoc. DO NOT EDIT.\nconst x = 1;')).toBe(true);
  });

  it('reads a line comment banner', () => {
    expect(check('// This file was generated by a script\nconst x = 1;')).toBe(true);
  });

  it('accepts a file that is nothing but a banner', () => {
    // No token to bound the leading block against — every comment is leading.
    expect(check('/** @generated */')).toBe(true);
  });

  it('is false for an ordinary header comment', () => {
    expect(check('/** Utilities for parsing. */\nconst x = 1;')).toBe(false);
  });

  it('is false for an empty file', () => {
    expect(check('')).toBe(false);
  });

  it('does NOT accept a banner phrase below the first statement', () => {
    // Otherwise any comment anywhere in the file buys a whole-file
    // suppression, which is a hole rather than a scope decision.
    expect(check('const x = 1;\n// this code was generated by hand')).toBe(false);
  });

  it('does not treat "generated" in ordinary prose as a declaration', () => {
    expect(check('/** Returns the generated id for a session. */\nconst x = 1;')).toBe(
      false,
    );
  });

  it('does not treat a bare "do not edit" as a declaration', () => {
    // Hand-written files carry that instruction too and it says nothing about
    // who wrote the code.
    expect(check('/* Do not edit — mirrored from upstream. */\nconst x = 1;')).toBe(false);
  });
});
