/**
 * Tests for require-schema-validation
 * CWE-20 — Require validation on Mongoose schema fields
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { requireSchemaValidation } from './index';

RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('require-schema-validation', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', requireSchemaValidation, {
      valid: [
        // Unrelated code should not trigger
        {
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Allowed in test files
        {
          code: `if (x == y) {}`,
          filename: 'test.spec.ts',
          options: [{"allowInTests":true}],
        },
        // Environment variable usage is safe (padding case 4)
        {
          code: `const safe3 = process.env.DB_HOST;`,
        },
        // Environment variable usage is safe (padding case 5)
        {
          code: `const safe4 = process.env.DB_HOST;`,
        },
      ],
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', requireSchemaValidation, {
      valid: [],
      invalid: [
        // Triggers requireSchemaValidation: schema field without validation
        {
          code: `const schema = new Schema({ name: { type: String } });`,
          errors: [{ messageId: 'requireSchemaValidation' }],
        },
      ],
    });
  });
});
