import type { Metadata } from 'next';

import { Section } from '@interlace/ui/section';
import { SectionHeader } from '@interlace/ui/blocks/section-header';

import { ChangelogFilters } from '@/components/changelog/changelog-filters';
import { ChangelogPagination } from '@/components/changelog/changelog-pagination';
import { ReleaseList } from '@/components/changelog/release-list';
import { getChangelogPage } from '@/lib/changelog-data';

export const dynamic = 'force-static';

export const metadata: Metadata = {
  title: 'Changelog',
  description:
    'Every release across all Interlace ESLint plugins, newest first. Filter by package, see what changed, and get the exact install command for any version.',
  alternates: { canonical: '/changelog' },
  openGraph: {
    title: 'Changelog | ESLint Interlace',
    description:
      'Every release across all Interlace ESLint plugins — filter by package and see exactly what changed.',
    type: 'website',
    url: '/changelog',
  },
};

interface ChangelogPageProps {
  searchParams: Promise<{ page?: string; pkg?: string }>;
}

/**
 * `/changelog` — the release history, on the storefront.
 *
 * Releases were already recorded in per-package `CHANGELOG.md` files, git
 * tags, GitHub Releases and npm. All four are places a reader has to already
 * know about; none of them answers "what has changed lately across the things
 * I install" without opening thirty tabs. This is that page.
 *
 * Server-rendered with no client JavaScript: the filter and the pager are URL
 * state, so every view is shareable and crawlable, the back button behaves,
 * and the list cannot shift after paint. Data comes from
 * `src/data/changelog.json`, regenerated by `docs-data.yml` whenever a push to
 * main touches `packages/**`.
 *
 * Structural lock: `src/__tests__/changelog-page-lock.test.tsx`.
 */
export default async function ChangelogPage({
  searchParams,
}: ChangelogPageProps) {
  const params = await searchParams;
  const parsed = Number.parseInt(params.page ?? '1', 10);

  const { releases, page, pageCount, total, packages, totals } =
    getChangelogPage({
      page: Number.isNaN(parsed) ? 1 : parsed,
      pkg: params.pkg,
    });

  const active = packages.find((p) => p.short === params.pkg)?.short;

  return (
    <Section spacing="comfortable" container="wide" id="changelog">
      <SectionHeader
        as="h1"
        align="start"
        eyebrow={`${totals.releases} releases · ${totals.packages} packages`}
        title="Changelog"
        tagline="Every release across the ecosystem, newest first. Each entry links to the pull request that shipped it, and every published version carries the exact command to install it."
      />

      <ChangelogFilters packages={packages} active={active} />

      {/* Announces the filtered count without needing a live region: the
          heading above already changed, and this is static server output. */}
      <p className="text-muted-foreground mb-8 text-sm">
        {active
          ? `${total} release${total === 1 ? '' : 's'} of ${active}`
          : `${total} releases`}
        {pageCount > 1 ? ` · page ${page} of ${pageCount}` : ''}
      </p>

      <ReleaseList releases={releases} />

      <ChangelogPagination page={page} pageCount={pageCount} pkg={active} />
    </Section>
  );
}
