/**
 * Rule MDX badge-presence validator.
 *
 * Every per-rule MDX page generated by `apps/docs/scripts/sync-rules-docs.ts`
 * must:
 *   1. Declare `type_aware:` and `type_aware_status:` in frontmatter so
 *      `fumadocs` exposes them programmatically.
 *   2. Render `<RuleBadges ... />` near the top so the indicator is visible
 *      on the page itself.
 *
 * If either disappears, the badge silently vanishes from one or more rule
 * pages. This is the CI guard for that case.
 */

import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import type { PluginEntry } from './plugin-rule-source-drift';

export interface Finding {
  plugin: string;
  rule: string;
  file: string;
  surface: 'frontmatter-type_aware' | 'frontmatter-type_aware_status' | 'rule-badges-jsx';
  severity: 'error' | 'warning';
  message: string;
}

export interface RuleMdxBadgePresenceOptions {
  monorepoRoot: string;
  plugins: readonly PluginEntry[];
}

const FRONTMATTER_TYPE_AWARE = /(^|\n)type_aware\s*:\s*(true|false)\b/;
const FRONTMATTER_TYPE_STATUS = /(^|\n)type_aware_status\s*:\s*(unaware|optional|aware)\b/;
const RULE_BADGES_JSX = /<RuleBadges\b[^>]*typeAware=\{(true|false)\}/;

export function validateRuleMdxBadgePresence(
  opts: RuleMdxBadgePresenceOptions,
): Finding[] {
  const findings: Finding[] = [];

  for (const plugin of opts.plugins) {
    const mdxDir = join(
      opts.monorepoRoot,
      'apps',
      'docs',
      'content',
      'docs',
      plugin.pillar,
      `plugin-${plugin.slug}`,
      'rules',
    );
    if (!existsSync(mdxDir)) continue;

    const files = readdirSync(mdxDir)
      .filter((f) => f.endsWith('.mdx') && f !== 'index.mdx')
      .sort();

    for (const f of files) {
      const rule = f.replace(/\.mdx$/, '');
      const filePath = join(mdxDir, f);
      const content = readFileSync(filePath, 'utf-8');
      const rel = `apps/docs/content/docs/${plugin.pillar}/plugin-${plugin.slug}/rules/${f}`;

      const frontmatterEnd = content.indexOf('\n---', 3);
      const frontmatter = frontmatterEnd > 0 ? content.slice(0, frontmatterEnd) : content;
      const body = frontmatterEnd > 0 ? content.slice(frontmatterEnd + 4) : content;

      if (!FRONTMATTER_TYPE_AWARE.test(frontmatter)) {
        findings.push({
          plugin: plugin.slug,
          rule,
          file: rel,
          surface: 'frontmatter-type_aware',
          severity: 'error',
          message: `Missing \`type_aware: true|false\` in frontmatter. Re-run \`tsx apps/docs/scripts/sync-rules-docs.ts\`.`,
        });
      }
      if (!FRONTMATTER_TYPE_STATUS.test(frontmatter)) {
        findings.push({
          plugin: plugin.slug,
          rule,
          file: rel,
          surface: 'frontmatter-type_aware_status',
          severity: 'error',
          message: `Missing \`type_aware_status: unaware|optional|aware\` in frontmatter. Re-run \`tsx apps/docs/scripts/sync-rules-docs.ts\`.`,
        });
      }
      if (!RULE_BADGES_JSX.test(body)) {
        findings.push({
          plugin: plugin.slug,
          rule,
          file: rel,
          surface: 'rule-badges-jsx',
          severity: 'error',
          message: `<RuleBadges typeAware={...} /> not found near top of MDX. Re-run \`tsx apps/docs/scripts/sync-rules-docs.ts\`.`,
        });
      }
    }
  }

  return findings;
}
