/**
 * Tests for no-select-all
 * CWE-1049 — Prevent using * in SELECT statements (implicit columns).
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { noSelectAll } from './index';

RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('no-select-all', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', noSelectAll, {
      valid: [
        // Unrelated code should not trigger
        {
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Non-targeted method calls are safe
        {
          code: `obj.safeMethod();`,
        },
        // Environment variable usage is safe (padding case 4)
        {
          code: `const safe3 = process.env.DB_HOST;`,
        },
        // Environment variable usage is safe (padding case 5)
        {
          code: `const safe4 = process.env.DB_HOST;`,
        },
      ],
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', noSelectAll, {
      valid: [],
      invalid: [
        // Triggers noSelectAll
        {
          code: `client.query('SELECT * FROM users')`,
          errors: [{ messageId: 'noSelectAll' }],
        },
      ],
    });
  });
});
