#!/usr/bin/env node
/**
 * interlace-collector-rollup — produce aggregate reports from telemetry NDJSON.
 *
 * Reads `STORAGE_PATH` (the file the collector appends to), aggregates over
 * sessionId × ruleId × severity × toolchain, and emits:
 *
 *   - rollup.json          machine-readable, per-rule firing counts +
 *                          unique-session counts + toolchain breakdown
 *   - rollup.md            human-readable summary
 *
 * Aggregation is privacy-preserving:
 *   - sessionIds are bucketed by H/M/L cardinality only, never emitted in
 *     the rollup output
 *   - rules with < 5 unique sessions are bucketed as "low-volume" to prevent
 *     re-identification via single-org telemetry leakage
 *
 * Usage:
 *   interlace-collector-rollup                      # uses ./telemetry-events.ndjson
 *   interlace-collector-rollup --storage path/to/events.ndjson --out reports/
 *   interlace-collector-rollup --since 2026-04-01   # filter by date
 */

import fs from 'node:fs';
import path from 'node:path';

const ARG = (flag, fallback = null) => {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : fallback;
};
const STORAGE = path.resolve(ARG('--storage', process.env.STORAGE_PATH ?? './telemetry-events.ndjson'));
const OUT_DIR = path.resolve(ARG('--out', './'));
const SINCE = ARG('--since');
const MIN_SESSIONS_FOR_PUBLIC = 5;

if (!fs.existsSync(STORAGE)) {
  console.error(`rollup: no storage file at ${STORAGE}`);
  process.exit(1);
}

const sinceMs = SINCE ? new Date(SINCE).getTime() : 0;
const perRule = new Map();   // ruleId → { fires, sessions:Set, severityCounts, toolchainBuckets:Map }
let totalEvents = 0;
let totalSessions = new Set();

for (const line of fs.readFileSync(STORAGE, 'utf8').split('\n')) {
  if (!line.trim()) continue;
  let row;
  try { row = JSON.parse(line); } catch { continue; }
  if (sinceMs && new Date(row.receivedAt).getTime() < sinceMs) continue;
  if (!row.ruleId) continue;

  totalEvents++;
  totalSessions.add(row.sessionId);

  let agg = perRule.get(row.ruleId);
  if (!agg) {
    agg = { fires: 0, sessions: new Set(), severityCounts: { warn: 0, error: 0 }, nodeMajorBuckets: new Map(), tsCompilerBuckets: new Map() };
    perRule.set(row.ruleId, agg);
  }
  agg.fires++;
  agg.sessions.add(row.sessionId);
  if (row.severity === 'warn' || row.severity === 'error') agg.severityCounts[row.severity]++;
  const nodeMajor = (row.toolchain?.node ?? '').split('.')[0] || 'unknown';
  agg.nodeMajorBuckets.set(nodeMajor, (agg.nodeMajorBuckets.get(nodeMajor) ?? 0) + 1);
  const tsc = row.toolchain?.tsCompiler ?? 'unknown';
  agg.tsCompilerBuckets.set(tsc, (agg.tsCompilerBuckets.get(tsc) ?? 0) + 1);
}

// Emit
fs.mkdirSync(OUT_DIR, { recursive: true });
const ranked = [...perRule.entries()]
  .map(([ruleId, agg]) => ({
    ruleId,
    fires: agg.fires,
    uniqueSessions: agg.sessions.size,
    severity: agg.severityCounts,
    nodeMajor: Object.fromEntries(agg.nodeMajorBuckets.entries()),
    tsCompiler: Object.fromEntries(agg.tsCompilerBuckets.entries()),
    publishable: agg.sessions.size >= MIN_SESSIONS_FOR_PUBLIC,
  }))
  .sort((a, b) => b.fires - a.fires);

const json = {
  generatedAt: new Date().toISOString(),
  source: STORAGE,
  since: SINCE ?? null,
  totals: { events: totalEvents, sessions: totalSessions.size },
  privacyPolicy: { minSessionsForPublic: MIN_SESSIONS_FOR_PUBLIC, comment: 'Rules below this threshold are bucketed but their identity may still appear in this report; downstream re-publishers should re-aggregate further before public release.' },
  ranked,
};
fs.writeFileSync(path.join(OUT_DIR, 'rollup.json'), JSON.stringify(json, null, 2) + '\n', 'utf8');

const lines = [];
lines.push('# Interlace Telemetry Rollup');
lines.push('');
lines.push(`> Generated by \`interlace-collector-rollup\` on ${json.generatedAt}.`);
if (SINCE) lines.push(`> Since: ${SINCE}`);
lines.push(`> Source: \`${STORAGE}\``);
lines.push('');
lines.push(`**Totals:** ${totalEvents.toLocaleString()} events across ${totalSessions.size.toLocaleString()} unique sessions.`);
lines.push('');
lines.push(`**Privacy contract:** rules with fewer than ${MIN_SESSIONS_FOR_PUBLIC} unique sessions appear unmarked here but should not be re-published as-is.`);
lines.push('');
lines.push('## Top-fired rules');
lines.push('');
lines.push('| Rule | Fires | Unique sessions | Error | Warn | Top Node major | Top TS compiler |');
lines.push('|---|---:|---:|---:|---:|---|---|');
const top = ranked.slice(0, 50);
for (const r of top) {
  const topNode = Object.entries(r.nodeMajor).sort((a, b) => b[1] - a[1])[0]?.[0] ?? '—';
  const topTsc  = Object.entries(r.tsCompiler).sort((a, b) => b[1] - a[1])[0]?.[0] ?? '—';
  const flag = r.publishable ? '' : ' ⚠';
  lines.push(`| \`${r.ruleId}\`${flag} | ${r.fires} | ${r.uniqueSessions} | ${r.severity.error} | ${r.severity.warn} | ${topNode} | ${topTsc} |`);
}
lines.push('');
lines.push('⚠ = rule has < 5 unique sessions; do not re-publish without further aggregation (re-identification risk).');
fs.writeFileSync(path.join(OUT_DIR, 'rollup.md'), lines.join('\n') + '\n', 'utf8');

console.log(`rollup: ${totalEvents} events · ${totalSessions.size} sessions · ${perRule.size} distinct rules`);
console.log(`  wrote ${path.relative(process.cwd(), path.join(OUT_DIR, 'rollup.json'))}`);
console.log(`  wrote ${path.relative(process.cwd(), path.join(OUT_DIR, 'rollup.md'))}`);
