import { defineConfig } from 'vitest/config';

/**
 * Vitest configuration for eslint-plugin-gemini-security
 *
 * Mirrors the sibling security plugins: node environment, v8 coverage pinned at
 * the 100% policy target (docs/QUALITY_STANDARDS.md §2), JUnit output for CI.
 */
export default defineConfig({
  root: __dirname,
  plugins: [],
  test: {
    globals: true,
    environment: 'node',
    watch: false,
    include: [
      'src/**/*.test.ts',
      'src/**/*.spec.ts',
    ],
    // Setting `exclude` replaces vitest's defaults — spread them back in and
    // add build-artifact dirs so stale outputs can never shadow real tests.
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/cypress/**',
      '**/.{idea,git,cache,output,temp}/**',
      '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*',
      '**/.next/**',
      '**/.turbo/**',
      '**/storybook-static/**',
      '**/coverage/**',
    ],
    passWithNoTests: true,
    globalSetup: ['../../vitest.global-setup.ts'],
    name: { label: 'gemini-security', color: 'magenta' },
    pool: 'vmThreads',
    coverage: {
      enabled: true,
      provider: 'v8',
      thresholds: { lines: 100, statements: 100, functions: 100, branches: 100 },
      reportOnFailure: true,
      reportsDirectory: './coverage',
      include: ['src/**/*.ts'],
      // `src/oxlint.ts` is generated by scripts/generate-oxlint-shims.ts — a
      // re-export with no logic of its own. It is verified by the repo-level
      // scripts/__tests__/oxlint-export-lock.test.ts, which actually loads it
      // and asserts the rule map, so counting it here would only measure the
      // generator.
      exclude: ['node_modules/', 'dist/', '**/*.test.ts', '**/*.spec.ts', 'src/oxlint.ts'],
      ignoreClassMethods: ['context.report'],
      clean: true,
      reporter: ['text', 'text-summary', 'html', 'lcov'],
    },
    reporters: ['default', 'junit'],
    outputFile: {
      junit: './test-results/junit.xml',
    },
  },
});
