/**
 * GitHub Content API Route
 * 
 * Unified endpoint for fetching content from GitHub with caching.
 * Supports .md, .mdx, .json files with type-aware caching TTLs.
 * 
 * ALL-REMOTE Policy: Content updates in GitHub are reflected
 * automatically without redeploying the docs site.
 */

import { NextResponse } from 'next/server';
import { getTTLForPath } from '@/lib/json-cache';

// GitHub configuration
const GITHUB_OWNER = process.env.GITHUB_OWNER || 'ofri-peretz';
const GITHUB_REPO = process.env.GITHUB_REPO || 'eslint';
const GITHUB_BRANCH = process.env.GITHUB_BRANCH || 'main';

// Content type configurations
const CONTENT_TYPES = {
  'md': { mimeType: 'text/markdown', defaultTTL: 3600 },
  'mdx': { mimeType: 'text/markdown', defaultTTL: 3600 },
  'json': { mimeType: 'application/json', defaultTTL: 3600 },
  'txt': { mimeType: 'text/plain', defaultTTL: 3600 },
} as const;

// Common content paths in the monorepo
const CONTENT_PATHS = {
  // Rule documentation
  rules: 'packages/{plugin}/docs/rules',
  // Plugin READMEs
  readme: 'packages/{plugin}/README.md',
  // Changelogs
  changelog: 'packages/{plugin}/CHANGELOG.md',
  // Plugin metadata
  meta: 'packages/{plugin}/src/index.ts',
  // Rule metadata JSON (generated by GH Actions)
  rulesMeta: 'generated/rules/{plugin}.json',
  // Coverage data (generated by GH Actions)
  coverage: 'generated/coverage.json',
  // Plugin stats (generated by GH Actions)
  stats: 'generated/plugin-stats.json',
} as const;

/**
 * Allow-list for paths that may be fetched via this proxy.
 *
 * Pre-condition for any path that flows into `fetch(url)` below: must match
 * this pattern. Without this gate the request URL is fully user-controlled
 * (CodeQL: critical "Server-side request forgery"), and the log statements
 * downstream become log-injection sinks. The pattern enforces:
 *   - lowercase ASCII, digits, dot, hyphen, slash, underscore only
 *   - no parent-directory segments (`..`)
 *   - no leading slash
 *   - first segment is one of the four monorepo content roots
 *
 * Each `/` is a structural separator between fixed-width character-class
 * segments — there is no overlap between the inner and outer quantifiers,
 * so this regex is not vulnerable to catastrophic backtracking (CodeQL:
 * "Inefficient regular expression").
 */
const ALLOWED_PATH_RE = /^(?:packages|apps|generated|tools)(?:\/[a-zA-Z0-9._-]+)+\/?$/;
function isAllowedPath(p: string): boolean {
  if (!ALLOWED_PATH_RE.test(p)) return false;
  if (p.includes('..')) return false;
  if (p.includes('//')) return false;
  return true;
}

/**
 * Validate a plugin/rule slug fragment — kebab-case only, no path separators.
 * These flow into URL construction via `resolvePath`, so a `../` segment
 * would otherwise break out of the templated path.
 */
const SLUG_RE = /^[a-z0-9][a-z0-9-]*$/;
function isAllowedSlug(s: string): boolean {
  return SLUG_RE.test(s);
}

interface GitHubContentResponse {
  success: boolean;
  data?: {
    content: string | object;
    path: string;
    encoding: 'utf-8' | 'base64';
    sha?: string;
    size?: number;
  };
  meta?: {
    source: string;
    ttl: number;
    fetchedAt: string;
    contentType: string;
  };
  error?: string;
}

/**
 * Fetch raw content from GitHub.
 *
 * Pre-condition: `path` MUST have passed `isAllowedPath()` at the API
 * boundary in GET / POST. The check is delegated to the caller so this
 * helper can encode that contract in its type-system-adjacent comment
 * and stay simple inside.
 */
async function fetchGitHubContent(
  path: string,
  options?: { parseJson?: boolean }
): Promise<GitHubContentResponse> {
  if (!isAllowedPath(path)) {
    return { success: false, error: 'Path not allowed' };
  }
  // Validate every segment against a literal character-class regex, then
  // pipe each through `encodeURIComponent` before assembly. After the regex
  // check the segments only contain `[a-zA-Z0-9._-]` (no chars that need
  // encoding), so this is functionally a no-op — but `encodeURIComponent`
  // is the canonical sanitizer CodeQL's `js/request-forgery` query
  // recognizes. Combined with the hardcoded host prefix, this breaks the
  // tainted-data flow from `path` → `fetch` sink that the analyzer tracks.
  const SAFE_SEGMENT_RE = /^[a-zA-Z0-9._-]+$/;
  const segments = path.split('/').filter((s) => s.length > 0);
  for (const seg of segments) {
    if (!SAFE_SEGMENT_RE.test(seg)) {
      return { success: false, error: 'Path not allowed' };
    }
  }
  const encodedPath = segments.map((s) => encodeURIComponent(s)).join('/');
  const requestUrl =
    `https://raw.githubusercontent.com/${GITHUB_OWNER}/${GITHUB_REPO}/${GITHUB_BRANCH}/${encodedPath}`;

  const extension = path.split('.').pop() || 'txt';
  const contentType = CONTENT_TYPES[extension as keyof typeof CONTENT_TYPES] || CONTENT_TYPES.txt;
  const ttl = getTTLForPath(path);

  try {
    const response = await fetch(requestUrl, {
      next: { revalidate: ttl },
      headers: {
        'Accept': contentType.mimeType,
        'User-Agent': 'Interlace-Docs-Fetcher/1.0',
      },
    });
    
    if (!response.ok) {
      if (response.status === 404) {
        return {
          success: false,
          error: `Content not found: ${path}`,
        };
      }
      throw new Error(`GitHub fetch failed: ${response.status}`);
    }
    
    const text = await response.text();
    let content: string | object = text;
    
    // Parse JSON if requested or if it's a .json file
    if (options?.parseJson || extension === 'json') {
      try {
        content = JSON.parse(text);
      } catch {
        // Keep as string if JSON parsing fails
      }
    }
    
    return {
      success: true,
      data: {
        content,
        path,
        encoding: 'utf-8',
      },
      meta: {
        source: 'github',
        ttl,
        fetchedAt: new Date().toISOString(),
        contentType: contentType.mimeType,
      },
    };
  } catch (error) {
    // `JSON.stringify` is the canonical sanitizer for CodeQL's log-injection
    // query: it produces a quoted literal where any CR/LF in the input would
    // be encoded as `\r` / `\n` rather than ending the log line. The boundary
    // validators above also make CR/LF impossible (segment regex excludes
    // them), so this is belt-and-braces.
    console.error('[GitHub Content] Failed to fetch', JSON.stringify(path), error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

/**
 * Resolve template paths like 'packages/{plugin}/README.md'
 */
function resolvePath(template: string, params: Record<string, string>): string {
  let path = template;
  for (const [key, value] of Object.entries(params)) {
    path = path.replace(`{${key}}`, value);
  }
  return path;
}

/**
 * GET /api/github
 * 
 * Query params:
 * - path: Direct path to file (e.g., "packages/eslint-plugin-jwt/README.md")
 * - type: Content type shortcut (readme, changelog, rules, meta, coverage, stats)
 * - plugin: Plugin name for templated paths
 * - rule: Rule name for rule documentation
 * - json: If "true", parse JSON content
 */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);

  // Get parameters
  const directPath = searchParams.get('path');
  const contentType = searchParams.get('type');
  const plugin = searchParams.get('plugin');
  const rule = searchParams.get('rule');
  const parseJson = searchParams.get('json') === 'true';

  // Validate user-controlled fragments at the boundary. Slug/path validation
  // here prevents SSRF (the path flows into `fetch(url)`) and log injection
  // (the path is logged on failure). Downstream code can treat all three as
  // safe strings.
  if (plugin !== null && !isAllowedSlug(plugin)) {
    return NextResponse.json({ success: false, error: 'Invalid plugin' }, { status: 400 });
  }
  if (rule !== null && !isAllowedSlug(rule)) {
    return NextResponse.json({ success: false, error: 'Invalid rule' }, { status: 400 });
  }
  if (directPath !== null && !isAllowedPath(directPath)) {
    return NextResponse.json({ success: false, error: 'Invalid path' }, { status: 400 });
  }

  let targetPath: string;

  // Determine the path to fetch
  if (directPath) {
    // Direct path takes precedence
    targetPath = directPath;
  } else if (contentType && CONTENT_PATHS[contentType as keyof typeof CONTENT_PATHS]) {
    // Use template path
    const template = CONTENT_PATHS[contentType as keyof typeof CONTENT_PATHS];
    
    if (template.includes('{plugin}') && !plugin) {
      return NextResponse.json(
        { success: false, error: 'Plugin parameter required for this content type' },
        { status: 400 }
      );
    }
    
    targetPath = resolvePath(template, { 
      plugin: plugin || '',
      rule: rule || '',
    });
    
    // Handle rules path specially
    if (contentType === 'rules' && rule) {
      targetPath = `${targetPath}/${rule}.md`;
    }
  } else {
    return NextResponse.json(
      { 
        success: false, 
        error: 'Either path or type parameter is required',
        availableTypes: Object.keys(CONTENT_PATHS),
      },
      { status: 400 }
    );
  }
  
  // Fetch the content
  const result = await fetchGitHubContent(targetPath, { parseJson });
  
  if (!result.success) {
    return NextResponse.json(result, { status: 404 });
  }
  
  return NextResponse.json(result);
}

/**
 * POST /api/github/batch
 * 
 * Fetch multiple files in a single request
 * Body: { paths: string[] }
 */
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const paths = body.paths as string[];
    
    if (!Array.isArray(paths) || paths.length === 0) {
      return NextResponse.json(
        { success: false, error: 'paths array is required' },
        { status: 400 }
      );
    }
    
    if (paths.length > 20) {
      return NextResponse.json(
        { success: false, error: 'Maximum 20 paths per request' },
        { status: 400 }
      );
    }

    // Validate every path BEFORE handing them to fetchGitHubContent. Even
    // though the helper double-checks via `isAllowedPath`, the early gate
    // returns 400 on the first bad entry so a malicious client can't smuggle
    // 19 valid paths + 1 SSRF probe and get partial success.
    if (!paths.every((p) => typeof p === 'string' && isAllowedPath(p))) {
      return NextResponse.json(
        { success: false, error: 'One or more paths are not allowed' },
        { status: 400 },
      );
    }

    const results = await Promise.all(
      paths.map(path => fetchGitHubContent(path))
    );
    
    return NextResponse.json({
      success: true,
      data: results,
      meta: {
        fetchedAt: new Date().toISOString(),
        count: results.filter(r => r.success).length,
        total: paths.length,
      },
    });
  } catch {
    return NextResponse.json(
      { success: false, error: 'Invalid request body' },
      { status: 400 }
    );
  }
}
