/**
 * Tests for no-unsafe-regex-query
 * CWE-400 — Prevent ReDoS attacks via $regex with user input
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { noUnsafeRegexQuery } from './index';

RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('no-unsafe-regex-query', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', noUnsafeRegexQuery, {
      valid: [
        // Unrelated code should not trigger
        {
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Non-targeted method calls are safe
        {
          code: `obj.safeMethod();`,
        },
        // Static property values are safe
        {
          code: `const config = { key: "static-value" };`,
        },
        // Allowed in test files
        {
          code: `if (x == y) {}`,
          filename: 'test.spec.ts',
          options: [{"allowInTests":true}],
        },
      ],
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', noUnsafeRegexQuery, {
      valid: [],
      invalid: [
        // Triggers unsafeRegex: user input in $regex operator
        {
          code: `db.users.find({ name: { $regex: req.body.pattern } });`,
          errors: [{ messageId: 'unsafeRegex' }],
        },
      ],
    });
  });
});
