/**
 * Tests for no-operator-injection
 * CWE-943 — Prevent MongoDB operator injection attacks via user input
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { noOperatorInjection } from './index';

RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('no-operator-injection', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', noOperatorInjection, {
      valid: [
        // Unrelated code should not trigger
        {
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Static property values are safe
        {
          code: `const config = { key: "static-value" };`,
        },
        // Allowed in test files
        {
          code: `if (x == y) {}`,
          filename: 'test.spec.ts',
          options: [{"allowInTests":true}],
        },
        // Environment variable usage is safe (padding case 5)
        {
          code: `const safe4 = process.env.DB_HOST;`,
        },
      ],
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', noOperatorInjection, {
      valid: [],
      invalid: [
        // Triggers operatorInjection: operator from user input
        {
          code: `const filter = { $ne: req.body.value };`,
          errors: [{ messageId: 'operatorInjection' }],
        },
      ],
    });
  });
});
