/**
 * Tests for no-floating-query
 * CWE-391 — Ensure all queries are awaited or returned to prevent unhandled promise rejections.
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { noFloatingQuery } from './index';

/**
 * Every fixture imports a PostgreSQL client, because the rule now abstains in
 * files that use no PostgreSQL at all. Wrapping the arrays rather than editing
 * each fixture means one cannot be left behind — a fixture missing the import
 * would pass vacuously on the gate instead of exercising the detection it was
 * written for.
 */
const withPg = (code: string): string => `import { Pool } from 'pg';\n${code}`;
const pg = <T,>(cases: T[]): T[] =>
  cases.map((c) =>
    typeof c === 'string'
      ? (withPg(c) as T)
      : ({ ...c, code: withPg((c as { code: string }).code) } as T),
  );


RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('no-floating-query', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', noFloatingQuery, {
      valid: pg([
        // Unrelated code should not trigger
        {
          name: 'pg is imported but nothing queries',
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Non-targeted method calls are safe
        {
          code: `obj.safeMethod();`,
        },
        // Environment variable usage is safe (padding case 4)
        {
          code: `const safe3 = process.env.DB_HOST;`,
        },
        // Environment variable usage is safe (padding case 5)
        {
          code: `const safe4 = process.env.DB_HOST;`,
        },
      ]),
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', noFloatingQuery, {
      valid: [],
      invalid: pg([
        // Triggers noFloatingQuery
        {
          name: 'a query whose promise nobody awaits — the rejection is unhandled',
          code: `client.query('SELECT 1')`,
          errors: [{ messageId: 'noFloatingQuery' }],
        },
      ]),
    });
  });
});

/**
 * REGRESSION LOCKS — every defect the rule corpus
 * (`benchmarks/rule-corpus/postgresql-security__no-floating-query`) proved.
 *
 * BEFORE: TP 5 / FP 0 / FN 5 — precision 100%, recall 50.0%, F1 66.7%.
 * AFTER:  14 / 0 / 0 — 100% on the corpus including the adversarial wave.
 *
 * Every miss had the same root cause: the rule decided ownership from the
 * PARENT NODE TYPE alone. A MemberExpression parent meant "chained, therefore
 * handled" — which accepted a one-argument `.then()` and a bare `.finally()`. A
 * VariableDeclarator or AssignmentExpression parent meant "stored, therefore
 * handled" — even when nothing ever read the binding. And optional chaining
 * moved the ExpressionStatement one node further away, hiding the shape
 * entirely.
 */
describe('no-floating-query — regression locks', () => {
  ruleTester.run('a chain is handled only by a rejection handler', noFloatingQuery, {
    valid: pg([
      "pool.query('SELECT 1').catch(e => console.error(e));",
      "pool.query('SELECT 1').then(r => cache.set(r), e => console.warn(e));",
      "pool.query('SELECT 1').then(r => r.rows[0]).then(r => cache.set(r)).catch(e => log(e));",
      "pool.query('SELECT 1').catch(e => log(e)).finally(done);",
    ]),
    invalid: [],
  });

  ruleTester.run('chains with no rejection handler float', noFloatingQuery, {
    valid: [],
    invalid: pg([
      {
        // A one-argument `.then()` covers the success path and leaves the
        // failure path as an unhandled rejection.
        code: "pool.query('SELECT 1').then(r => cache.set(r));",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
      {
        code: "pool.query('SELECT 1').then(r => r.rows[0]).then(r => cache.set(r));",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
      {
        // `.finally()` re-throws what it is handed: transparent, not a handler.
        code: "pool.query('SELECT 1').finally(done);",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
    ]),
  });

  ruleTester.run('a binding owns a promise only when something reads it', noFloatingQuery, {
    valid: pg([
      "async function f() { const p = pool.query('SELECT 1'); return await p; }",
      "async function f() { let p; p = pool.query('SELECT 1'); return await p; }",
      "async function f(id) { const u = pool.query('SELECT 1'); const o = pool.query('SELECT 2'); return [await u, await o]; }",
    ]),
    invalid: [],
  });

  ruleTester.run('unread bindings float', noFloatingQuery, {
    valid: [],
    invalid: pg([
      {
        code: "async function f(t) { const pending = pool.query('UPDATE s SET r = now() WHERE t = $1', [t]); return { ok: true }; }",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
      {
        code: "function f(id) { let pending; pending = pool.query('UPDATE j SET q = now() WHERE id = $1', [id]); }",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
    ]),
  });

  ruleTester.run('optional chaining does not hide the statement', noFloatingQuery, {
    valid: [],
    invalid: pg([
      {
        // `?.` wraps the call in a ChainExpression, so the call's parent is no
        // longer the ExpressionStatement.
        code: "function f(h) { this.db?.query('INSERT INTO p (h) VALUES ($1)', [h]); }",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
      {
        code: "function f(h) { pool.query?.('INSERT INTO p (h) VALUES ($1)', [h]); }",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
    ]),
  });

  ruleTester.run('control flow in statement position is not ownership', noFloatingQuery, {
    valid: [],
    invalid: pg([
      {
        // `dirty && q()` IS `if (dirty) q();`.
        code: "function f(dirty, k) { dirty && pool.query('UPDATE c SET d = false WHERE id = $1', [k]); }",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
      {
        code: "function f(ok, id) { ok ? pool.query('UPDATE j SET s = $1', ['done']) : pool.query('UPDATE j SET s = $1', ['failed']); }",
        errors: [{ messageId: 'noFloatingQuery' }, { messageId: 'noFloatingQuery' }],
      },
      {
        code: "function f(n) { (console.count(n), pool.query('INSERT INTO m (n) VALUES ($1)', [n])); }",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
      {
        code: "function f(keys) { keys.forEach(k => { pool.query('DELETE FROM c WHERE id = $1', [k]); }); }",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
    ]),
  });

  ruleTester.run('the same operators in a value position are transparent', noFloatingQuery, {
    valid: pg([
      "async function f(a, id) { return await (a ? pool.query('SELECT 1') : pool.query('SELECT 2')); }",
      "async function f(p, id) { return p && pool.query('SELECT payload FROM e WHERE id = $1', [id]); }",
      // Explicit fire-and-forget, and hand-offs to something that can own it.
      "void pool.query('UPDATE w SET s = now() WHERE pid = $1', [process.pid]);",
      "track(pool.query('INSERT INTO m (n) VALUES ($1)', [n]));",
      "async function f(ids) { const p = []; for (const id of ids) { p.push(pool.query('SELECT 1')); } return Promise.all(p); }",
      "async function f(id) { const p = { u: pool.query('SELECT 1'), o: pool.query('SELECT 2') }; return await Promise.all([p.u, p.o]); }",
      "function* steps(id) { yield pool.query('SELECT 1'); }",
      "class C { ready = pool.query('SELECT 1'); async t() { return await this.ready; } }",
    ]),
    invalid: [],
  });
});

/**
 * Coverage of the chain walk's stopping conditions and of the binding lookup.
 */
describe('no-floating-query — chain and binding edges', () => {
  ruleTester.run('member access that is not a chain link', noFloatingQuery, {
    valid: [
      // No PostgreSQL client in the file: the plugin does not run at all.
      "db.query('SELECT 1');",
      ...pg([
        // `.then` read as a VALUE rather than called. The chain walk stops
        // there, and a property access is a value use, not a discard.
        "const settle = pool.query('SELECT 1').then;",
        // Destructuring a promise is a different mistake; this rule abstains
        // rather than guessing what the binding owns.
        "const { rows } = pool.query('SELECT 1');",
      ]),
    ],
    invalid: pg([
      {
        // An implicit global has no binding to look up, so nothing can be
        // shown to read it.
        code: "function f() { globalPending = pool.query('SELECT 1'); }",
        errors: [{ messageId: 'noFloatingQuery' }],
      },
    ]),
  });
});
