/**
 * Base UI Migration Lock Tests
 *
 * Locks the headless-library choice for every shadcn-canon primitive served
 * out of `.interlace/components/ui/`. The migration from Radix → Base UI
 * (`@base-ui-components/react`) is the active source of truth — these
 * assertions catch any future drift that would silently re-introduce a
 * `@radix-ui/*` import or rename a Base UI primitive back to its Radix
 * spelling.
 *
 * Why this is a source-file integrity test and not a behavior test:
 *
 *   - The `.interlace/` directory is auto-generated by the baseline sync
 *     (see agents/interlace/docs-baseline). A hand-edit that reverts a
 *     primitive to Radix would deploy, since the file is "still valid TSX."
 *     Only a string-match against the synced output catches the revert.
 *
 *   - The Base UI primitives use a fundamentally different API surface
 *     (`render` prop vs `asChild` + `Slot`). A silent rollback would break
 *     consumer callsites that assume the new API. We caught zero `asChild`
 *     usages at migration time — locking that absence prevents creep.
 *
 *   - Two known API renames (Radix → Base UI) must NEVER reappear:
 *       1. `TooltipProvider` `delayDuration` → `delay`
 *       2. Dropdown trigger imports `@base-ui-components/react/menu`
 *          (Base UI rolls dropdowns into a generic `Menu` primitive).
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';

const SYNCED_UI = resolve(__dirname, '../../.interlace/components/ui');

function read(file: string): string {
  return readFileSync(resolve(SYNCED_UI, file), 'utf-8');
}

/**
 * Strip line and block comments so a regex like `/asChild/` doesn't hit a
 * JSDoc that *mentions* the legacy API (e.g. "Equivalent to shadcn's legacy
 * `asChild`."). We assert on actual TS code only.
 */
function stripComments(src: string): string {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/.*$/gm, '$1');
}

const MIGRATED = [
  'accordion.tsx',
  'avatar.tsx',
  'checkbox.tsx',
  'dialog.tsx',
  'dropdown-menu.tsx',
  'popover.tsx',
  'radio-group.tsx',
  'scroll-area.tsx',
  'select.tsx',
  'separator.tsx',
  'sheet.tsx',
  'switch.tsx',
  'tabs.tsx',
  'tooltip.tsx',
];

describe('Base UI migration: no Radix imports survived', () => {
  it.each(MIGRATED)('%s imports `@base-ui-components/react`, never `@radix-ui/*`', (file) => {
    const src = read(file);
    expect(src).toMatch(/@base-ui-components\/react/);
    expect(src).not.toMatch(/@radix-ui\//);
  });

  it('button.tsx uses Base UI `useRender` (not Radix `Slot`)', () => {
    const src = read('button.tsx');
    const code = stripComments(src);
    expect(code).toContain("from '@base-ui-components/react/use-render'");
    expect(code).not.toContain('@radix-ui/react-slot');
    // The render-prop API replaces the legacy `asChild` boolean. Locking the
    // type as `useRender.RenderProp` prevents an accidental re-introduction
    // of `asChild?: boolean` which would compile but silently no-op. We match
    // the prop *declaration* and destructure forms, not docstring mentions.
    expect(code).toContain('useRender.RenderProp');
    expect(code).not.toMatch(/asChild\s*\?\s*:/);
    expect(code).not.toMatch(/\{[^}]*\basChild\b[^}]*\}/);
  });

  it('badge.tsx uses Base UI `useRender` (not Radix `Slot`)', () => {
    const src = read('badge.tsx');
    const code = stripComments(src);
    expect(code).toContain("from '@base-ui-components/react/use-render'");
    expect(code).not.toContain('@radix-ui/react-slot');
    expect(code).not.toMatch(/asChild\s*\?\s*:/);
    expect(code).not.toMatch(/\{[^}]*\basChild\b[^}]*\}/);
  });
});

describe('Base UI API renames: Radix-era spellings stay out', () => {
  it('tooltip.tsx exposes `delay` (Base UI), not `delayDuration` (Radix)', () => {
    const src = read('tooltip.tsx');
    expect(src).toMatch(/\bdelay\b/);
    // The single application callsite was migrated in this same effort
    // (apps/docs/src/app/layout.tsx). Locking the spelling here keeps the
    // baseline source in lockstep with what consumers pass to it.
    expect(src).not.toContain('delayDuration');
  });

  it('dropdown-menu.tsx imports from `@base-ui-components/react/menu` (Base UI rolls dropdowns into Menu)', () => {
    const src = read('dropdown-menu.tsx');
    expect(src).toContain("from '@base-ui-components/react/menu'");
    expect(src).not.toContain('@radix-ui/react-dropdown-menu');
  });
});

describe('Base UI migration: button-variants stays server-safe', () => {
  // `buttonVariants` is intentionally split out of button.tsx so it can be
  // called from server components when composing a className string. If a
  // future edit moves the CVA back inline with the `useRender` Button, the
  // import chain becomes "use client" only and breaks SSR pagination links.
  it('button-variants.ts has no `use client` directive and no React imports', () => {
    const code = stripComments(read('button-variants.ts'));
    expect(code).not.toMatch(/^['"]use client['"]/m);
    expect(code).not.toMatch(/from ['"]react['"]/);
    expect(code).not.toMatch(/\b(useRender|useState|useEffect)\b/);
  });

  it('button.tsx still imports `buttonVariants` from the server-safe sibling, not from itself', () => {
    const src = read('button.tsx');
    expect(src).toContain("from './button-variants'");
  });
});
