import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import path from 'path';
import numbers from '@/data/interlace-numbers.json';
import pluginStats from '@/data/plugin-stats.json';
import { buildNumbersManifest } from '../../scripts/sync-plugin-stats';

/**
 * Numbers-manifest lock
 *
 * Single-source-of-truth guard for every plugin/rule count claim.
 * interlace-numbers.json (generated by scripts/sync-plugin-stats.ts from the
 * package registry) is the ONLY place counts may come from. Surfaces render
 * them via <Stat> (MDX) or the stats loader — never as hand-typed literals.
 *
 * If the "no hand-typed counts" test fails: replace the literal with
 * <Stat of="…" /> or <Stat plugin="…" /> (MDX), or read the manifest (TS).
 */

const DOCS_ROOT = path.join(__dirname, '../..');

// Every surface that makes a plugin/rule count claim. Add new surfaces here
// when they start consuming the manifest.
const COVERED_SURFACES = [
  'content/docs/getting-started/index.mdx',
  'content/docs/security/index.mdx',
  'content/docs/quality/index.mdx',
  'src/app/(home)/page.tsx',
  'src/lib/stats-loader.ts',
  'src/components/mdx/stat.tsx',
];

// A digit immediately followed by a plugins/rules noun is a hand-typed count.
const HAND_TYPED_COUNT =
  /\b\d+\+?\s+(?:specialized\s+|security\s+|quality\s+|react\s+)?(?:plugins?|rules)\b/gi;

describe('interlace-numbers.json manifest', () => {
  it('is exactly what the generator derives from plugin-stats.json', () => {
    const rebuilt = buildNumbersManifest(
      pluginStats.plugins,
      numbers.generatedAt,
    );
    expect(numbers).toEqual(rebuilt);
  });

  it('pillars sum to totals', () => {
    expect(
      numbers.plugins.security + numbers.plugins.quality + numbers.plugins.react,
    ).toBe(numbers.plugins.total);
    expect(
      numbers.rules.security + numbers.rules.quality + numbers.rules.react,
    ).toBe(numbers.rules.total);
  });

  it('counts published plugins only, and all of them', () => {
    const published = pluginStats.plugins.filter((p) => p.published);
    expect(numbers.plugins.total).toBe(published.length);
    expect(numbers.rules.total).toBe(
      published.reduce((sum, p) => sum + p.rules, 0),
    );
  });
});

describe('no hand-typed plugin/rule counts on covered surfaces', () => {
  for (const surface of COVERED_SURFACES) {
    it(surface, () => {
      const content = readFileSync(path.join(DOCS_ROOT, surface), 'utf-8');
      const matches = content.match(HAND_TYPED_COUNT) ?? [];
      expect(
        matches,
        `${surface} hand-types counts (${matches.join(', ')}) — render them from interlace-numbers.json via <Stat> or the stats loader instead`,
      ).toEqual([]);
    });
  }
});
