/**
 * Tests for no-missing-client-release
 * CWE-404 — Ensure pg client is released after use to prevent pool exhaustion.
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { noMissingClientRelease } from './index';

/**
 * Every fixture imports a PostgreSQL client, because the rule now abstains in
 * files that use no PostgreSQL at all. Wrapping the arrays rather than editing
 * each fixture means one cannot be left behind — a fixture missing the import
 * would pass vacuously on the gate instead of exercising the detection it was
 * written for.
 */
const withPg = (code: string): string => `import { Pool } from 'pg';\n${code}`;
const pg = <T,>(cases: T[]): T[] =>
  cases.map((c) =>
    typeof c === 'string'
      ? (withPg(c) as T)
      : ({ ...c, code: withPg((c as { code: string }).code) } as T),
  );


RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('no-missing-client-release', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', noMissingClientRelease, {
      valid: pg([
        // Unrelated code should not trigger
        {
          name: 'pg is imported but nothing queries',
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Non-targeted method calls are safe
        {
          code: `obj.safeMethod();`,
        },
        // Properly configured connection
        {
          code: `mongoose.connect(uri, { tls: true });`,
        },
        // Environment variable usage is safe (padding case 5)
        {
          code: `const safe4 = process.env.DB_HOST;`,
        },
      ]),
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', noMissingClientRelease, {
      valid: [],
      invalid: pg([
        // Triggers missingClientRelease.
        //
        // `pool` used to be undeclared here and this still passed, because the
        // rule matched the METHOD NAME `connect` on any receiver at all.
        {
          name: 'a pooled client checked out and never released',
          code: `const pool = new Pool();\nasync function test() { const client = await pool.connect(); const res = await client.query('SELECT 1'); return res; }`,
          errors: [{ messageId: 'missingClientRelease' }],
        },
      ]),
    });
  });

  /**
   * Regression locks for the defects
   * `benchmarks/rule-corpus/postgresql-security__no-missing-client-release`
   * proved. The rule scored 33.3% F1 on that corpus.
   */
  describe('corpus regressions', () => {
    const declarePool = (code: string): string => `const pool = new Pool();\n${code}`;

    ruleTester.run('only a POOL hands out a client', noMissingClientRelease, {
      valid: pg([
        // FP — `connect()` is on almost everything, and neither of these HAS a
        // `release()` to call. Both were reported as leaked pg clients.
        "import { broker } from '../lib/broker';\nasync function f() { const channel = await broker.connect(); }",
        "import { WebSocket } from 'ws';\nasync function f() { const s = await WebSocket.connect('wss://x'); }",
        'async function f() { const c = await unknownThing.connect(); }',
        // A `Pool` from a package that is not PostgreSQL.
        "import { Pool as Workers } from 'generic-pool';\nconst w = new Workers();\nasync function f() { const c = await w.connect(); }",
        // A pool reassigned elsewhere.
        'let pool = new Pool();\npool = other;\nasync function f() { const c = await pool.connect(); }',
        // Not from a `new`.
        'const pool = getPool();\nasync function f() { const c = await pool.connect(); }',
        // `this.x` never assigned a pool.
        'class R { async f() { const c = await this.pool.connect(); } }',
        // Not a member call at all.
        'async function f() { const c = await connect(); }',
        // A `new` on a locally declared class resolves to no module.
        'class LocalPool {}\nconst p = new LocalPool();\nasync function f() { const c = await p.connect(); }',
        // A receiver that is neither an identifier nor `this.x`.
        'async function f() { const c = await registry.pools.main.connect(); }',
        // A PARAMETER assigned once inside the body.
        'export async function f(pool) { pool = new Pool(); const c = await pool.connect(); }',
        // Class fields the PropertyDefinition arm must skip.
        'class R { [KEY] = new Pool(); async f() { const c = await this.pool.connect(); } }',
        'class R { pool; async f() { const c = await this.pool.connect(); } }',
        'class R { pool = getPool(); async f() { const c = await this.pool.connect(); } }',
        'class R { pool = new LocalThing(); async f() { const c = await this.pool.connect(); } }',
        // `this.x = …` assignments the AssignmentExpression arm must skip.
        'class R { constructor() { this.pool = getPool(); } async f() { const c = await this.pool.connect(); } }',
        // A `this.x = new …` whose constructor is not a pg Pool.
        'class LocalThing {}\nclass R { constructor() { this.pool = new LocalThing(); } async f() { const c = await this.pool.connect(); } }',
        'class R { constructor() { this[KEY] = new Pool(); } async f() { const c = await this.pool.connect(); } }',
        'class R { constructor() { this.pool += new Pool(); } async f() { const c = await this.pool.connect(); } }',
      ]),
      invalid: pg([
        // FN — the pool on `this`, the ordinary repository shape.
        {
          code: 'class R { constructor() { this.pool = new Pool(); } async f() { const c = await this.pool.connect(); await c.query("SELECT 1"); } }',
          errors: [{ messageId: 'missingClientRelease' }],
        },
        {
          code: 'class R { pool = new Pool(); async f() { const c = await this.pool.connect(); await c.query("SELECT 1"); } }',
          errors: [{ messageId: 'missingClientRelease' }],
        },
        {
          code: "import pg from 'pg';\nconst p = new pg.Pool();\nasync function f() { const c = await p.connect(); await c.query('SELECT 1'); }",
          errors: [{ messageId: 'missingClientRelease' }],
        },
        // A scoped package: the root is `@vercel/postgres`, not `@vercel`.
        // Aliased, because the `pg()` wrapper already binds `Pool` and a
        // duplicate declaration would resolve to that one instead.
        {
          code: "import { Pool as VercelPool } from '@vercel/postgres';\nconst p = new VercelPool();\nasync function f() { const c = await p.connect(); await c.query('SELECT 1'); }",
          errors: [{ messageId: 'missingClientRelease' }],
        },
      ]),
    });

    ruleTester.run('a release outside a finally is not guaranteed', noMissingClientRelease, {
      valid: pg([
        // The remediation.
        declarePool(
          'async function f() { const c = await pool.connect(); try { await c.query("SELECT 1"); } finally { c.release(); } }',
        ),
        // `release(true)` destroys the connection — still a release.
        declarePool(
          'async function f() { const c = await pool.connect(); try { await c.query("SELECT 1"); } finally { c.release(true); } }',
        ),
        // An awaited release changes nothing about the guarantee.
        declarePool(
          'async function f() { const c = await pool.connect(); try { await c.query("SELECT 1"); } finally { await c.release(); } }',
        ),
        // The finally of an OUTER try, with a nested inner try/catch.
        declarePool(
          'async function f() { const c = await pool.connect(); try { try { await c.query("BEGIN"); } catch (e) { await c.query("ROLLBACK"); throw e; } } finally { c.release(); } }',
        ),
      ]),
      invalid: pg([
        // FN — the release is on the happy path only. The moment the query
        // throws, the connection leaks. This is the leak that only shows up in
        // production, because the happy path always returns the client.
        {
          code: declarePool(
            'async function f() { const c = await pool.connect(); await c.query("SELECT 1"); c.release(); }',
          ),
          errors: [{ messageId: 'releaseNotGuaranteed' }],
        },
        // An early return jumps over it.
        {
          code: declarePool(
            'async function f() { const c = await pool.connect(); const r = await c.query("SELECT 1"); if (!r.rowCount) { return null; } c.release(); return r; }',
          ),
          errors: [{ messageId: 'releaseNotGuaranteed' }],
        },
        // A throw jumps over it.
        {
          code: declarePool(
            'async function f(n) { const c = await pool.connect(); if (n <= 0) { throw new Error("bad"); } await c.query("SELECT 1"); c.release(); }',
          ),
          errors: [{ messageId: 'releaseNotGuaranteed' }],
        },
        // Released in the catch but not on success: every SUCCESSFUL request
        // leaks. The inverted version of the same bug.
        {
          code: declarePool(
            'async function f() { const c = await pool.connect(); try { await c.query("SELECT 1"); } catch (e) { c.release(); throw e; } }',
          ),
          errors: [{ messageId: 'releaseNotGuaranteed' }],
        },
        // Inside a callback that may never run.
        {
          code: declarePool(
            'async function f() { const c = await pool.connect(); await c.query("SELECT 1"); setTimeout(() => { c.release(); }, 1000); }',
          ),
          errors: [{ messageId: 'releaseNotGuaranteed' }],
        },
      ]),
    });

    ruleTester.run('referencing release is not calling it', noMissingClientRelease, {
      valid: pg([]),
      invalid: pg([
        // FN — `handlers.push(client.release)` READS the method and hands it to
        // something that never runs it. The old test asked only whether the
        // member expression's PARENT was a CallExpression — which it is, the
        // `push(...)` one — so passing the release away counted as calling it.
        {
          code: declarePool(
            'const handlers = [];\nasync function f() { const c = await pool.connect(); handlers.push(c.release); await c.query("SELECT 1"); }',
          ),
          errors: [{ messageId: 'missingClientRelease' }],
        },
        // Was pinned as `missingClientRelease` — "a computed member is not a
        // proven release". It IS the release call, so the finding is now the
        // more precise one: the client IS released, just not from a `finally`,
        // so a throw in the `query` below still leaks it.
        {
          code: declarePool(
            'async function f() { const c = await pool.connect(); c["release"](); await c.query("SELECT 1"); }',
          ),
          errors: [{ messageId: 'releaseNotGuaranteed' }],
        },
      ]),
    });

    ruleTester.run('ownership leaving the function means abstain', noMissingClientRelease, {
      valid: pg([
        // The standard `withClient(client, work)` wrapper exists precisely to
        // guarantee the release. Reporting it fires on the remediation.
        declarePool(
          "import { runInTransaction } from '../lib/transaction';\nasync function f() { const c = await pool.connect(); return runInTransaction(c, (x) => x.query('SELECT 1')); }",
        ),
        // Returned to the caller, who owns the lifetime.
        declarePool(
          'async function checkout() { const c = await pool.connect(); await c.query("SET LOCAL statement_timeout = 5000"); return c; }',
        ),
        // Stored on the instance — the pool here is a REAL one, so the rule
        // reaches the ownership test rather than bailing at the receiver.
        'class S { pool = new Pool(); async open() { const c = await this.pool.connect(); this.client = c; } }',
        // Put in a container.
        declarePool(
          'const held = [];\nasync function f() { const c = await pool.connect(); held.push(c); }',
        ),
        declarePool('async function f() { const c = await pool.connect(); const held = [c]; }'),
        declarePool(
          'async function f() { const c = await pool.connect(); return { client: c }; }',
        ),
        declarePool(
          'async function f() { const c = await pool.connect(); const wrapped = { client: c }; }',
        ),
        // Handed to an arrow directly.
        declarePool(
          'async function f() { const c = await pool.connect(); const run = () => c; return run; }',
        ),
      ]),
      invalid: pg([]),
    });

    ruleTester.run('checkout shapes the rule does not read', noMissingClientRelease, {
      valid: pg([
        // Not assigned to anything.
        declarePool('async function f() { await pool.connect(); }'),
        // Destructured — there is no client identifier to follow.
        declarePool(
          'async function f() { const { release } = await pool.connect(); release(); }',
        ),
        // A different method.
        declarePool('async function f() { const c = await pool.other(); }'),
        // The call is not part of a declaration.
        declarePool('async function f() { let c; c = await pool.connect(); }'),
      ]),
      invalid: pg([]),
    });

    // NOT wrapped — a file with no PostgreSQL client does no work at all.
    ruleTester.run('the module gate still abstains', noMissingClientRelease, {
      valid: [
        { name: 'the module gate abstains in a file with no PostgreSQL client', code: 'const pool = new Pool();\nasync function f() { const c = await pool.connect(); }' },
      ],
      invalid: [],
    });
  });
});

/** FP/FN review 2026-10 (benchmarks/audits/2026-10-10-fp-fn-postgresql-security.md). */
describe('no-missing-client-release — fp/fn review 2026-10', () => {
  ruleTester.run('REL-1: imported, injected and typed pools', noMissingClientRelease, {
    valid: pg([
      // Released properly through an injected pool.
      { name: 'an injected typed pool released in finally is correct', code: 'export class Repo { constructor(private readonly pool: Pool) {} async run() { const c = await this.pool.connect(); try { await c.query("SELECT 1"); } finally { c.release(); } } }' },
      // A checkout whose client never runs a query is not evidence of a pool.
      { name: 'a broker channel checkout that runs no query is not a pg pool checkout', code: "import { broker } from '../lib/broker';\nasync function f() { const ch = await broker.connect(); ch.publish('x'); }" },
      // A typed parameter that is NOT pg's Pool.
      { name: 'a parameter typed as generic-pool Pool is not a pg pool', code: "import { Pool as Workers } from 'generic-pool';\nexport async function f(p: Workers) { const c = await p.connect(); }" },
      { name: 'a parameter typed pg.PoolClient is not a pool', code: "import pg from 'pg';\nexport async function f(p: pg.PoolClient) { const c = await p.connect(); }" },
      { name: 'a deeply qualified Pool type cannot be resolved to pg', code: 'export async function f(p: ns.pg.Pool) { const c = await p.connect(); }' },
      { name: 'a generic type reference is not a pg pool type', code: 'export async function f(p: Array<string>) { const c = await p.connect(); }' },
      { name: 'a destructured typed parameter is not read', code: 'export async function f({ p }: { p: Pool }) { const c = await p.connect(); }' },
      // `this` outside any class, and a computed field.
      { name: 'this outside any class has no declared field', code: 'export async function f() { const c = await this.pool.connect(); }' },
      { name: 'a computed this[key] field cannot be named', code: 'class R { async f() { const c = await this[key].connect(); } }' },
      { name: 'a typed field that is not the receiver does not make it a pool', code: 'class R { db: Pool; [k]: Pool; async f() { const c = await this.other.connect(); } }' },
      { name: 'a constructor parameter that is not a parameter property is not a field', code: 'class R { constructor(other: Pool, private x: number) {} async f() { const c = await this.pool.connect(); } }' },
    ]),
    invalid: pg([
      {
        name: 'pool imported from a local db module; the client runs queries',
        code: "import { pool } from './db';\nexport async function transfer() { const client = await pool.connect(); await client.query('BEGIN'); await client.query('COMMIT'); }",
        errors: [{ messageId: 'missingClientRelease' }],
      },
      {
        name: 'pool as an untyped parameter',
        code: "export async function work(p) { const c = await p.connect(); await c.query('SELECT 1'); }",
        errors: [{ messageId: 'missingClientRelease' }],
      },
      {
        name: 'pool injected through a constructor parameter property',
        code: "export class Repo { constructor(private readonly pool: Pool) {} async run() { const c = await this.pool.connect(); } }",
        errors: [{ messageId: 'missingClientRelease' }],
      },
      {
        name: 'pool declared as a typed class field',
        code: "import pg from 'pg';\nexport class Repo { private db: pg.Pool; async run() { const c = await this.db.connect(); } }",
        errors: [{ messageId: 'missingClientRelease' }],
      },
      {
        name: 'a pool type from a scoped driver package',
        code: "import type { Pool as NeonPool } from '@neondatabase/serverless';\nexport async function f(p: NeonPool) { const c = await p.connect(); }",
        errors: [{ messageId: 'missingClientRelease' }],
      },
      {
        name: 'pool as a typed parameter and a typed const',
        code: "export async function f(p: Pool) { const c = await p.connect(); }\nconst shared: Pool = make();\nexport async function g() { const c = await shared.connect(); }",
        errors: [{ messageId: 'missingClientRelease' }, { messageId: 'missingClientRelease' }],
      },
    ]),
  });

  ruleTester.run('REL-2: passing the client to a helper is not handing it off', noMissingClientRelease, {
    valid: pg([
      // A wrapper that is handed the client and runs nothing on it itself.
      { name: 'a wrapper handed the client that runs no query itself owns the release', code: "import { withClient } from './tx';\nconst pool = new Pool();\nexport async function f() { const c = await pool.connect(); await withClient(c, (x) => x.query('SELECT 1')); }" },
    ]),
    invalid: pg([
      {
        name: 'the function runs the transaction itself and passes the client to a repository helper',
        code: "const pool = new Pool();\nasync function insertUser(client, name) { await client.query('INSERT INTO users (name) VALUES ($1)', [name]); }\nexport async function signup(name) { const client = await pool.connect(); await client.query('BEGIN'); await insertUser(client, name); await client.query('COMMIT'); }",
        errors: [{ messageId: 'missingClientRelease' }],
      },
    ]),
  });

  ruleTester.run('REL-3: released in the try and in its catch covers every path', noMissingClientRelease, {
    valid: pg([
      {
// @found harness-reproduced FP/FN audit 2026-10-10 (benchmarks/audits/2026-10-10-fp-fn-postgresql-security.md)
 name: 'FP: release at the end of the try plus release in its catch covers every path', code: "const pool = new Pool();\nexport async function get(id) { const client = await pool.connect(); try { const res = await client.query('SELECT * FROM users WHERE id = $1', [id]); client.release(); return res.rows[0]; } catch (err) { client.release(err); throw err; } }" },
      {
// @found reasoned during the 2026-10-10 FP/FN audit, not seen in real code
 name: 'FP: release as the last try statement plus catch release covers every path', code: "const pool = new Pool();\nexport async function get(id) { const client = await pool.connect(); try { await client.query('SELECT 1'); client.release(); } catch (err) { client.release(err); throw err; } }" },
      // A `return` inside a nested callback does not leave the try early.
      { name: 'a return inside a nested callback does not leave the try early', code: "const pool = new Pool();\nexport async function get(ids) { const client = await pool.connect(); try { const keep = ids.filter((x) => { return x > 0; }); await client.query('SELECT 1', [keep]); client.release(); } catch (err) { client.release(err); throw err; } }" },
      // Released in a nested block of the try, then in the catch.
      { name: 'a release after a nested block plus a conditional catch release covers every path', code: "const pool = new Pool();\nexport async function get(id) { const client = await pool.connect(); try { { await client.query('SELECT 1'); } client.release(); } catch (err) { if (err) { client.release(err); } throw err; } }" },
    ]),
    invalid: pg([
      {
        name: 'released in the try, but the catch path leaks',
        code: "const pool = new Pool();\nexport async function get(id) { const client = await pool.connect(); try { await client.query('SELECT 1'); client.release(); } catch (err) { log(err); } }",
        errors: [{ messageId: 'releaseNotGuaranteed' }],
      },
      {
        name: 'an early return before the try-block release leaks',
        code: "const pool = new Pool();\nexport async function get(id) { const client = await pool.connect(); try { if (!id) { return null; } await client.query('SELECT 1'); client.release(); } catch (err) { client.release(err); throw err; } }",
        errors: [{ messageId: 'releaseNotGuaranteed' }],
      },
      {
        name: 'an awaited release is not read as the try-block release',
        code: "const pool = new Pool();\nexport async function get(id) { const client = await pool.connect(); try { await client.query('SELECT 1'); await client.release(); } catch (err) { client.release(err); throw err; } }",
        errors: [{ messageId: 'releaseNotGuaranteed' }],
      },
      {
        name: 'released in a catch that belongs to a different try',
        code: "const pool = new Pool();\nexport async function get(id) { const client = await pool.connect(); try { await client.query('SELECT 1'); client.release(); return 1; } catch (e) { throw e; }\ntry { x(); } catch (err) { client.release(err); } }",
        errors: [{ messageId: 'releaseNotGuaranteed' }],
      },
    ]),
  });
});
