/**
 * Comprehensive tests for no-xpath-injection rule
 * Security: CWE-643 (XPath Injection)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll, expect } from 'vitest';
import parser from '@typescript-eslint/parser';
import { createWithMockContext } from '@interlace/eslint-devkit';
import { noXpathInjection } from './index';

// Configure RuleTester for Vitest
RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

// Use Flat Config format (ESLint 9+)
const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
  },
});

describe('no-xpath-injection', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe XPath operations', noXpathInjection, {
      valid: [
    // --- a router wildcard is not a location step -------------------------
    // City-of-Helsinki/haitaton-ui reported CWE-643 at CVSS 9.8 twice on these,
    // in a repository importing no XPath package and containing no XPath at
    // all. `/*` is XPath's abbreviated `child::*` and also React Router's
    // wildcard segment; on its own it is not evidence of either.
    'const p = `/${lang}/*`;',
    'const routes = LOCALES.map((l) => ({ path: `/${l}/*` }));',
    // The wildcard gate is corroboration, not amnesty: a module that imports an
    // XPath package gets the finding, so this one is deliberately NOT valid and
    // lives in the invalid block below. What is valid is the same shape with a
    // package that evaluates nothing.
    "import { format } from 'date-fns'; const p = `/${lang}/*`;",

        // Only args[0] of an evaluator is the XPath expression; a template
        // in the context-node position is not the query.
        {
          code: 'document.evaluate(expr, `//users/..`);',
        },
        // The safe-annotation escape hatch, now reached only when the string
        // does flow to an evaluator.
        {
          options: [{ reportDangerousConstructs: true }],
          code: '/** @xpath-safe */\nconst q = `//users/..`;\ndocument.evaluate(q, doc);',
        },
        // reachesXpathSink: parent is neither a call, a declarator, nor a
        // concatenation — nothing to follow, so nothing to report.
        {
          code: 'const o = { q: `//users/..` };',
        },
        // reachesXpathSink: callee is neither Identifier nor MemberExpression.
        {
          code: 'const getEval = () => doc.evaluate; (getEval())(`//users/..`);',
        },
        // reachesXpathSink: declared, but never passed to an evaluator.
        {
          code: 'const q = `//users/..`; console.log(q);',
        },
        // Regression: strings that look like XPath but never reach an
        // evaluator. All three were reported on redis/ioredis, a package with
        // no XPath API at all — `//` or `..` anywhere in the text was the
        // entire evidence.
        {
          code: 'const banner = `// Generated by bin/generate-version.js. Do not edit.`;',
        },
        {
          code: 'const ca = `MIIDTzCCAjegAwIBAgIJAKSVpiDswLc//wMA0GCSqGSIb3DQEBBQUAMD4`;',
        },
        {
          code: 'const rel = `../lib/index.js`;',
        },
        // A slash is a path separator in every language. The old heuristic was
        // `includes('/') || includes('[')`, which matched every path join, URL
        // build and array index — this exact line reported CWE-643, measured on
        // the Interlace repo.
        `function rel(fullPath, baseDir) { return fullPath.replace(baseDir + '/', ''); }`,
        `function u(base, id) { return base + '/api/' + id; }`,
        `function k(arr, i) { return 'items[' + i + ']'; }`,
        // Detection reads the AST, not printed source. An identifier that merely
        // spells an XPath function, and a comment inside the expression, are not
        // string content — both matched while the gate regexed
        // `sourceCode.getText(node)`.
        `function f(req) { const s = render.text() + req.query.q; use(s); }`,
        `function f(req) { const s = base /* //user[@id] */ + req.query.q; use(s); }`,
        // A non-string literal contributes no text.
        `function f(req) { const s = '/total: ' + 42 + req.query.n; use(s); }`,
        // Safe XPath literals
        {
          code: 'const result = document.evaluate("/users/user[@id=\'123\']", document);',
        },
        // Validated input
        {
          code: 'const safeId = validateId(userInput); const xpath = `/users/user[@id="${safeId}"]`;',
        },
        // Safe XPath construction
        {
          code: 'const xpath = buildXPath("users", { id: "123" });',
        },
        // Non-XPath operations
        {
          code: 'const result = array.find(item => item.id === userInput);',
        },
        // Escaped input
        {
          code: 'const xpath = `/users/user[@name="${escapeXPath(userName)}"]`;',
        },
      ],
      invalid: [

        {
          // Template quasis are string content too — same expression, backticks.
          code: "function q(req) { const x = `//user[name='` + req.query.n + `']`; doc.evaluate(x); }",
          errors: 1,
        },
      ],
    });
  });

  describe('Invalid Code - XPath Injection', () => {
    ruleTester.run(
      'invalid - XPath injection vulnerabilities',
      noXpathInjection,
      {
        valid: [],
        invalid: [
          {
            code: 'const xpath = "/users/user[name=\'" + userInput + "\']";',
            errors: [
              {
                messageId: 'xpathInjection',
              },
            ],
          },
          {
            code: 'const query = `/users/user[@id="${userId}"]`;',
            errors: [
              {
                messageId: 'unsafeXpathConcatenation',
              },
            ],
          },
          {
            code: 'document.evaluate(userQuery, document);',
            errors: [
              {
                messageId: 'unvalidatedXpathInput',
              },
            ],
          },
        ],
      },
    );
  });

  describe('Invalid Code - Dangerous XPath Patterns', () => {
    ruleTester.run('invalid - dangerous XPath expressions', noXpathInjection, {
      valid: [],
      invalid: [
        // FN GUARD — the wildcard gate is corroboration, not amnesty. The same
        // `/*` shape that is a React Router path in a component is still an
        // XPath injection in a module that evaluates XPath, and the evidence is
        // allowed to arrive AFTER the template it justifies.
        {
          code: 'const q = `/${req.query.id}/*`; doc.evaluate(q, root);',
          errors: [{ messageId: 'unsafeXpathConcatenation' }],
        },
        {
          code: 'const xpath = "//users/user/..";',
          // `dangerousXpathExpression` is opt-in: these are CONSTANT XPath
          // strings, and `//` is the descendant axis, present in essentially
          // every XPath. Reporting them at CVSS 9.8 by default is what made
          // this rule fire on correct code.
          options: [{ reportDangerousConstructs: true }],
          errors: [
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
        {
          code: 'const query = "/root/*";',
          // `dangerousXpathExpression` is opt-in: these are CONSTANT XPath
          // strings, and `//` is the descendant axis, present in essentially
          // every XPath. Reporting them at CVSS 9.8 by default is what made
          // this rule fire on correct code.
          options: [{ reportDangerousConstructs: true }],
          errors: [
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
        {
          code: 'const xpathWithWildcard = "//user[*]";',
          // `dangerousXpathExpression` is opt-in: these are CONSTANT XPath
          // strings, and `//` is the descendant axis, present in essentially
          // every XPath. Reporting them at CVSS 9.8 by default is what made
          // this rule fire on correct code.
          options: [{ reportDangerousConstructs: true }],
          errors: [
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
      ],
    });
  });

  describe('Invalid Code - Unvalidated XPath Input', () => {
    ruleTester.run('invalid - unvalidated XPath input', noXpathInjection, {
      valid: [],
      invalid: [
        {
          code: 'xmlDoc.selectNodes(userSearchQuery);',
          errors: [
            {
              messageId: 'unvalidatedXpathInput',
            },
          ],
        },
        {
          code: 'const xpathVar = userInput; document.evaluate(xpathVar, document);',
          errors: [
            {
              messageId: 'xpathInjection',
            },
          ],
        },
      ],
    });
  });

  describe('Invalid Code - XPath Variable Assignment', () => {
    ruleTester.run(
      'invalid - dangerous XPath variable assignments',
      noXpathInjection,
      {
        valid: [],
        invalid: [
          {
            code: 'const userXPath = "//users/user/..";',
            // `dangerousXpathExpression` is opt-in: these are CONSTANT XPath
            // strings, and `//` is the descendant axis, present in essentially
            // every XPath. Reporting them at CVSS 9.8 by default is what made
            // this rule fire on correct code.
            options: [{ reportDangerousConstructs: true }],
            errors: [
              {
                messageId: 'dangerousXpathExpression',
              },
            ],
          },
          // Both used to assert with NO XPath string and NO evaluator anywhere — a match on
          // the declaration name plus a match on the initialiser name, and nothing else.
          // That pair reported `const QueryValidateSchema = QueryInputSchema` (a Zod schema)
          // as CWE-643 on real source. The declaration must now reach an evaluator, and the
          // report lands there.
          {
            code: 'const xpathQuery = req.params.query; doc.evaluate(xpathQuery, doc);',
            errors: [{ messageId: 'unvalidatedXpathInput' }],
          },
          {
            code: 'let searchPath = userInput; xpath.select(searchPath, doc);',
            errors: [{ messageId: 'unvalidatedXpathInput' }],
          },
        ],
      },
    );
  });

  describe('Valid Code - False Positives Reduced', () => {
    ruleTester.run('valid - false positives reduced', noXpathInjection, {
      valid: [
        // Safe annotations
        {
          options: [{ reportDangerousConstructs: true }],
          code: `
            /** @xpath-safe */
            const xpath = \`//user[@id="\${userId}"]\`;
          `,
        },
        // Validated inputs
        {
          code: `
            const cleanId = validateXPathInput(userId);
            const xpath = \`/users/user[@id="\${cleanId}"]\`;
          `,
        },
        // Sanitized inputs
        {
          code: `
            const safeQuery = sanitizeXPath(req.query.search);
            document.evaluate(safeQuery, document);
          `,
        },
        // Safe XPath construction
        {
          code: `
            const xpath = createXPath('users', 'user', { id: userId });
            document.evaluate(xpath, document);
          `,
        },
        // Internal XPath queries
        {
          code: 'const configPath = "/config/database";',
        },
      ],
      invalid: [],
    });
  });

  describe('Configuration Options', () => {
    ruleTester.run('config - custom XPath functions', noXpathInjection, {
      valid: [
        {
          code: 'myXpathLib.evaluate(query, doc);',
          options: [{ xpathFunctions: ['myXpathLib.evaluate'] }],
        },
      ],
      invalid: [],
    });

    ruleTester.run('config - custom safe constructors', noXpathInjection, {
      valid: [
        {
          code: 'const xpath = mySafeBuilder("users", userId);',
          options: [{ safeXpathConstructors: ['mySafeBuilder'] }],
        },
        {
          code: 'const xpath = unsafeBuilder(userId);',
          options: [{ safeXpathConstructors: ['mySafeBuilder'] }],
        },
      ],
      invalid: [],
    });
  });

  describe('Complex XPath Injection Scenarios', () => {
    ruleTester.run('complex - real-world XPath patterns', noXpathInjection, {
      valid: [],
      invalid: [
        {
          options: [{ reportDangerousConstructs: true }],
          code: `
            function searchUsers(searchTerm) {
              // DANGEROUS: Direct interpolation
              const xpath = \`//user[contains(name, "\${searchTerm}")]\`;
              return document.evaluate(xpath, xmlDoc);
            }
          `,
          errors: [
            {
              messageId: 'unsafeXpathConcatenation',
            },
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
        {
          code: `
            const express = require('express');
            const app = express();

            app.get('/search', (req, res) => {
              // DANGEROUS: User input directly in XPath
              const userQuery = req.query.q;
              const xpath = "/users/user[name='" + userQuery + "']";
              const result = xmlDoc.selectSingleNode(xpath);
              res.json(result);
            });
          `,
          // One defect, one finding: the declaration no longer reports alongside the sink.
          errors: [
            {
              messageId: 'xpathInjection',
            },
          ],
        },
        {
          options: [{ reportDangerousConstructs: true }],
          code: `
            // XPath injection with attribute traversal
            const maliciousQuery = req.params.id; // Could be "../../../etc/passwd"
            const xpath = \`//user[@id='\${maliciousQuery}']\`;
            const node = xml.evaluate(xpath, xmlDoc);
          `,
          // One defect, one finding: the declaration no longer reports alongside the sink.
          errors: [
            {
              messageId: 'unsafeXpathConcatenation',
            },
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
        {
          // The asymmetry itself, pinned: a predicate step with no `//`.
          // Caught by the concatenation handler all along; the template
          // handler used to be blind to it.
          code: 'const xpath = `/root/node[${req.query.id}]`; doc.evaluate(xpath);',
          errors: [
            {
              messageId: 'unsafeXpathConcatenation',
            },
          ],
        },
        {
          code: `
            // Dangerous XPath allowing parent traversal
            const userPath = userInput; // Could be "../admin/password"
            const xpath = \`/app/users/user[\${userPath}]\`;
            const result = document.evaluate(xpath, document);
          `,
          // A location step carrying a predicate is XPath whether or not the
          // expression also contains `//`. This fixture used to assert one
          // error, which encoded the gap as expected behaviour: the template
          // handler required `//` while the concatenation handler did not, so
          // the same string was injection to one path and invisible to the
          // other. Both now use XPATH_SYNTAX.
          errors: [
            {
              messageId: 'unsafeXpathConcatenation',
            },
          ],
        },
      ],
    });
  });

  describe('Advanced XPath Coverage', () => {
    ruleTester.run(
      'coverage - function parameters and direct calls',
      noXpathInjection,
      {
        valid: [
          // Helper function with safe annotation
          {
            options: [{ reportDangerousConstructs: true }],
            code: `
            /** @xpath-safe */
            function safeQuery() {
              const xpath = "//user"; 
              // Rule checks statement level too for some visitors, but usually annotation is on the statement using it
            }
          `,
          },
        ],
        invalid: [
          // Direct function call (not method) - Invalid because // is dangerous pattern
          {
            // The import is what makes a BARE `select(...)` an XPath evaluator.
            // Without it the identifier carries only its spelling, and `select`
            // is also NgRx's store operator — `store.pipe(select(selectUser))`
            // reported CWE-643 at CVSS 9.8 in files with no XML in them.
            code: 'import { select } from "xpath"; select("//user")',
            options: [{ xpathFunctions: ['select'], reportDangerousConstructs: true }],
            errors: [{ messageId: 'dangerousXpathExpression' }],
          },
          // Function parameter as input
          {
            code: `
            function find(userInput) {
              document.evaluate("//user[@name='" + userInput + "']", document);
            }
          `,
            errors: [{ messageId: 'xpathInjection' }],
          },
          // req object usage directly
          {
            code: 'document.evaluate("//user[@id=" + req.id + "]", document);',
            errors: [{ messageId: 'xpathInjection' }],
          },
          // Direct function call with dangerous input
          {
            code: 'selectNodes("//user[@name=" + userInput + "]")',
            options: [{ xpathFunctions: ['selectNodes'] }],
            errors: [{ messageId: 'xpathInjection' }],
          },
        ],
      },
    );

    ruleTester.run('coverage - validation and construction', noXpathInjection, {
      valid: [
        // Variable assigned verified safe construction
        {
          code: `
            const safePath = buildXPath('user', {});
            document.evaluate(safePath, document);
          `,
          options: [{ safeXpathConstructors: ['buildXPath'] }],
        },
        // Validation function wrapper
        {
          code: `
            const query = escapeXPath(userInput);
            document.evaluate("//user[@id='" + query + "']", document);
          `,
          options: [{ xpathValidationFunctions: ['escapeXPath'] }],
        },
        // Annotated statement
        {
          options: [{ reportDangerousConstructs: true }],
          code: `
            /** @xpath-safe */
            const xpath = "//user[@name='" + userInput + "']";
            document.evaluate(xpath, document);
          `,
        },
      ],
      invalid: [
        // Validation function not in options
        {
          code: `
            const query = myEscape(userInput);
            document.evaluate("//user[@id='" + query + "']", document);
          `,
          errors: [{ messageId: 'xpathInjection' }],
        },
      ],
    });
  });

  // Layer 1 — coverage gap fixtures
  describe('Coverage - branch gaps', () => {
    ruleTester.run('coverage gaps - valid', noXpathInjection, {
      valid: [
        // id 15: non-req MemberExpression init → isUntrustedXpathInput second-inner-if false arm
        { code: 'const xpathQuery = foo.bar;' },
        // id 22: isXpathInputValidated true arm — validation function wraps the template
        { code: 'validateXPath(`/users/user[@id="${userInput}"]`)' },
        // id 31: XPath call with zero args → early return
        { options: [{ reportDangerousConstructs: true }],
          code: 'document.evaluate()' },
        // id 35: dangerous literal XPath but @xpath-safe annotation
        {
          options: [{ reportDangerousConstructs: true }],
          code: `/** @xpath-safe */
document.evaluate("//users/..", document);`,
        },
        // id 42: untrusted identifier XPath but @xpath-safe annotation
        {
          options: [{ reportDangerousConstructs: true }],
          code: `/** @xpath-safe */
document.evaluate(userQuery, document);`,
        },
        // id 45: URL template literal → skip early return
        { code: 'const t = `https://example.com/page`' },
        // id 47: file-path template literal → skip early return
        { code: 'const t = `/home/user/file`' },
        // id 49: CSS selector template literal → skip early return
        { code: 'const t = `[data-id="foo"]`' },
        // id 51+52: query-string template literal → skip early return
        { options: [{ reportDangerousConstructs: true }],
          code: 'const t = `?id=123`' },
        // id 62 true arm: dangerous XPath template but @xpath-safe annotation
        {
          options: [{ reportDangerousConstructs: true }],
          code: `/** @xpath-safe */
const xpath = \`//users/..\``,
        },
        // id 65+66: BinaryExpression with no '/' or '[' → early return
        { code: 'const r = "hello" + userInput' },
        // id 78: VariableDeclarator with no init → early return
        { code: 'let xpathQuery;' },
      ],
      invalid: [
        // id 11 arm 1: containsXpathInterpolation second arm ('..+..' pattern)
        {
          options: [{ reportDangerousConstructs: true }],
          code: "const xpath = `//node[@id='a+b']`; document.evaluate(xpath, doc);",
          errors: [{ messageId: 'dangerousXpathExpression' }],
        },
        // id 11 arm 2: containsXpathInterpolation third arm ("..+.." pattern)
        {
          code: 'const xpath = `//node[@id="a+b"]`; document.evaluate(xpath, doc);',
          // `dangerousXpathExpression` is opt-in: these are CONSTANT XPath
          // strings, and `//` is the descendant axis, present in essentially
          // every XPath. Reporting them at CVSS 9.8 by default is what made
          // this rule fire on correct code.
          options: [{ reportDangerousConstructs: true }],
          errors: [{ messageId: 'dangerousXpathExpression' }],
        },
        // id 55 false arm + id 62 false arm: no interpolation, dangerous XPath template
        {
          code: 'const xpath = `//users/..`; document.evaluate(xpath, doc);',
          // `dangerousXpathExpression` is opt-in: these are CONSTANT XPath
          // strings, and `//` is the descendant axis, present in essentially
          // every XPath. Reporting them at CVSS 9.8 by default is what made
          // this rule fire on correct code.
          options: [{ reportDangerousConstructs: true }],
          errors: [{ messageId: 'dangerousXpathExpression' }],
        },
        // isXpathSinkCall via a bare Identifier callee.
        {
          // Import-gated, as above: a bare callee needs module evidence.
          code: 'import { select } from "xpath"; select(`//users/..`);',
          // `dangerousXpathExpression` is opt-in: these are CONSTANT XPath
          // strings, and `//` is the descendant axis, present in essentially
          // every XPath. Reporting them at CVSS 9.8 by default is what made
          // this rule fire on correct code.
          options: [{ reportDangerousConstructs: true }],
          errors: [{ messageId: 'dangerousXpathExpression' }],
        },
        // reachesXpathSink walks out through a concatenation.
        // Two DISTINCT findings, not a duplicate: `xpathInjection` says a dynamic value
        // reaches an evaluator, `dangerousXpathExpression` says the literal carries
        // parent-axis traversal. Different information, different fixes.
        {
          code: 'document.evaluate(`//users/..` + suffix, doc);',
          errors: [
            { messageId: 'xpathInjection' },
          ],
        },
        // Moved from `valid` (was "id 21: destructured param"). A destructured parameter
        // concatenated into an XPath string and handed to `document.evaluate` IS injection.
        // It was only "valid" because `id` is not in the taint-NAME list.
        {
          code: 'function f({id}) { document.evaluate("//user[@name=" + id + "]", document); }',
          errors: 1,
        },
        // id 69+70: leftUntrusted = true (untrusted identifier on left of +)
        {
          code: 'const r = userInput + "//users/.."',
          errors: [{ messageId: 'xpathInjection' }],
        },
      ],
    });
  });

  // Layer 2 — mock context for node.loc?.start.line ?? 0 fallback
  describe('Layer 2 - mock context', () => {
    it('CallExpression dangerousXpathExpression falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        // `dangerousXpathExpression` is opt-in now — a CONSTANT XPath containing
        // `//` is ordinary syntax, not a vulnerability. These tests exercise the
        // loc-fallback inside that report path, so they must enable it.
        options: [{ reportDangerousConstructs: true }],
      });
      const callExpression = listeners.CallExpression as (n: unknown) => void;

      callExpression({
        type: 'CallExpression',
        // A MEMBER callee: a bare `evaluate(...)` now needs a resolvable import
        // to count as an XPath evaluator, which a synthetic node has no scope
        // to provide. The report path under test is the same.
        callee: {
          type: 'MemberExpression',
          object: { type: 'Identifier', name: 'doc' },
          property: { type: 'Identifier', name: 'evaluate' },
        },
        arguments: [{ type: 'Literal', value: '//users/..' }],
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('CallExpression unvalidatedXpathInput falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection);
      const callExpression = listeners.CallExpression as (n: unknown) => void;

      callExpression({
        type: 'CallExpression',
        // Member callee, same reason as above.
        callee: {
          type: 'MemberExpression',
          object: { type: 'Identifier', name: 'doc' },
          property: { type: 'Identifier', name: 'evaluate' },
        },
        arguments: [
          { type: 'Identifier', name: 'userInput', parent: undefined },
        ],
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('TemplateLiteral unsafeXpathConcatenation falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: '`/users/user[@id="${userInput}"]`',
      });
      const templateLiteral = listeners.TemplateLiteral as (n: unknown) => void;

      // The static text lives in the quasis, not in the printed source — the
      // handler reads the AST, so the mock has to carry it there.
      templateLiteral({
        type: 'TemplateLiteral',
        parent: undefined,
        expressions: [
          { type: 'Identifier', name: 'userInput', parent: undefined },
        ],
        quasis: [
          { type: 'TemplateElement', value: { raw: '/users/user[@id="' } },
          { type: 'TemplateElement', value: { raw: '"]' } },
        ],
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('TemplateLiteral dangerousXpathExpression falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: '`//users/..`',
        // Opt-in: a constant XPath containing `//` is ordinary syntax. This
        // test covers the loc-fallback inside that report path, so it enables
        // the path explicitly.
        options: [{ reportDangerousConstructs: true }],
      });
      const templateLiteral = listeners.TemplateLiteral as (n: unknown) => void;

      // The report now requires the string to reach an XPath evaluator, so
      // the node needs a sink parent to get as far as the line-0 fallback
      // this test exists to cover.
      const node: Record<string, unknown> = {
        type: 'TemplateLiteral',
        expressions: [],
        quasis: [{ type: 'TemplateElement', value: { raw: '//users/..' } }],
      };
      node.parent = {
        type: 'CallExpression',
        callee: {
          type: 'MemberExpression',
          property: { type: 'Identifier', name: 'evaluate' },
        },
        arguments: [node],
      };
      templateLiteral(node);

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('TemplateLiteral with no parent reaches no sink and is not reported', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: '`//users/..`',
        // Opt-in: a constant XPath containing `//` is ordinary syntax. This
        // test covers the loc-fallback inside that report path, so it enables
        // the path explicitly.
        options: [{ reportDangerousConstructs: true }],
      });
      const templateLiteral = listeners.TemplateLiteral as (n: unknown) => void;

      templateLiteral({
        type: 'TemplateLiteral',
        parent: undefined,
        expressions: [],
        quasis: [{ type: 'TemplateElement', value: { raw: '//users/..' } }],
      });

      expect(reports).toHaveLength(0);
    });

    it('TemplateLiteral declared but unresolvable in scope is not reported', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: '`//users/..`',
        // Opt-in: a constant XPath containing `//` is ordinary syntax. This
        // test covers the loc-fallback inside that report path, so it enables
        // the path explicitly.
        options: [{ reportDangerousConstructs: true }],
      });
      const templateLiteral = listeners.TemplateLiteral as (n: unknown) => void;

      // The mock's getScope returns an empty scope, so the declared name
      // resolves to nothing — the `?? []` arm of the reference lookup.
      templateLiteral({
        type: 'TemplateLiteral',
        parent: {
          type: 'VariableDeclarator',
          id: { type: 'Identifier', name: 'q' },
        },
        expressions: [],
        quasis: [{ type: 'TemplateElement', value: { raw: '//users/..' } }],
      });

      expect(reports).toHaveLength(0);
    });

    it('BinaryExpression xpathInjection falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: 'userInput + "//users/.."',
      });
      const binaryExpression = listeners.BinaryExpression as (
        n: unknown,
      ) => void;

      binaryExpression({
        type: 'BinaryExpression',
        operator: '+',
        left: { type: 'Identifier', name: 'userInput', parent: undefined },
        right: { type: 'Literal', value: '//users/..' },
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('VariableDeclarator dangerousXpathExpression falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        // `dangerousXpathExpression` is opt-in now — a CONSTANT XPath containing
        // `//` is ordinary syntax, not a vulnerability. These tests exercise the
        // loc-fallback inside that report path, so they must enable it.
        options: [{ reportDangerousConstructs: true }],
      });
      const variableDeclarator = listeners.VariableDeclarator as (
        n: unknown,
      ) => void;

      variableDeclarator({
        type: 'VariableDeclarator',
        id: { type: 'Identifier', name: 'xpathQuery' },
        init: { type: 'Literal', value: '//users/..' },
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('VariableDeclarator declaration path stays silent without a sink', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection);
      const variableDeclarator = listeners.VariableDeclarator as (
        n: unknown,
      ) => void;

      variableDeclarator({
        type: 'VariableDeclarator',
        id: { type: 'Identifier', name: 'xpathQuery' },
        init: { type: 'Identifier', name: 'userInput', parent: undefined },
      });

      // The declaration path now requires the declared variable to reach an evaluator, so a
      // bare identifier-to-identifier mock reports nothing. That name-only branch is exactly
      // what reported `const QueryValidateSchema = QueryInputSchema` as CWE-643 on real
      // source. The loc fallback it used to cover is now hoisted and shared with the literal
      // branch, which the mock above exercises.
      expect(reports).toHaveLength(0);
    });
  });
});

/**
 * Wild-corpus sweep (8 repos of published SDK/CLI code): 9 findings, 0 real.
 * None of the eight repositories contains an XPath API.
 *
 * Two defects, both "shape is not meaning":
 *
 *  - `//` is the XPath descendant axis AND the separator in every URI. 7 of
 *    the 9 findings were the `//` in `gid://…`, `https://…` or a URL built
 *    from `req.protocol + '://' + host`.
 *  - `..` is the XPath parent axis AND every relative filesystem path, and
 *    `::` is the XPath axis separator AND a dozen unrelated conventions.
 */
describe('corpus regression — URIs, cache keys and file paths are not XPath', () => {
  ruleTester.run('wild corpus', noXpathInjection, {
    valid: [
      // Shopify CLI packages/cli-kit/.../bulk-operations/helpers.ts:21 (×4)
      // and app-management-client.ts:1235.
      {
        name: 'a GID template is not a descendant axis',
        code: 'function gid(id) { return `gid://shopify/BulkOperation/${id}`; }',
      },
      {
        name: 'a GID template passed to a helper',
        code: 'function gid(id) { return encodeGid(`gid://organization/ShopifyShop/${id}`); }',
      },
      // okta-auth-js samples/.../web-server/routes/login.js:63 (×2) — the
      // scheme is an interpolation, so the literal text is a bare `://`.
      {
        name: 'a URL assembled from req.protocol',
        code: `const parsedUrl = new URL(req.protocol + '://' + req.get('host') + req.originalUrl);`,
      },
      {
        name: 'a URL template with a dynamic scheme',
        code: 'function u(req) { return `${req.protocol}://${req.get("host")}${req.originalUrl}`; }',
      },
      // Shopify CLI .../validation/app_config_webhook.ts:55 — a cache key.
      {
        name: 'a double-colon cache key is not an axis',
        code: 'function k(topic, uri, filter) { return `${topic}::${uri}::${filter}`; }',
      },
      // okta-auth-js samples/gulpfile.js:37 — a relative require path whose
      // variable name happens to contain "path".
      {
        name: 'a relative file path is not a parent axis',
        code: `const OKTA_ENV_SCRIPT_PATH = '../env/index.js';`,
      },
      { name: 'a relative path in a query-named variable', code: `const queryPath = '../../lib';` },
    ],
    invalid: [
      // Real XPath must still report — if any of these go quiet the narrowing
      // above has become a false negative.
      {
        name: 'descendant axis with an interpolation',
        code: 'function f(userInput) { return `//user[@id="${userInput}"]`; }',
        errors: [{ messageId: 'unsafeXpathConcatenation' }],
      },
      {
        name: 'a named axis is still an axis',
        code: 'function f(userInput) { return `/root/child::user[@id="${userInput}"]`; }',
        errors: [{ messageId: 'unsafeXpathConcatenation' }],
      },
      {
        name: 'ancestor-or-self is an axis',
        code: 'function f(userInput) { return `ancestor-or-self::user[${userInput}]`; }',
        errors: [{ messageId: 'unsafeXpathConcatenation' }],
      },
      {
        name: 'concatenated XPath predicate',
        code: `const xpath = "/users/user[name='" + userInput + "']";`,
        errors: [{ messageId: 'xpathInjection' }],
      },
      {
        name: 'a parent axis inside a real XPath literal still reports',
        options: [{ reportDangerousConstructs: true }],
        code: `const xpathQuery = "//users/user/..";`,
        errors: [{ messageId: 'dangerousXpathExpression' }],
      },
    ],
  });
});

/**
 * Regression lock — evidence, not names. Both defects found by hand-reading real findings
 * across 20 open-source projects.
 *
 * FALSE POSITIVE: two name matchers stacked. The declaration name had to contain
 * xpath/query/path and the initialiser's name had to contain query/params/input/user/search,
 * so `const QueryValidateSchema = QueryInputSchema` — a Zod schema, in a file that has never
 * seen XPath — was reported as CWE-643. Neither name says the value is an XPath expression.
 *
 * FALSE NEGATIVE: `xpath.select("//user[@id='" + id + "']", doc)` was silent because `id` is
 * not in the taint-NAME list — while the string looksLikeXpath, the sink is proven, and part
 * of the expression is dynamic. Three independent facts, and the rule wanted a fourth that
 * was only ever a name.
 */
ruleTester.run('lock: evidence, not names', noXpathInjection, {
  valid: [
    { code: 'export const QueryValidateSchema = QueryInputSchema;' },
    { code: 'const queryPath = userQuery;' },
    { code: 'const xpathQuery = req.params.query;' },
    // A lookalike string that never reaches an evaluator.
    { code: 'const p = "//u[@id=\'" + id + "\']";' },
  ],
  invalid: [
    { code: 'xpath.select("//user[@id=\'" + id + "\']", doc);', errors: 1 },
    { code: 'const xpathVar = userInput; document.evaluate(xpathVar, document);', errors: 1 },
    // Destructuring bails out of the declaration path, but the sink still recognises the
    // argument — locks the early return without pretending the code is safe.
    { code: 'const { xpathQuery } = opts; doc.evaluate(xpathQuery, doc);', errors: 1 },
  ],
});

/**
 * Regression lock — `select` needs an XPath receiver.
 *
 * `select` is xpath-npm's API and also Mongoose's projection method, Knex's column picker
 * and jQuery's. Matching it on the property name alone made `mq.select(projection)` and
 * `builder().select(field)` XPath sinks — the largest remaining false-positive shape for
 * this rule after the name-matching fix. `evaluate`, `selectSingleNode` and `selectNodes`
 * name nothing else in common use and stay unconditional.
 */
ruleTester.run('lock: the select sink needs an xpath receiver', noXpathInjection, {
  valid: [
    { code: 'mq.select(projection);' },
    { code: 'builder().select(field);' },
    { code: 'knex("users").select(col);' },
    // A member receiver that is not xpath-shaped.
    { code: 'db.query.select(userInput);' },
  ],
  invalid: [
    { code: 'xpath.select("//user[@id=\'" + id + "\']", doc);', errors: 1 },
    // Namespaced receiver: `lib.xpath.select(...)`.
    { code: 'lib.xpath.select("//user[@id=\'" + id + "\']", doc);', errors: 1 },
    { code: 'xml.selectNodes(userQuery);', errors: 1 },
  ],
});

/**
 * Regression lock — two false positives a reviewer found in the rule this branch set out
 * to fix, both confirmed by measurement before being believed.
 *
 * 1. `dynamicAtSink` tested `operand.type !== Literal` as a stand-in for "can change".
 *    They are not the same question — it is the same substitution this rule was
 *    criticised for making with NAMES. `const id = '42'` is provably constant and
 *    reported at a real sink.
 *
 * 2. `hasUntrusted` reported a concatenation with no evaluator anywhere in the file.
 *    Requiring a sink outright was too blunt: a bare `const q = "..." + userInput` with
 *    no use at all is unresolved provenance, not proven safety — the variable is almost
 *    certainly evaluated in another module. Silence now needs positive evidence that
 *    every use goes somewhere harmless.
 */
describe('no-xpath-injection: constants and destinations', () => {
  ruleTester.run('evidence on both halves', noXpathInjection, {
    valid: [
      // A provably constant operand cannot be steered, even at a genuine sink.
      { code: `const id = '42'; xpath.select("//user[@id='" + id + "']", doc);` },
      { code: `const ID = '42'; const q = "//user[@id='" + ID + "']"; xpath.select(q, doc);` },
      // Built from a request, then demonstrably handed somewhere harmless.
      { code: `const s = '//u[@id=' + req.params.id + ']'; console.log(s);` },
      { code: `const s = '//u[@id=' + req.params.id + ']'; res.send(s);` },
    ],
    invalid: [
      // Declared and never used: destination unknown, which is not safety.
      {
        code: `const q = "/users/user[name='" + userInput + "']";`,
        errors: [{ messageId: 'xpathInjection' }],
      },
      // Every use classified, and one of them is a sink.
      {
        code: `const q = "//u[@id='" + req.params.id + "']"; console.log(q); xpath.select(q, doc);`,
        errors: [{ messageId: 'xpathInjection' }],
      },
      // Inline at the sink.
      {
        code: `xpath.select("//user[@id='" + req.params.id + "']", doc);`,
        errors: [{ messageId: 'xpathInjection' }],
      },
      // A non-constant local at a sink is still dynamic — `userId` resolves to nothing.
      {
        code: `xpath.select("//user[@id='" + userId + "']", doc);`,
        errors: [{ messageId: 'xpathInjection' }],
      },
    ],
  });
});

/**
 * REGRESSION LOCK — a constant XPath is not a vulnerability.
 *
 * `containsDangerousXpath` swept for `//`, `text()`, `..` and `/*` in the
 * PRINTED text. Every one of those is ordinary XPath — `//` is the descendant
 * axis and appears in essentially every XPath ever written. Probed on the
 * shipped rule at `error` in `recommended`:
 *
 *   xpath.select("//users/user[@active=1]", doc)  ->  CWE-643, CVSS 9.8
 *
 * The rule's own header already stated the principle it was violating:
 * "A constant string has nothing to inject into."
 *
 * `xpathInjection`, which requires a dynamic expression, is untouched and still
 * reports — including through one variable hop. The valid case below FAILS on
 * the pre-fix rule.
 */
ruleTester.run('no-xpath-injection-constant-is-not-a-finding', noXpathInjection, {
  valid: [
    'xpath.select("//users/user[@active=1]", doc);',
    'const q = "//catalog/book/title/text()"; doc.evaluate(q);',
  ],
  invalid: [
    {
      code: 'xpath.select("//users/user[@name=" + req.query.n + "]", doc);',
      errors: [{ messageId: 'xpathInjection' }],
    },
    {
      // Through one binding hop — the shape a real handler writes.
      code: 'function q(req) { const x = "//user[name=" + req.query.n + "]"; doc.evaluate(x); }',
      errors: [{ messageId: 'xpathInjection' }],
    },
    {
      // The old behaviour, restored explicitly by a consumer who wants it.
      code: 'xpath.select("//users/user[@active=1]", doc);',
      options: [{ reportDangerousConstructs: true }],
      errors: [{ messageId: 'dangerousXpathExpression' }],
    },
  ],
});

/**
 * Coverage for `reachesXpathSink`'s final `return false`.
 *
 * Reached when a constant XPath string sits in a position that is neither a
 * sink argument, nor a declarator whose binding reaches a sink, nor a
 * concatenation/template to keep walking. It went uncovered once
 * `dangerousXpathExpression` became opt-in, because the fixtures that used to
 * reach it did so without ever enabling that path.
 */
ruleTester.run('no-xpath-injection-sink-walk-terminates', noXpathInjection, {
  valid: [
    {
      // Declared, never passed to an evaluator: nothing to reach.
      code: 'const q = "//users/user/.."; console.log(q);',
      options: [{ reportDangerousConstructs: true }],
    },
    {
      // In an object property — not a call argument, not a declarator init.
      code: 'const cfg = { selector: "//users/.." }; ship(cfg);',
      options: [{ reportDangerousConstructs: true }],
    },
    {
      // Returned directly: the walk hits a ReturnStatement, which is none of
      // the handled parent types, so `reachesXpathSink` falls through.
      code: 'function sel() { return `//users/..`; }',
      options: [{ reportDangerousConstructs: true }],
    },
    {
      // Declared then reassigned — the binding exists but no reference is a
      // sink argument.
      code: 'let q = `//users/..`; q = other; use(q);',
      options: [{ reportDangerousConstructs: true }],
    },
    {
      // Computed member callee: `isXpathSinkCall` cannot name it, so the
      // `callee.property.type === Identifier` arm falls to null. Covers the
      // last branch of that ternary.
      code: 'const q = "//users/.."; api["evaluate"](q);',
      options: [{ reportDangerousConstructs: true }],
    },
    {
      // Computed callee taking the constant DIRECTLY, so isXpathSinkCall is
      // reached with a MemberExpression whose property is not an Identifier.
      code: 'api["evaluate"]("//users/..");',
      options: [{ reportDangerousConstructs: true }],
    },
    {
      // Callee that is neither Identifier nor MemberExpression at all.
      code: '(getEvaluator())("//users/..");',
      options: [{ reportDangerousConstructs: true }],
    },
  ],
  invalid: [],
});

/**
 * Option coverage — `trustedSanitizers`, `trustedAnnotations`, `strictMode`.
 *
 * Every block below is a PAIR over one unchanged snippet: the `valid` entry
 * sets the option, the `invalid` entry runs the same source without it (or
 * with the option that overrides it), and the two verdicts disagree. A case
 * that sets an option and reaches the default verdict executes the line and
 * proves nothing — the option could be deleted from the rule and this file
 * would stay green.
 *
 * The made-up names are deliberate. `trustedSanitizers` extends
 * `SANITIZATION_FUNCTIONS` and membership is exact (`Set.has`), so `zzzWrap`
 * cannot match by any other route; `@zzz-reviewed` contains none of the
 * built-in `SAFE_ANNOTATIONS` as a substring, and the built-in check is a
 * substring match.
 */
ruleTester.run(
  'option: trustedSanitizers marks a variable validated',
  noXpathInjection,
  {
    valid: [
      {
        // The rule keeps its own `validatedVariables` set, filled from
        // `xpathValidationFunctions` and `trustedSanitizers`. Naming `zzzWrap`
        // puts `userQuery` in it, so the evaluator no longer sees the value as
        // unvalidated input.
        code: 'const userQuery = zzzWrap(req.params.id);\ndocument.evaluate(userQuery, doc);',
        options: [{ trustedSanitizers: ['zzzWrap'] }],
      },
    ],
    invalid: [
      {
        // Byte-identical source with the option withheld. `zzzWrap` is then an
        // unknown function, `userQuery` never enters `validatedVariables`, and
        // the evaluator reports — so the option is what changed the verdict,
        // not the code.
        code: 'const userQuery = zzzWrap(req.params.id);\ndocument.evaluate(userQuery, doc);',
        errors: [{ messageId: 'unvalidatedXpathInput' }],
      },
    ],
  },
);

ruleTester.run(
  'option: trustedAnnotations silences an untrusted evaluator argument',
  noXpathInjection,
  {
    valid: [
      {
        // `hasSafeAnnotation` walks the node and its ancestors up to the
        // enclosing function, so the comment before the call statement covers
        // the argument. `@zzz-reviewed` is only an annotation because the
        // option says so.
        code: '/* @zzz-reviewed by appsec */\ndocument.evaluate(searchQuery, doc);',
        options: [{ trustedAnnotations: ['@zzz-reviewed'] }],
      },
    ],
    invalid: [
      {
        // Same source, same comment, option withheld: the comment matches none
        // of the built-in annotations, so the argument is still unvalidated
        // input and the call reports.
        code: '/* @zzz-reviewed by appsec */\ndocument.evaluate(searchQuery, doc);',
        errors: [{ messageId: 'unvalidatedXpathInput' }],
      },
    ],
  },
);

/**
 * `strictMode` only reaches report sites guarded by `safetyChecker.isSafe`.
 *
 * The site chosen here — the concatenation path's `xpathInjection` report — is
 * one of those. It is NOT interchangeable with the two blocks above: the
 * `validatedVariables` set and the direct `hasSafeAnnotation` call at the
 * evaluator both bypass the safety checker entirely, so `strictMode: true`
 * leaves those two snippets quiet. Pairing strictMode against either of them
 * would have produced a test that passes whatever strictMode does.
 */
ruleTester.run(
  'option: strictMode overrides trustedSanitizers',
  noXpathInjection,
  {
    valid: [
      {
        // `zzzWrap` is dynamic and the string reaches an evaluator, so the
        // concatenation would report; the trusted sanitizer is the only thing
        // keeping it quiet.
        code: 'const q = "//user[@id=" + zzzWrap(id);\ndocument.evaluate(q, doc);',
        options: [{ trustedSanitizers: ['zzzWrap'] }],
      },
    ],
    invalid: [
      {
        // Same source, same sanitizer list, plus `strictMode`. The checker now
        // returns false unconditionally, so the suppression the previous case
        // relies on disappears and the finding comes back.
        code: 'const q = "//user[@id=" + zzzWrap(id);\ndocument.evaluate(q, doc);',
        options: [{ trustedSanitizers: ['zzzWrap'], strictMode: true }],
        errors: [{ messageId: 'xpathInjection' }],
      },
    ],
  },
);

/**
 * Regression locks — defects proved by
 * `benchmarks/rule-corpus/secure-coding__no-xpath-injection`.
 */
ruleTester.run('lock - corpus-proved defects', noXpathInjection, {
  valid: [
    // NgRx. `select` here is the store operator and the argument is a memoised
    // selector function. Reported at CVSS 9.8 in a file with no XML in it,
    // because `select` is on the sink-name list and `selectUserProfile`
    // contains `user`.
    {
      code: 'import { select } from "@ngrx/store"; export const vm$ = store.pipe(select(selectUserProfile));',
    },
    // Any feature-flag SDK. Same shape, different verb.
    {
      code: 'import { evaluate } from "../lib/flags"; export function canExport(userContext) { return evaluate(userContext).enabled; }',
    },
    // A protocol-relative URL. `//` is the descendant axis only when a node
    // test follows it in the same literal; here it is a host.
    {
      code: 'export function cdnHref(host, asset) { return "//" + host + "/assets/" + asset; }',
    },
  ],
  invalid: [
    // The same bare call, WITH the import that makes it an evaluator.
    {
      code: 'import { select } from "xpath"; export function f(doc, name) { return select("//user[@name=\'" + name + "\']", doc); }',
      errors: [{ messageId: 'xpathInjection' }],
    },
    // `select1` is the xpath package's other documented entry point. Its
    // absence from the sink list did not merely miss the call — it actively
    // SUPPRESSED the concatenation finding, because a value whose only use is a
    // non-sink is treated as proven-safe.
    {
      code: 'const xpath = require("xpath"); exports.byMail = function (mail, doc) { const expression = "//users/user[email/text()=\'" + mail + "\']"; return xpath.select1(expression, doc); };',
      errors: [{ messageId: 'xpathInjection' }],
    },
  ],
});

/**
 * The evaluator PACKAGE list is an option, and its default is exactly what
 * shipped.
 *
 * The list only decides a BARE call — `select(expr, doc)` — where the resolved
 * import is the whole of the evidence: as a member call the receiver
 * disambiguates, and a literal XPath expression carries its own syntax. So
 * every case here is a bare call on a dynamic expression, and each is paired
 * with the same code under `options: [{}]`.
 *
 * Probed both directions before it was written: `import { select } from "xpath"`
 * reports `unvalidatedXpathInput`; the identical call with the import changed to
 * `@ngrx/store` is QUIET. The import is the only thing that moves.
 */
ruleTester.run('options: xpathPackages is configurable, default unchanged', noXpathInjection, {
  valid: [
    // ---- replacing the list drops the built-in evidence -------------------
    // `xpath` audited off the list: the bare `select` has nothing left to make
    // it an evaluator, which is exactly the NgRx shape locked above.
    {
      code: 'import { select } from "xpath"; export function f(doc, name) { return select(name, doc); }',
      options: [{ xpathPackages: ['xpath.js'] }],
    },
    // Extending never removes: a package in neither list stays quiet.
    {
      code: 'import { select } from "@ngrx/store"; export function f(doc, name) { return select(name, doc); }',
      options: [{ additionalXpathPackages: ['@acme/xml'] }],
    },
  ],
  invalid: [

    // ---- the default is unchanged ----------------------------------------
    // Positive control for the replacing case above: with an EMPTY option bag
    // the same bare call still reports.
    {
      code: 'import { select } from "xpath"; export function f(doc, name) { return select(name, doc); }',
      options: [{}],
      errors: [{ messageId: 'unvalidatedXpathInput' }],
    },

    // ---- extending the list adds coverage ---------------------------------
    // A house wrapper that re-exports `xpath.select`. The sink is identical;
    // only the specifier differs, and npm can never enumerate it.
    {
      code: 'import { select } from "@acme/xml"; export function f(doc, name) { return select(name, doc); }',
      options: [{ additionalXpathPackages: ['@acme/xml'] }],
      errors: [{ messageId: 'unvalidatedXpathInput' }],
    },
    // Full replacement widens as well as narrows.
    {
      code: 'import { select } from "@acme/xml"; export function f(doc, name) { return select(name, doc); }',
      options: [{ xpathPackages: ['@acme/xml'] }],
      errors: [{ messageId: 'unvalidatedXpathInput' }],
    },
  ],
});
