/**
 * Comprehensive tests for no-xpath-injection rule
 * Security: CWE-643 (XPath Injection)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll, expect } from 'vitest';
import parser from '@typescript-eslint/parser';
import { createWithMockContext } from '@interlace/eslint-devkit';
import { noXpathInjection } from './index';

// Configure RuleTester for Vitest
RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

// Use Flat Config format (ESLint 9+)
const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
  },
});

describe('no-xpath-injection', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe XPath operations', noXpathInjection, {
      valid: [
        // Only args[0] of an evaluator is the XPath expression; a template
        // in the context-node position is not the query.
        {
          code: 'document.evaluate(expr, `//users/..`);',
        },
        // The safe-annotation escape hatch, now reached only when the string
        // does flow to an evaluator.
        {
          code: '/** @xpath-safe */\nconst q = `//users/..`;\ndocument.evaluate(q, doc);',
        },
        // reachesXpathSink: parent is neither a call, a declarator, nor a
        // concatenation — nothing to follow, so nothing to report.
        {
          code: 'const o = { q: `//users/..` };',
        },
        // reachesXpathSink: callee is neither Identifier nor MemberExpression.
        {
          code: 'const getEval = () => doc.evaluate; (getEval())(`//users/..`);',
        },
        // reachesXpathSink: declared, but never passed to an evaluator.
        {
          code: 'const q = `//users/..`; console.log(q);',
        },
        // Regression: strings that look like XPath but never reach an
        // evaluator. All three were reported on redis/ioredis, a package with
        // no XPath API at all — `//` or `..` anywhere in the text was the
        // entire evidence.
        {
          code: 'const banner = `// Generated by bin/generate-version.js. Do not edit.`;',
        },
        {
          code: 'const ca = `MIIDTzCCAjegAwIBAgIJAKSVpiDswLc//wMA0GCSqGSIb3DQEBBQUAMD4`;',
        },
        {
          code: 'const rel = `../lib/index.js`;',
        },
        // A slash is a path separator in every language. The old heuristic was
        // `includes('/') || includes('[')`, which matched every path join, URL
        // build and array index — this exact line reported CWE-643, measured on
        // the Interlace repo.
        `function rel(fullPath, baseDir) { return fullPath.replace(baseDir + '/', ''); }`,
        `function u(base, id) { return base + '/api/' + id; }`,
        `function k(arr, i) { return 'items[' + i + ']'; }`,
        // Detection reads the AST, not printed source. An identifier that merely
        // spells an XPath function, and a comment inside the expression, are not
        // string content — both matched while the gate regexed
        // `sourceCode.getText(node)`.
        `function f(req) { const s = render.text() + req.query.q; use(s); }`,
        `function f(req) { const s = base /* //user[@id] */ + req.query.q; use(s); }`,
        // A non-string literal contributes no text.
        `function f(req) { const s = '/total: ' + 42 + req.query.n; use(s); }`,
        // Safe XPath literals
        {
          code: 'const result = document.evaluate("/users/user[@id=\'123\']", document);',
        },
        // Validated input
        {
          code: 'const safeId = validateId(userInput); const xpath = `/users/user[@id="${safeId}"]`;',
        },
        // Safe XPath construction
        {
          code: 'const xpath = buildXPath("users", { id: "123" });',
        },
        // Non-XPath operations
        {
          code: 'const result = array.find(item => item.id === userInput);',
        },
        // Escaped input
        {
          code: 'const xpath = `/users/user[@name="${escapeXPath(userName)}"]`;',
        },
      ],
      invalid: [
        {
          // Template quasis are string content too — same expression, backticks.
          code: "function q(req) { const x = `//user[name='` + req.query.n + `']`; doc.evaluate(x); }",
          errors: 2,
        },
      ],
    });
  });

  describe('Invalid Code - XPath Injection', () => {
    ruleTester.run(
      'invalid - XPath injection vulnerabilities',
      noXpathInjection,
      {
        valid: [],
        invalid: [
          {
            code: 'const xpath = "/users/user[name=\'" + userInput + "\']";',
            errors: [
              {
                messageId: 'xpathInjection',
              },
            ],
          },
          {
            code: 'const query = `/users/user[@id="${userId}"]`;',
            errors: [
              {
                messageId: 'unsafeXpathConcatenation',
              },
            ],
          },
          {
            code: 'document.evaluate(userQuery, document);',
            errors: [
              {
                messageId: 'unvalidatedXpathInput',
              },
            ],
          },
        ],
      },
    );
  });

  describe('Invalid Code - Dangerous XPath Patterns', () => {
    ruleTester.run('invalid - dangerous XPath expressions', noXpathInjection, {
      valid: [],
      invalid: [
        {
          code: 'const xpath = "//users/user/..";',
          errors: [
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
        {
          code: 'const query = "/root/*";',
          errors: [
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
        {
          code: 'const xpathWithWildcard = "//user[*]";',
          errors: [
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
      ],
    });
  });

  describe('Invalid Code - Unvalidated XPath Input', () => {
    ruleTester.run('invalid - unvalidated XPath input', noXpathInjection, {
      valid: [],
      invalid: [
        {
          code: 'xmlDoc.selectNodes(userSearchQuery);',
          errors: [
            {
              messageId: 'unvalidatedXpathInput',
            },
          ],
        },
        {
          code: 'const xpathVar = userInput; document.evaluate(xpathVar, document);',
          errors: [
            {
              messageId: 'xpathInjection',
            },
          ],
        },
      ],
    });
  });

  describe('Invalid Code - XPath Variable Assignment', () => {
    ruleTester.run(
      'invalid - dangerous XPath variable assignments',
      noXpathInjection,
      {
        valid: [],
        invalid: [
          {
            code: 'const userXPath = "//users/user/..";',
            errors: [
              {
                messageId: 'dangerousXpathExpression',
              },
            ],
          },
          {
            code: 'const xpathQuery = req.params.query;',
            errors: [
              {
                messageId: 'xpathInjection',
              },
            ],
          },
          {
            code: 'let searchPath = userInput;',
            errors: [
              {
                messageId: 'xpathInjection',
              },
            ],
          },
        ],
      },
    );
  });

  describe('Valid Code - False Positives Reduced', () => {
    ruleTester.run('valid - false positives reduced', noXpathInjection, {
      valid: [
        // Safe annotations
        {
          code: `
            /** @xpath-safe */
            const xpath = \`//user[@id="\${userId}"]\`;
          `,
        },
        // Validated inputs
        {
          code: `
            const cleanId = validateXPathInput(userId);
            const xpath = \`/users/user[@id="\${cleanId}"]\`;
          `,
        },
        // Sanitized inputs
        {
          code: `
            const safeQuery = sanitizeXPath(req.query.search);
            document.evaluate(safeQuery, document);
          `,
        },
        // Safe XPath construction
        {
          code: `
            const xpath = createXPath('users', 'user', { id: userId });
            document.evaluate(xpath, document);
          `,
        },
        // Internal XPath queries
        {
          code: 'const configPath = "/config/database";',
        },
      ],
      invalid: [],
    });
  });

  describe('Configuration Options', () => {
    ruleTester.run('config - custom XPath functions', noXpathInjection, {
      valid: [
        {
          code: 'myXpathLib.evaluate(query, doc);',
          options: [{ xpathFunctions: ['myXpathLib.evaluate'] }],
        },
      ],
      invalid: [],
    });

    ruleTester.run('config - custom safe constructors', noXpathInjection, {
      valid: [
        {
          code: 'const xpath = mySafeBuilder("users", userId);',
          options: [{ safeXpathConstructors: ['mySafeBuilder'] }],
        },
        {
          code: 'const xpath = unsafeBuilder(userId);',
          options: [{ safeXpathConstructors: ['mySafeBuilder'] }],
        },
      ],
      invalid: [],
    });
  });

  describe('Complex XPath Injection Scenarios', () => {
    ruleTester.run('complex - real-world XPath patterns', noXpathInjection, {
      valid: [],
      invalid: [
        {
          code: `
            function searchUsers(searchTerm) {
              // DANGEROUS: Direct interpolation
              const xpath = \`//user[contains(name, "\${searchTerm}")]\`;
              return document.evaluate(xpath, xmlDoc);
            }
          `,
          errors: [
            {
              messageId: 'unsafeXpathConcatenation',
            },
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
        {
          code: `
            const express = require('express');
            const app = express();

            app.get('/search', (req, res) => {
              // DANGEROUS: User input directly in XPath
              const userQuery = req.query.q;
              const xpath = "/users/user[name='" + userQuery + "']";
              const result = xmlDoc.selectSingleNode(xpath);
              res.json(result);
            });
          `,
          errors: [
            {
              messageId: 'xpathInjection',
            },
            {
              messageId: 'xpathInjection',
            },
          ],
        },
        {
          code: `
            // XPath injection with attribute traversal
            const maliciousQuery = req.params.id; // Could be "../../../etc/passwd"
            const xpath = \`//user[@id='\${maliciousQuery}']\`;
            const node = xml.evaluate(xpath, xmlDoc);
          `,
          errors: [
            {
              messageId: 'xpathInjection',
            },
            {
              messageId: 'unsafeXpathConcatenation',
            },
            {
              messageId: 'dangerousXpathExpression',
            },
          ],
        },
        {
          // The asymmetry itself, pinned: a predicate step with no `//`.
          // Caught by the concatenation handler all along; the template
          // handler used to be blind to it.
          code: 'const xpath = `/root/node[${req.query.id}]`; doc.evaluate(xpath);',
          errors: [
            {
              messageId: 'unsafeXpathConcatenation',
            },
          ],
        },
        {
          code: `
            // Dangerous XPath allowing parent traversal
            const userPath = userInput; // Could be "../admin/password"
            const xpath = \`/app/users/user[\${userPath}]\`;
            const result = document.evaluate(xpath, document);
          `,
          // A location step carrying a predicate is XPath whether or not the
          // expression also contains `//`. This fixture used to assert one
          // error, which encoded the gap as expected behaviour: the template
          // handler required `//` while the concatenation handler did not, so
          // the same string was injection to one path and invisible to the
          // other. Both now use XPATH_SYNTAX.
          errors: [
            {
              messageId: 'xpathInjection',
            },
            {
              messageId: 'unsafeXpathConcatenation',
            },
          ],
        },
      ],
    });
  });

  describe('Advanced XPath Coverage', () => {
    ruleTester.run(
      'coverage - function parameters and direct calls',
      noXpathInjection,
      {
        valid: [
          // Helper function with safe annotation
          {
            code: `
            /** @xpath-safe */
            function safeQuery() {
              const xpath = "//user"; 
              // Rule checks statement level too for some visitors, but usually annotation is on the statement using it
            }
          `,
          },
        ],
        invalid: [
          // Direct function call (not method) - Invalid because // is dangerous pattern
          {
            code: 'select("//user")',
            options: [{ xpathFunctions: ['select'] }],
            errors: [{ messageId: 'dangerousXpathExpression' }],
          },
          // Function parameter as input
          {
            code: `
            function find(userInput) {
              document.evaluate("//user[@name='" + userInput + "']", document);
            }
          `,
            errors: [{ messageId: 'xpathInjection' }],
          },
          // req object usage directly
          {
            code: 'document.evaluate("//user[@id=" + req.id + "]", document);',
            errors: [{ messageId: 'xpathInjection' }],
          },
          // Direct function call with dangerous input
          {
            code: 'selectNodes("//user[@name=" + userInput + "]")',
            options: [{ xpathFunctions: ['selectNodes'] }],
            errors: [{ messageId: 'xpathInjection' }],
          },
        ],
      },
    );

    ruleTester.run('coverage - validation and construction', noXpathInjection, {
      valid: [
        // Variable assigned verified safe construction
        {
          code: `
            const safePath = buildXPath('user', {});
            document.evaluate(safePath, document);
          `,
          options: [{ safeXpathConstructors: ['buildXPath'] }],
        },
        // Validation function wrapper
        {
          code: `
            const query = escapeXPath(userInput);
            document.evaluate("//user[@id='" + query + "']", document);
          `,
          options: [{ xpathValidationFunctions: ['escapeXPath'] }],
        },
        // Annotated statement
        {
          code: `
            /** @xpath-safe */
            const xpath = "//user[@name='" + userInput + "']";
            document.evaluate(xpath, document);
          `,
        },
      ],
      invalid: [
        // Validation function not in options
        {
          code: `
            const query = myEscape(userInput);
            document.evaluate("//user[@id='" + query + "']", document);
          `,
          errors: [{ messageId: 'xpathInjection' }],
        },
      ],
    });
  });

  // Layer 1 — coverage gap fixtures
  describe('Coverage - branch gaps', () => {
    ruleTester.run('coverage gaps - valid', noXpathInjection, {
      valid: [
        // id 15: non-req MemberExpression init → isUntrustedXpathInput second-inner-if false arm
        { code: 'const xpathQuery = foo.bar;' },
        // id 21: destructured param → param.type !== Identifier → false arm
        {
          code: 'function f({id}) { document.evaluate("//user[@name=" + id + "]", document); }',
        },
        // id 22: isXpathInputValidated true arm — validation function wraps the template
        { code: 'validateXPath(`/users/user[@id="${userInput}"]`)' },
        // id 31: XPath call with zero args → early return
        { code: 'document.evaluate()' },
        // id 35: dangerous literal XPath but @xpath-safe annotation
        {
          code: `/** @xpath-safe */
document.evaluate("//users/..", document);`,
        },
        // id 42: untrusted identifier XPath but @xpath-safe annotation
        {
          code: `/** @xpath-safe */
document.evaluate(userQuery, document);`,
        },
        // id 45: URL template literal → skip early return
        { code: 'const t = `https://example.com/page`' },
        // id 47: file-path template literal → skip early return
        { code: 'const t = `/home/user/file`' },
        // id 49: CSS selector template literal → skip early return
        { code: 'const t = `[data-id="foo"]`' },
        // id 51+52: query-string template literal → skip early return
        { code: 'const t = `?id=123`' },
        // id 62 true arm: dangerous XPath template but @xpath-safe annotation
        {
          code: `/** @xpath-safe */
const xpath = \`//users/..\``,
        },
        // id 65+66: BinaryExpression with no '/' or '[' → early return
        { code: 'const r = "hello" + userInput' },
        // id 78: VariableDeclarator with no init → early return
        { code: 'let xpathQuery;' },
      ],
      invalid: [
        // id 11 arm 1: containsXpathInterpolation second arm ('..+..' pattern)
        {
          code: "const xpath = `//node[@id='a+b']`; document.evaluate(xpath, doc);",
          errors: [{ messageId: 'dangerousXpathExpression' }],
        },
        // id 11 arm 2: containsXpathInterpolation third arm ("..+.." pattern)
        {
          code: 'const xpath = `//node[@id="a+b"]`; document.evaluate(xpath, doc);',
          errors: [{ messageId: 'dangerousXpathExpression' }],
        },
        // id 55 false arm + id 62 false arm: no interpolation, dangerous XPath template
        {
          code: 'const xpath = `//users/..`; document.evaluate(xpath, doc);',
          errors: [{ messageId: 'dangerousXpathExpression' }],
        },
        // isXpathSinkCall via a bare Identifier callee.
        {
          code: 'select(`//users/..`);',
          errors: [{ messageId: 'dangerousXpathExpression' }],
        },
        // reachesXpathSink walks out through a concatenation.
        {
          code: 'document.evaluate(`//users/..` + suffix, doc);',
          errors: [{ messageId: 'dangerousXpathExpression' }],
        },
        // id 69+70: leftUntrusted = true (untrusted identifier on left of +)
        {
          code: 'const r = userInput + "//users/.."',
          errors: [{ messageId: 'xpathInjection' }],
        },
      ],
    });
  });

  // Layer 2 — mock context for node.loc?.start.line ?? 0 fallback
  describe('Layer 2 - mock context', () => {
    it('CallExpression dangerousXpathExpression falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection);
      const callExpression = listeners.CallExpression as (n: unknown) => void;

      callExpression({
        type: 'CallExpression',
        callee: { type: 'Identifier', name: 'evaluate' },
        arguments: [{ type: 'Literal', value: '//users/..' }],
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('CallExpression unvalidatedXpathInput falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection);
      const callExpression = listeners.CallExpression as (n: unknown) => void;

      callExpression({
        type: 'CallExpression',
        callee: { type: 'Identifier', name: 'evaluate' },
        arguments: [
          { type: 'Identifier', name: 'userInput', parent: undefined },
        ],
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('TemplateLiteral unsafeXpathConcatenation falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: '`/users/user[@id="${userInput}"]`',
      });
      const templateLiteral = listeners.TemplateLiteral as (n: unknown) => void;

      // The static text lives in the quasis, not in the printed source — the
      // handler reads the AST, so the mock has to carry it there.
      templateLiteral({
        type: 'TemplateLiteral',
        parent: undefined,
        expressions: [
          { type: 'Identifier', name: 'userInput', parent: undefined },
        ],
        quasis: [
          { type: 'TemplateElement', value: { raw: '/users/user[@id="' } },
          { type: 'TemplateElement', value: { raw: '"]' } },
        ],
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('TemplateLiteral dangerousXpathExpression falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: '`//users/..`',
      });
      const templateLiteral = listeners.TemplateLiteral as (n: unknown) => void;

      // The report now requires the string to reach an XPath evaluator, so
      // the node needs a sink parent to get as far as the line-0 fallback
      // this test exists to cover.
      const node: Record<string, unknown> = {
        type: 'TemplateLiteral',
        expressions: [],
        quasis: [{ type: 'TemplateElement', value: { raw: '//users/..' } }],
      };
      node.parent = {
        type: 'CallExpression',
        callee: {
          type: 'MemberExpression',
          property: { type: 'Identifier', name: 'evaluate' },
        },
        arguments: [node],
      };
      templateLiteral(node);

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('TemplateLiteral with no parent reaches no sink and is not reported', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: '`//users/..`',
      });
      const templateLiteral = listeners.TemplateLiteral as (n: unknown) => void;

      templateLiteral({
        type: 'TemplateLiteral',
        parent: undefined,
        expressions: [],
        quasis: [{ type: 'TemplateElement', value: { raw: '//users/..' } }],
      });

      expect(reports).toHaveLength(0);
    });

    it('TemplateLiteral declared but unresolvable in scope is not reported', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: '`//users/..`',
      });
      const templateLiteral = listeners.TemplateLiteral as (n: unknown) => void;

      // The mock's getScope returns an empty scope, so the declared name
      // resolves to nothing — the `?? []` arm of the reference lookup.
      templateLiteral({
        type: 'TemplateLiteral',
        parent: {
          type: 'VariableDeclarator',
          id: { type: 'Identifier', name: 'q' },
        },
        expressions: [],
        quasis: [{ type: 'TemplateElement', value: { raw: '//users/..' } }],
      });

      expect(reports).toHaveLength(0);
    });

    it('BinaryExpression xpathInjection falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection, {
        sourceText: 'userInput + "//users/.."',
      });
      const binaryExpression = listeners.BinaryExpression as (
        n: unknown,
      ) => void;

      binaryExpression({
        type: 'BinaryExpression',
        operator: '+',
        left: { type: 'Identifier', name: 'userInput', parent: undefined },
        right: { type: 'Literal', value: '//users/..' },
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('VariableDeclarator dangerousXpathExpression falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection);
      const variableDeclarator = listeners.VariableDeclarator as (
        n: unknown,
      ) => void;

      variableDeclarator({
        type: 'VariableDeclarator',
        id: { type: 'Identifier', name: 'xpathQuery' },
        init: { type: 'Literal', value: '//users/..' },
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });

    it('VariableDeclarator xpathInjection falls back to line 0 when loc is missing', () => {
      const { listeners, reports } = createWithMockContext(noXpathInjection);
      const variableDeclarator = listeners.VariableDeclarator as (
        n: unknown,
      ) => void;

      variableDeclarator({
        type: 'VariableDeclarator',
        id: { type: 'Identifier', name: 'xpathQuery' },
        init: { type: 'Identifier', name: 'userInput', parent: undefined },
      });

      expect(reports).toHaveLength(1);
      expect(reports[0].data?.line).toBe('0');
    });
  });
});

/**
 * Wild-corpus sweep (8 repos of published SDK/CLI code): 9 findings, 0 real.
 * None of the eight repositories contains an XPath API.
 *
 * Two defects, both "shape is not meaning":
 *
 *  - `//` is the XPath descendant axis AND the separator in every URI. 7 of
 *    the 9 findings were the `//` in `gid://…`, `https://…` or a URL built
 *    from `req.protocol + '://' + host`.
 *  - `..` is the XPath parent axis AND every relative filesystem path, and
 *    `::` is the XPath axis separator AND a dozen unrelated conventions.
 */
describe('corpus regression — URIs, cache keys and file paths are not XPath', () => {
  ruleTester.run('wild corpus', noXpathInjection, {
    valid: [
      // Shopify CLI packages/cli-kit/.../bulk-operations/helpers.ts:21 (×4)
      // and app-management-client.ts:1235.
      {
        name: 'a GID template is not a descendant axis',
        code: 'function gid(id) { return `gid://shopify/BulkOperation/${id}`; }',
      },
      {
        name: 'a GID template passed to a helper',
        code: 'function gid(id) { return encodeGid(`gid://organization/ShopifyShop/${id}`); }',
      },
      // okta-auth-js samples/.../web-server/routes/login.js:63 (×2) — the
      // scheme is an interpolation, so the literal text is a bare `://`.
      {
        name: 'a URL assembled from req.protocol',
        code: `const parsedUrl = new URL(req.protocol + '://' + req.get('host') + req.originalUrl);`,
      },
      {
        name: 'a URL template with a dynamic scheme',
        code: 'function u(req) { return `${req.protocol}://${req.get("host")}${req.originalUrl}`; }',
      },
      // Shopify CLI .../validation/app_config_webhook.ts:55 — a cache key.
      {
        name: 'a double-colon cache key is not an axis',
        code: 'function k(topic, uri, filter) { return `${topic}::${uri}::${filter}`; }',
      },
      // okta-auth-js samples/gulpfile.js:37 — a relative require path whose
      // variable name happens to contain "path".
      {
        name: 'a relative file path is not a parent axis',
        code: `const OKTA_ENV_SCRIPT_PATH = '../env/index.js';`,
      },
      { name: 'a relative path in a query-named variable', code: `const queryPath = '../../lib';` },
    ],
    invalid: [
      // Real XPath must still report — if any of these go quiet the narrowing
      // above has become a false negative.
      {
        name: 'descendant axis with an interpolation',
        code: 'function f(userInput) { return `//user[@id="${userInput}"]`; }',
        errors: [{ messageId: 'unsafeXpathConcatenation' }],
      },
      {
        name: 'a named axis is still an axis',
        code: 'function f(userInput) { return `/root/child::user[@id="${userInput}"]`; }',
        errors: [{ messageId: 'unsafeXpathConcatenation' }],
      },
      {
        name: 'ancestor-or-self is an axis',
        code: 'function f(userInput) { return `ancestor-or-self::user[${userInput}]`; }',
        errors: [{ messageId: 'unsafeXpathConcatenation' }],
      },
      {
        name: 'concatenated XPath predicate',
        code: `const xpath = "/users/user[name='" + userInput + "']";`,
        errors: [{ messageId: 'xpathInjection' }],
      },
      {
        name: 'a parent axis inside a real XPath literal still reports',
        code: `const xpathQuery = "//users/user/..";`,
        errors: [{ messageId: 'dangerousXpathExpression' }],
      },
    ],
  });
});
