/**
 * report-format — shared markdown helpers for audit/bench reports posted
 * to PRs by .github/workflows/*.yml. Single source of truth for the
 * visual contract: status badges, GFM-native callouts, collapsibles,
 * mobile-readable tables. Pure string composition — no deps.
 *
 * Consumers: scripts/audit-api-surface.ts, scripts/audit-cve-rule-latency.ts,
 * scripts/check-per-rule-budget.ts (the three pilot reports).
 *
 * The format contract these helpers produce is locked by
 * apps/docs/src/__tests__/audit-reports-format-lock.test.ts. If you change
 * the shape of `reportHeader` or `howToRead`, update the lock test too.
 */

export type StatusLevel = 'pass' | 'fail' | 'warn' | 'stale' | 'info';

const BADGE_COLOR: Record<StatusLevel, string> = {
  pass: 'brightgreen',
  fail: 'red',
  warn: 'yellow',
  stale: 'lightgrey',
  info: 'blue',
};

/**
 * shields.io static-badge URL. Renders inline in GitHub PR comments, in
 * the Actions step-summary tab, and in VS Code's markdown preview — no
 * JS runtime required.
 *
 * We escape per shields.io conventions: '-' → '--', '_' → '__', ' ' → '_'.
 */
export function statusBadge(level: StatusLevel, label: string): string {
  const safe = encodeBadgeSegment(label);
  return `![${level}: ${label}](https://img.shields.io/badge/${safe}-${BADGE_COLOR[level]})`;
}

/**
 * Two-segment badge (`left-right-color`) for KV pills like
 * "as of-2026-05-13-lightgrey".
 */
export function kvBadge(left: string, right: string, color: StatusLevel = 'info'): string {
  return `![${left}: ${right}](https://img.shields.io/badge/${encodeBadgeSegment(left)}-${encodeBadgeSegment(right)}-${BADGE_COLOR[color]})`;
}

function encodeBadgeSegment(s: string): string {
  return encodeURIComponent(
    s.replace(/-/g, '--').replace(/_/g, '__').replace(/ /g, '_'),
  );
}

export interface ReportHeaderInput {
  /** H1 title — also becomes the sticky-comment marker. */
  title: string;
  /** Pass/fail/warn pill rendered first in the badge row. */
  status: StatusLevel;
  /** Status pill label (e.g. "passing", "10/10 plugins at floor"). */
  statusLabel: string;
  /** Plain-English one-line summary under the badge row. */
  headlineSentence: string;
  /** Headline metric for the right-most pill (optional). */
  headlineMetric?: { label: string; value: string };
  /** ISO date of the underlying data (e.g. "2026-05-13"). */
  asOf: string;
  /** Footer line: `npm run …`. */
  generatedBy: string;
  /** Footer line: source data file path. */
  sourceFile: string;
  /** Optional extra footer note (policy summary etc.). */
  extraMeta?: string;
}

/**
 * Render the canonical header block — H1 + shields.io badge row +
 * one-line headline sentence + blockquote meta footer. Every pilot
 * report starts with this; the format-lock test asserts the badge row
 * lives in the first 15 lines.
 */
export function reportHeader(input: ReportHeaderInput): string {
  const lines: string[] = [];
  lines.push(`# ${input.title}`);
  lines.push('');
  const badges = [statusBadge(input.status, input.statusLabel), kvBadge('as of', input.asOf, 'stale')];
  if (input.headlineMetric) {
    badges.push(kvBadge(input.headlineMetric.label, input.headlineMetric.value, 'info'));
  }
  lines.push(badges.join(' '));
  lines.push('');
  lines.push(input.headlineSentence);
  lines.push('');
  lines.push(`> Generated by \`${input.generatedBy}\` from \`${input.sourceFile}\` on ${input.asOf}.`);
  if (input.extraMeta) {
    lines.push(`> ${input.extraMeta}`);
  }
  lines.push('');
  return lines.join('\n');
}

export type CalloutKind = 'NOTE' | 'TIP' | 'IMPORTANT' | 'WARNING' | 'CAUTION';

/**
 * GFM-native callout block. Renders as a coloured banner on GitHub
 * (since 2023). Falls back to a plain blockquote everywhere else.
 */
export function callout(kind: CalloutKind, body: string): string {
  const bodyLines = body.split('\n').map((l) => (l.length > 0 ? `> ${l}` : '>'));
  return [`> [!${kind}]`, ...bodyLines, ''].join('\n');
}

/**
 * Collapsible `<details>` block. Used for verbose sections (per-plugin
 * notes, "How to read this") that otherwise drown the headline numbers.
 *
 * The empty lines around the inner body are required for GitHub to
 * render markdown inside the `<details>` — without them GitHub treats
 * the body as raw HTML and tables/code-fences break.
 */
export function collapsible(summary: string, body: string): string {
  return `<details>\n<summary>${summary}</summary>\n\n${body}\n\n</details>\n`;
}

export type ColumnAlign = 'left' | 'right' | 'center';

export interface TableInput {
  head: string[];
  rows: Array<Array<string | number | null | undefined>>;
  /** Per-column alignment. Omit a slot for `left`. Defaults to numeric heuristics. */
  align?: ColumnAlign[];
  /** Cells longer than this collapse with `…`. Default 120. */
  maxCellWidth?: number;
}

const NUMERIC_CELL_RE = /^-?[\d.,]+(ms|d|%|MB|GB|s|kb|KB|kB)?$/i;

/**
 * Auto-aligned markdown table with a mobile-readability guard.
 *
 * - Columns where every non-empty cell matches /^-?[\d.,]+(ms|%|…)?$/ are
 *   auto-right-aligned (overridable via `align`).
 * - Cells longer than `maxCellWidth` (default 120) are truncated with
 *   `…`. The 200-char-row format lock catches anything that still
 *   overflows a PR comment view.
 */
export function table(input: TableInput): string {
  const head = input.head;
  const maxWidth = input.maxCellWidth ?? 120;
  const rows = input.rows.map((row) =>
    row.map((cell) => {
      const s = cell === null || cell === undefined ? '—' : String(cell);
      if (s.length <= maxWidth) return s;
      return s.slice(0, maxWidth - 1) + '…';
    }),
  );

  const align: ColumnAlign[] = head.map((_, col) => {
    if (input.align?.[col]) return input.align[col];
    // Heuristic: numeric if every non-empty cell in this column is numeric-shaped.
    const nonEmpty = rows.map((r) => r[col]).filter((c) => c && c !== '—');
    if (nonEmpty.length > 0 && nonEmpty.every((c) => NUMERIC_CELL_RE.test(c))) {
      return 'right';
    }
    return 'left';
  });

  const sep = align.map((a) => {
    if (a === 'right') return '---:';
    if (a === 'center') return ':---:';
    return ':---';
  });

  const lines: string[] = [];
  lines.push(`| ${head.join(' | ')} |`);
  lines.push(`| ${sep.join(' | ')} |`);
  for (const row of rows) {
    lines.push(`| ${row.join(' | ')} |`);
  }
  return lines.join('\n');
}

/**
 * Headline KV summary — a two-column table for the 3–6 most important
 * numbers in a report. Rendered right under the header.
 */
export function kvSummary(rows: Array<{ key: string; value: string }>): string {
  const head = ['Metric', 'Value'];
  return table({ head, rows: rows.map((r) => [r.key, r.value]), align: ['left', 'right'] });
}

/**
 * The canonical trailing "How to read this" block — a `<details>`
 * collapsible so verbose methodology doesn't push the headline numbers
 * off-screen on PR comments.
 *
 * The format-lock test asserts every pilot report ends with exactly one
 * of these.
 */
export function howToRead(body: string): string {
  return collapsible('How to read this', body);
}
