/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * Rules whose remedy does not exist inside generated code do not report there.
 *
 * Each rule gets BOTH directions. The control — the same snippet without the
 * banner — is what makes the silence mean anything; without it a snippet that
 * simply fails to trigger the rule looks like a pass.
 *
 * The banner deliberately carries no `eslint-disable`. Real generated files
 * often open with one, and an earlier version of this fixture did too — which
 * silences every rule and made the test pass with the opt-out removed.
 */

import { describe, it, expect } from 'vitest';
import { Linter } from 'eslint';
import tsParser from '@typescript-eslint/parser';
import { identicalFunctions } from '../../packages/eslint-plugin-maintainability/src/rules/maintainability/identical-functions';
import { noMagicNumbers } from '../../packages/eslint-plugin-conventions/src/rules/conventions/no-magic-numbers';
import { noCommentedCode } from '../../packages/eslint-plugin-conventions/src/rules/conventions/no-commented-code';
import { preferTemplateLiteral } from '../../packages/eslint-plugin-modernization/src/rules/prefer-template-literal';

const BANNER = '// Code generated by openapi-generator. DO NOT EDIT.\n';

const CASES = [
  {
    // This one is NOT a devkit `skipGeneratedFiles` opt-out. The rule ships its
    // own `ignoreGeneratedFiles` option, defaulting to true, and adding the
    // devkit flag on top was redundant — reverted. The case stays because it
    // locks that default, which nothing else did: with the opt-out removed
    // this test still passed, which is how the redundancy surfaced.
    name: 'maintainability/identical-functions (own ignoreGeneratedFiles default)',
    rule: identicalFunctions,
    code: [
      'export function alpha(a: number, b: number) {',
      '  const total = a + b; const scaled = total * 2; return scaled - 1;',
      '}',
      'export function beta(a: number, b: number) {',
      '  const total = a + b; const scaled = total * 2; return scaled - 1;',
      '}',
    ].join('\n'),
  },
  {
    name: 'conventions/no-magic-numbers',
    rule: noMagicNumbers,
    // NOT `const delay = 86400` — assigning to a named const is the pattern
    // this rule ASKS for, so it reports nothing and the control fails. The
    // magic number has to be unnamed at the point of use.
    code: 'export function retry(n: number) {\n  return n > 86400 ? 86400 : n * 3600;\n}\n',
  },
  {
    name: 'conventions/no-commented-code',
    rule: noCommentedCode,
    code: '// const unused = compute(1, 2);\nexport const live = 1;\n',
  },
  {
    name: 'modernization/prefer-template-literal',
    rule: preferTemplateLiteral,
    code: 'export const greet = (n: string) => "hello " + n + "!";\n',
  },
] as const;

const lint = (rule: unknown, code: string): Linter.LintMessage[] => {
  const linter = new Linter({ configType: 'flat' });
  return linter.verify(
    code,
    [
      {
        files: ['**/*.ts'],
        languageOptions: { parser: tsParser as never, ecmaVersion: 2022, sourceType: 'module' },
        plugins: { probe: { rules: { target: rule as never } } },
        rules: { 'probe/target': 'error' },
      },
    ],
    'src/subject.ts',
  );
};

describe('generated-file opt-outs', () => {
  for (const { name, rule, code } of CASES) {
    describe(name, () => {
      it('reports in ordinary source — the control', () => {
        expect(lint(rule, code).filter((m) => m.ruleId === 'probe/target').length).toBeGreaterThan(0);
      });

      it('stays silent on the same code behind a generated banner', () => {
        expect(lint(rule, BANNER + code).filter((m) => m.ruleId === 'probe/target')).toEqual([]);
      });
    });
  }
});
