/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 *
 * @provenBy {"file":"benchmarks/suites/ilb-oxlint-parity/run.ts","find":"if (files.length === 0) {\n    // A missing or empty corpus must not read as \"oxlint agrees with\n    // nothing\" — that is exactly the fabricated-measurement shape this fix\n    // exists to eliminate.\n    throw new Error(`oxlint corpus contains no lintable files: ${corpus}`);\n  }","replace":"if (files.length === 0) return [];"}
 */

/**
 * ILB-Oxlint-Parity collapsed to 0% (issue #906): ESLint found 10944
 * findings on the harvested-fixtures corpus, oxlint found 0.
 *
 * Root cause — reproduced and pinned here — is NOT a shim or rule bug.
 * `harvested-fixtures/` is `.gitignore`d (it is regenerated by
 * `harvest-fixtures.ts`, never committed). oxlint's directory walker is
 * git-aware and silently prunes an entire gitignored directory before a
 * single rule runs — `npx oxlint <gitignored-dir>` printed "No files found
 * to lint" and returned `number_of_files: 0`. `--no-ignore` does NOT
 * override this: it only disables `.eslintignore` / `--ignore-pattern`
 * handling, not the built-in git-ignore walk. `lintOxlint()` then fed that
 * non-JSON "No files found..." preamble straight into `JSON.parse`, whose
 * catch block swallowed the failure and returned `[]` — a real crash
 * disguised as a legitimate "oxlint found nothing" measurement.
 *
 * The fix: `lintOxlint()` enumerates the corpus itself (`corpusFiles`, a
 * plain `fs.readdirSync` walk that knows nothing about `.gitignore`) and
 * passes oxlint an explicit file list. An explicit file argument bypasses
 * directory-walk pruning entirely and is linted regardless of
 * `.gitignore`. Separately, `npx oxlint` failed outright (exit 249, empty
 * stdout/stderr) against that file list's ~4000 arguments — an npx-only
 * limit, well under the OS ARG_MAX — so the fix also calls the installed
 * `node_modules/oxlint/bin/oxlint` binary directly.
 */

import { describe, expect, it, afterEach } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(__dirname, '../..');
const RUN_TS = join(ROOT, 'benchmarks/suites/ilb-oxlint-parity/run.ts');
const OXLINT_BIN = join(ROOT, 'node_modules', 'oxlint', 'bin', 'oxlint');
// Real path under the real, already-committed .gitignore rule (see
// `.gitignore`, "Generated by benchmarks/suites/ilb-oxlint-parity/harvest-fixtures").
// Not a fixture of the test's own making — the same directory the runner
// actually points oxlint at in CI.
const GITIGNORED_DIR = join(
  ROOT,
  'benchmarks/suites/ilb-oxlint-parity/harvested-fixtures',
  `__lock-test-${process.pid}__`,
);
// The repo-root `.oxlintrc.json` (auto-discovered when no `--config` is
// given) ignorePatterns away all of `benchmarks/suites/**` on its own —
// a SEPARATE mechanism from .gitignore, and one that (unlike .gitignore)
// filters explicit file args too. Passing an explicit, minimal `--config`
// — as the real `lintOxlint()` always does — opts out of that root config
// the same way production does, isolating the .gitignore behaviour this
// test is actually about.
const MINIMAL_CONFIG = join(
  ROOT,
  'benchmarks/suites/ilb-oxlint-parity/harvested-fixtures',
  `__lock-test-config-${process.pid}__.json`,
);

/** oxlint exits 1 both on "no files found" and on any error-severity finding. */
function runOxlint(args: string[]): string {
  try {
    return execFileSync(OXLINT_BIN, args, { encoding: 'utf8' });
  } catch (err) {
    const stdout = (err as { stdout?: string }).stdout;
    if (stdout) return stdout;
    throw err;
  }
}

function numberOfFiles(raw: string): number {
  // "No files found to lint. Please check your paths and ignore patterns."
  // precedes the JSON object on stdout in that case — strip it to parse.
  return JSON.parse(raw.slice(raw.indexOf('{'))).number_of_files;
}

/**
 * Extract a top-level function's body by counting braces, not a lazy regex
 * that stops at the first unindented `}` — which would silently truncate if
 * the function were ever reformatted or nested inside something else.
 */
function extractFunctionBody(src: string, signature: string): string {
  const start = src.indexOf(signature);
  if (start === -1) return '';
  const braceStart = src.indexOf('{', start);
  let depth = 0;
  for (let i = braceStart; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') {
      depth--;
      if (depth === 0) return src.slice(start, i + 1);
    }
  }
  return '';
}

describe('oxlint parity survives a gitignored corpus (issue #906)', () => {
  afterEach(() => {
    rmSync(GITIGNORED_DIR, { recursive: true, force: true });
    rmSync(MINIMAL_CONFIG, { force: true });
  });

  it('the corpus path this test relies on is still gitignored', () => {
    // If this ever stops being true the regression this test pins can no
    // longer happen the way it did — that is worth knowing, not masking.
    const out = execFileSync(
      'git',
      ['check-ignore', join(GITIGNORED_DIR, 'a.js')],
      { cwd: ROOT, encoding: 'utf8' },
    ).trim();
    expect(out).toBe(join(GITIGNORED_DIR, 'a.js'));
  });

  it('oxlint silently finds zero files when given the gitignored directory itself', () => {
    mkdirSync(GITIGNORED_DIR, { recursive: true });
    writeFileSync(join(GITIGNORED_DIR, 'a.js'), 'debugger;\n');
    // Explicit, minimal config — same reason as lintOxlint() always passing
    // one: opt out of the repo-root .oxlintrc.json's own
    // `ignorePatterns: ["benchmarks/suites/**", ...]`, which is a separate
    // mechanism from .gitignore and would otherwise confound this test.
    writeFileSync(MINIMAL_CONFIG, JSON.stringify({ ignorePatterns: [] }));

    const raw = runOxlint([
      '--config',
      MINIMAL_CONFIG,
      '--format',
      'json',
      GITIGNORED_DIR,
    ]);
    expect(
      numberOfFiles(raw),
      'oxlint no longer prunes a gitignored directory to zero files — the ' +
        'mechanism this fix works around has changed upstream. Good news, ' +
        'but it means lintOxlint() no longer needs the explicit-file-list ' +
        'workaround; do not just delete this test without checking that.',
    ).toBe(0);
  });

  it('the same file, passed explicitly, is linted normally', () => {
    mkdirSync(GITIGNORED_DIR, { recursive: true });
    const file = join(GITIGNORED_DIR, 'a.js');
    writeFileSync(file, 'debugger;\n');
    writeFileSync(MINIMAL_CONFIG, JSON.stringify({ ignorePatterns: [] }));

    const raw = runOxlint([
      '--config',
      MINIMAL_CONFIG,
      '--format',
      'json',
      file,
    ]);
    const parsed = JSON.parse(raw);
    expect(parsed.number_of_files).toBe(1);
    expect(
      parsed.diagnostics.some((d: { code?: string }) =>
        (d.code ?? '').includes('no-debugger'),
      ),
    ).toBe(true);
  });

  it('lintOxlint() builds an explicit file list and calls the oxlint binary directly, never `npx oxlint <corpus-dir>`', () => {
    const src = readFileSync(RUN_TS, 'utf-8');
    const fn = extractFunctionBody(
      src,
      'function lintOxlint(corpus, configPath) ',
    );
    expect(fn, 'lintOxlint() was not found — did it get renamed?').not.toBe('');

    expect(
      fn,
      'lintOxlint must enumerate the corpus itself before invoking oxlint, ' +
        'not hand oxlint a bare directory path — a gitignored corpus ' +
        'directory is silently pruned to zero files otherwise.',
    ).toContain('corpusFiles(corpus)');

    expect(
      fn,
      'lintOxlint must still be the one that decides WHAT is linted, even ' +
        'though the spawning moved out of it.',
    ).toContain('runOxlintBatched');

    /*
     * The invocation itself moved into `runOxlintBatched` when the corpus
     * outgrew a single argv (9,384 files: the spawn failed with pid 0 and no
     * stdout, which the catch read as an empty result). Both assertions below
     * follow it there rather than being dropped — a lock whose subject moves
     * and is then narrowed to what still passes stops asserting the thing it
     * was written for.
     */
    const invoke = extractFunctionBody(
      src,
      'function runOxlintBatched(configPath, files) ',
    );
    expect(
      invoke,
      'runOxlintBatched() was not found — did the oxlint invocation move again?',
    ).not.toBe('');

    expect(
      invoke,
      'oxlint must not be shelled out via `npx` — it exits 249 on this ' +
        "corpus's argv size with no stdout/stderr. Call the installed " +
        'oxlint binary directly.',
    ).not.toMatch(/execFileSync\(\s*['"]npx['"]/);

    expect(
      invoke,
      'oxlint must be invoked through the installed binary directly.',
    ).toMatch(
      /node_modules['"]?\s*,\s*['"]oxlint['"]\s*,\s*['"]bin['"]\s*,\s*['"]oxlint['"]/,
    );

    expect(
      invoke,
      'a batch that produces no output must throw. It means the spawn never ' +
        'happened or died before writing — never a batch that legitimately ' +
        "found nothing, and reading it as one would report ESLint's entire " +
        'output as an oxlint gap.',
    ).toMatch(/oxlint produced no output for a batch/);

    expect(
      fn,
      'a missing or empty corpus must throw, not silently report "0 ' +
        'findings" — that reads identically to a real (and correct) ' +
        'measurement of zero divergence, which is the same disguise the ' +
        'JSON.parse bug wore.',
    ).toMatch(/if \(files\.length === 0\) \{\s*[\s\S]*?throw new Error/);
  });

  it('a malformed oxlint response is surfaced, not swallowed into a false "0 findings"', () => {
    const src = readFileSync(RUN_TS, 'utf-8');
    const fn = extractFunctionBody(
      src,
      'function lintOxlint(corpus, configPath) ',
    );
    // The exact bug: `JSON.parse(raw)` failed on the "No files found to
    // lint" preamble, the catch block ran `return []`, and that silent
    // empty array was indistinguishable from oxlint legitimately agreeing
    // with nothing. A parse failure must throw with the raw output attached,
    // not disappear into the exact `catch { return []; }` shape that hid it.
    expect(fn).toContain('parsed = JSON.parse(raw);');
    expect(fn).not.toMatch(/catch\s*\{\s*return \[\];\s*\}/);
    expect(fn).toMatch(/JSON\.parse\(raw\)[\s\S]{0,300}throw new Error/);
  });
});
