/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * The changeset gate must never apply to the Version PR.
 *
 * `changeset-release/main` is generated by the changesets action. It CONSUMES
 * changesets — deleting them — and bumps `version` across every affected
 * package. That is precisely the shape the gate rejects: consumer-visible
 * changes with no added changeset. It is also the only PR whose entire purpose
 * is to publish.
 *
 * On 2026-09-01 the gate failed #787 naming 21 packages, so no version could
 * ship. A gate whose stated purpose is "merging a package change publishes it"
 * had become the reason nothing published — the release blocked by the very
 * check meant to guarantee releases happen.
 *
 * This asserts the exemption survives, because removing it looks harmless: the
 * gate keeps passing on every ordinary PR, and only the release stops.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parse } from 'yaml';

const WORKFLOW = resolve(__dirname, '..', '..', '.github/workflows/quality.yml');

describe('the changeset gate exempts the Version PR', () => {
  it('guards on head_ref != changeset-release/main', () => {
    const doc = parse(readFileSync(WORKFLOW, 'utf8')) as {
      jobs?: Record<string, { steps?: Array<Record<string, unknown>> }>;
    };

    const steps = Object.values(doc?.jobs ?? {}).flatMap((j) => j?.steps ?? []);
    const gate = steps.find(
      (s) =>
        typeof s.run === 'string' &&
        s.run.includes('check-changeset-coverage.ts') &&
        s.run.includes('--strict'),
    );

    // If the gate is gone entirely there is nothing to exempt — that is a
    // different regression, and `changeset-gate-in-ci` covers it. Here we only
    // assert: if it exists, it must not fire on the Version PR.
    if (!gate) return;

    expect(
      String(gate.if ?? ''),
      'The strict changeset gate runs without exempting `changeset-release/main`. ' +
        'The Version PR deletes changesets and bumps versions, so the gate will ' +
        'fail it and no release can ever ship.',
    ).toContain('changeset-release/main');
  });
});
