#!/usr/bin/env -S npx tsx
/**
 * audit-stock-corpus-overlap — count Oxlint stock rules per namespace,
 * compute the exact-slug overlap with our `.agent/oxlint-jsplugins-manifest.json`,
 * and report drift vs the previous committed snapshot.
 *
 * Sources:
 *   - Oxlint stock corpus: `crates/oxc_linter/src/rules/<ns>/*.rs` (minus `mod.rs`)
 *     in a local clone of `oxc-project/oxc`. Default path `../oos/oxc`;
 *     override with `--oxc <path>` or `OXC_PATH=`.
 *   - Our rule set: `.agent/oxlint-jsplugins-manifest.json` (authoritative,
 *     regenerated by `scripts/generate-oxlint-shims.ts`).
 *
 * Outputs:
 *   - `benchmark-results/stock-corpus-overlap.json` — structured data
 *   - `benchmark-results/stock-corpus-overlap.md`   — markdown report
 *
 * Drift detection: when the previous JSON exists, the markdown report
 * includes a "Changes since last run" section. The strict mode fails
 * CI when overlap *grows* (we accidentally shipped a rule that exactly
 * duplicates an Oxlint stock rule) — that's the signal a new duplicate
 * landed without a justification.
 *
 * Backs the §"Authoritative counts" + §"Authoritative exact-name overlap"
 * tables in `distribution/OXLINT_STOCK_OVERLAP.md`.
 *
 * Usage:
 *   npm run audit:stock-overlap
 *   npm run audit:stock-overlap -- --oxc /path/to/oxc-checkout
 *   npm run audit:stock-overlap:strict  # fails on duplicate-slug growth
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const DEFAULT_OXC = path.resolve(REPO_ROOT, '..', 'oos', 'oxc');
const MANIFEST_PATH = path.join(REPO_ROOT, '.agent', 'oxlint-jsplugins-manifest.json');
const JSON_OUT = path.join(REPO_ROOT, 'benchmark-results', 'stock-corpus-overlap.json');
const MD_OUT = path.join(REPO_ROOT, 'benchmark-results', 'stock-corpus-overlap.md');

export interface NamespaceSnapshot {
  namespace: string;
  ruleCount: number;
  rules: string[]; // kebab-case slugs, sorted
}

export interface OverlapData {
  generatedAt: string;
  oxc: {
    path: string;
    commit: string | null;
    namespaceCount: number;
    totalRuleFiles: number;
    uniqueSlugs: number;
    namespaces: NamespaceSnapshot[];
  };
  ours: {
    manifestPath: string;
    pluginCount: number;
    totalRules: number;
    uniqueSlugs: number;
  };
  overlap: {
    slugCount: number;
    slugs: string[]; // sorted
    byOurPlugin: Array<{
      plugin: string;
      overlappingSlugs: string[];
    }>;
    byOxlintNamespace: Array<{
      namespace: string;
      overlappingSlugs: string[];
    }>;
  };
}

/**
 * Walk `<oxcRoot>/crates/oxc_linter/src/rules/<ns>/*.rs` (excluding
 * `mod.rs`) and produce a snapshot per namespace. Pure: takes a
 * filesystem-shaped object so the unit tests can pass a fixture root.
 */
export function readOxlintRules(oxcRoot: string): NamespaceSnapshot[] {
  const rulesDir = path.join(oxcRoot, 'crates', 'oxc_linter', 'src', 'rules');
  if (!fs.existsSync(rulesDir)) {
    throw new Error(
      `Oxlint rules dir not found at ${rulesDir}. ` +
        `Clone oxc-project/oxc to ${DEFAULT_OXC} or pass --oxc <path>.`,
    );
  }
  const out: NamespaceSnapshot[] = [];
  for (const entry of fs.readdirSync(rulesDir)) {
    const nsDir = path.join(rulesDir, entry);
    if (!fs.statSync(nsDir).isDirectory()) continue;
    const rules = fs
      .readdirSync(nsDir)
      .filter((f) => f.endsWith('.rs') && f !== 'mod.rs')
      .map((f) => f.replace(/\.rs$/, '').replace(/_/g, '-'))
      .sort();
    out.push({ namespace: entry, ruleCount: rules.length, rules });
  }
  return out.sort((a, b) => a.namespace.localeCompare(b.namespace));
}

/**
 * Strip a leading `<scope>/` prefix from a rule name and return the
 * bare slug. Our manifest contains a mix of bare slugs and
 * scope-prefixed ones (e.g. `conventions/filename-case`), so this
 * normalization is required for fair comparison.
 */
export function bareSlug(name: string): string {
  return name.includes('/') ? name.slice(name.indexOf('/') + 1) : name;
}

export interface ManifestPlugin {
  package: string;
  short: string;
  ruleCount: number;
  rules: Array<{ name: string }>;
}

export interface Manifest {
  totalPlugins?: number;
  totalRules?: number;
  plugins: ManifestPlugin[];
}

export function readManifest(manifestPath: string): Manifest {
  const raw = fs.readFileSync(manifestPath, 'utf8');
  return JSON.parse(raw) as Manifest;
}

/**
 * Compute the exact-slug overlap. Returns a fully-populated overlap
 * record ready for serialization. Pure.
 */
export function computeOverlap(
  oxlintNamespaces: NamespaceSnapshot[],
  manifest: Manifest,
): OverlapData['overlap'] & {
  ourUniqueSlugs: number;
  oxlintUniqueSlugs: number;
  ourTotalRules: number;
} {
  // Build the oxlint slug→namespace[] index. A slug can appear in
  // multiple namespaces (e.g. `no-deprecated` in both `import` and
  // `typescript`); we track all of them.
  const slugToOxlintNs = new Map<string, Set<string>>();
  let oxlintTotal = 0;
  for (const ns of oxlintNamespaces) {
    for (const slug of ns.rules) {
      if (!slugToOxlintNs.has(slug)) slugToOxlintNs.set(slug, new Set());
      slugToOxlintNs.get(slug)!.add(ns.namespace);
      oxlintTotal += 1;
    }
  }
  const oxlintUniqueSlugs = slugToOxlintNs.size;

  // Build the our slug→plugin[] index.
  const ourSlugToPlugins = new Map<string, Set<string>>();
  let ourTotal = 0;
  for (const plugin of manifest.plugins) {
    for (const rule of plugin.rules) {
      const slug = bareSlug(rule.name);
      if (!ourSlugToPlugins.has(slug)) ourSlugToPlugins.set(slug, new Set());
      ourSlugToPlugins.get(slug)!.add(plugin.package);
      ourTotal += 1;
    }
  }
  const ourUniqueSlugs = ourSlugToPlugins.size;

  // Intersection: slugs present in both.
  const overlapSlugs: string[] = [];
  for (const slug of ourSlugToPlugins.keys()) {
    if (slugToOxlintNs.has(slug)) overlapSlugs.push(slug);
  }
  overlapSlugs.sort();

  // Group overlap by our plugin.
  const byPluginMap = new Map<string, string[]>();
  for (const slug of overlapSlugs) {
    for (const plugin of ourSlugToPlugins.get(slug)!) {
      if (!byPluginMap.has(plugin)) byPluginMap.set(plugin, []);
      byPluginMap.get(plugin)!.push(slug);
    }
  }
  const byOurPlugin = [...byPluginMap.entries()]
    .map(([plugin, slugs]) => ({ plugin, overlappingSlugs: slugs.sort() }))
    .sort((a, b) => a.plugin.localeCompare(b.plugin));

  // Group overlap by Oxlint namespace.
  const byNsMap = new Map<string, string[]>();
  for (const slug of overlapSlugs) {
    for (const ns of slugToOxlintNs.get(slug)!) {
      if (!byNsMap.has(ns)) byNsMap.set(ns, []);
      byNsMap.get(ns)!.push(slug);
    }
  }
  const byOxlintNamespace = [...byNsMap.entries()]
    .map(([namespace, slugs]) => ({ namespace, overlappingSlugs: slugs.sort() }))
    .sort((a, b) => a.namespace.localeCompare(b.namespace));

  return {
    slugCount: overlapSlugs.length,
    slugs: overlapSlugs,
    byOurPlugin,
    byOxlintNamespace,
    ourUniqueSlugs,
    oxlintUniqueSlugs,
    ourTotalRules: ourTotal,
  };
}

/**
 * Try to read the HEAD commit of the oxc checkout. Falls back to null
 * when it isn't a git checkout or git isn't available.
 */
function readOxcCommit(oxcRoot: string): string | null {
  try {
    return execSync('git rev-parse --short HEAD', {
      cwd: oxcRoot,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

/**
 * Diff a fresh overlap record against the previous on-disk snapshot.
 * Returns null when there is no previous snapshot.
 */
export interface OverlapDiff {
  newSlugs: string[];
  removedSlugs: string[];
  namespaceCountChange: number;
  ruleCountChange: number;
  perNamespaceChanges: Array<{
    namespace: string;
    before: number;
    after: number;
    delta: number;
  }>;
}

export function diffAgainstPrevious(
  fresh: OverlapData,
  previous: OverlapData | null,
): OverlapDiff | null {
  if (!previous) return null;
  const prevSlugs = new Set(previous.overlap.slugs);
  const freshSlugs = new Set(fresh.overlap.slugs);
  const newSlugs = [...freshSlugs].filter((s) => !prevSlugs.has(s)).sort();
  const removedSlugs = [...prevSlugs].filter((s) => !freshSlugs.has(s)).sort();
  const namespaceCountChange =
    fresh.oxc.namespaceCount - previous.oxc.namespaceCount;
  const ruleCountChange = fresh.oxc.totalRuleFiles - previous.oxc.totalRuleFiles;
  // Per-namespace deltas.
  const prevByNs = new Map(previous.oxc.namespaces.map((n) => [n.namespace, n.ruleCount]));
  const freshByNs = new Map(fresh.oxc.namespaces.map((n) => [n.namespace, n.ruleCount]));
  const allNs = new Set([...prevByNs.keys(), ...freshByNs.keys()]);
  const perNamespaceChanges = [...allNs]
    .map((namespace) => {
      const before = prevByNs.get(namespace) ?? 0;
      const after = freshByNs.get(namespace) ?? 0;
      return { namespace, before, after, delta: after - before };
    })
    .filter((d) => d.delta !== 0)
    .sort((a, b) => b.delta - a.delta);
  return { newSlugs, removedSlugs, namespaceCountChange, ruleCountChange, perNamespaceChanges };
}

function renderMarkdown(data: OverlapData, diff: OverlapDiff | null): string {
  const lines: string[] = [];
  lines.push('# Stock corpus overlap — Oxlint vs Interlace');
  lines.push('');
  lines.push(`> Generated by \`npm run audit:stock-overlap\` at ${data.generatedAt}.`);
  lines.push(`> Oxlint source: \`${data.oxc.path}\`${data.oxc.commit ? ` @ \`${data.oxc.commit}\`` : ''}.`);
  lines.push(`> Manifest: \`${data.ours.manifestPath}\`.`);
  lines.push('');

  lines.push('## Headline numbers');
  lines.push('');
  lines.push(`- **Oxlint stock corpus:** ${data.oxc.totalRuleFiles} rule files across ${data.oxc.namespaceCount} namespaces (${data.oxc.uniqueSlugs} unique slugs).`);
  lines.push(`- **Our manifest:** ${data.ours.totalRules} rules across ${data.ours.pluginCount} plugins (${data.ours.uniqueSlugs} unique slugs).`);
  lines.push(`- **Exact-slug overlap:** ${data.overlap.slugCount} (${Math.round((data.overlap.slugCount / Math.max(1, data.ours.uniqueSlugs)) * 100)}% of our slug set).`);
  lines.push('');

  lines.push('## Per-namespace counts (Oxlint stock)');
  lines.push('');
  lines.push('| Namespace | Rules |');
  lines.push('| :--- | ---: |');
  for (const ns of data.oxc.namespaces) {
    lines.push(`| \`${ns.namespace}\` | ${ns.ruleCount} |`);
  }
  lines.push(`| **Total** | **${data.oxc.totalRuleFiles}** |`);
  lines.push('');

  lines.push('## Overlap by our plugin');
  lines.push('');
  lines.push('| Our plugin | Overlapping slugs | Examples |');
  lines.push('| :--- | ---: | :--- |');
  for (const p of data.overlap.byOurPlugin) {
    const sample = p.overlappingSlugs.slice(0, 6).map((s) => `\`${s}\``).join(', ');
    const more = p.overlappingSlugs.length > 6 ? `, … (+${p.overlappingSlugs.length - 6})` : '';
    lines.push(`| \`${p.plugin}\` | ${p.overlappingSlugs.length} | ${sample}${more} |`);
  }
  lines.push('');

  lines.push('## Overlap by Oxlint namespace');
  lines.push('');
  lines.push('| Oxlint namespace | Overlapping slugs | Examples |');
  lines.push('| :--- | ---: | :--- |');
  for (const n of data.overlap.byOxlintNamespace) {
    const sample = n.overlappingSlugs.slice(0, 6).map((s) => `\`${s}\``).join(', ');
    const more = n.overlappingSlugs.length > 6 ? `, … (+${n.overlappingSlugs.length - 6})` : '';
    lines.push(`| \`${n.namespace}\` | ${n.overlappingSlugs.length} | ${sample}${more} |`);
  }
  lines.push('');

  if (diff) {
    lines.push('## Changes since last run');
    lines.push('');
    lines.push(`- Oxlint namespaces Δ: ${diff.namespaceCountChange >= 0 ? '+' : ''}${diff.namespaceCountChange}`);
    lines.push(`- Oxlint rule files Δ: ${diff.ruleCountChange >= 0 ? '+' : ''}${diff.ruleCountChange}`);
    lines.push(`- Overlapping slugs added: ${diff.newSlugs.length}${diff.newSlugs.length > 0 ? ` (${diff.newSlugs.map((s) => `\`${s}\``).join(', ')})` : ''}`);
    lines.push(`- Overlapping slugs removed: ${diff.removedSlugs.length}${diff.removedSlugs.length > 0 ? ` (${diff.removedSlugs.map((s) => `\`${s}\``).join(', ')})` : ''}`);
    if (diff.perNamespaceChanges.length > 0) {
      lines.push('');
      lines.push('### Per-namespace rule-count deltas');
      lines.push('');
      lines.push('| Namespace | Before | After | Δ |');
      lines.push('| :--- | ---: | ---: | ---: |');
      for (const d of diff.perNamespaceChanges) {
        lines.push(`| \`${d.namespace}\` | ${d.before} | ${d.after} | ${d.delta >= 0 ? '+' : ''}${d.delta} |`);
      }
    }
    lines.push('');
  }

  lines.push('## How this maps to evaluation metrics');
  lines.push('');
  lines.push('- Backs the §"Authoritative counts" + §"Authoritative exact-name overlap" tables in [`distribution/OXLINT_STOCK_OVERLAP.md`](../distribution/OXLINT_STOCK_OVERLAP.md).');
  lines.push('- A growth in overlapping slugs is the signal that we shipped a duplicate rule — strict mode (`audit:stock-overlap:strict`) fails on it so the PR diff explains the intent (article + justification, per `competitor_study_2026-05-09.md`).');
  lines.push('');
  return lines.join('\n');
}

interface CliArgs {
  oxcPath: string;
  strict: boolean;
}

function parseArgs(): CliArgs {
  const argv = process.argv.slice(2);
  let oxcPath = process.env.OXC_PATH || DEFAULT_OXC;
  const i = argv.indexOf('--oxc');
  if (i >= 0 && argv[i + 1]) oxcPath = argv[i + 1];
  return { oxcPath, strict: argv.includes('--strict') };
}

function main() {
  const args = parseArgs();
  const namespaces = readOxlintRules(args.oxcPath);
  const manifest = readManifest(MANIFEST_PATH);

  const overlap = computeOverlap(namespaces, manifest);

  const data: OverlapData = {
    generatedAt: new Date().toISOString(),
    oxc: {
      path: path.relative(REPO_ROOT, args.oxcPath) || args.oxcPath,
      commit: readOxcCommit(args.oxcPath),
      namespaceCount: namespaces.length,
      totalRuleFiles: namespaces.reduce((acc, ns) => acc + ns.ruleCount, 0),
      uniqueSlugs: overlap.oxlintUniqueSlugs,
      namespaces,
    },
    ours: {
      manifestPath: path.relative(REPO_ROOT, MANIFEST_PATH),
      pluginCount: manifest.plugins.length,
      totalRules: overlap.ourTotalRules,
      uniqueSlugs: overlap.ourUniqueSlugs,
    },
    overlap: {
      slugCount: overlap.slugCount,
      slugs: overlap.slugs,
      byOurPlugin: overlap.byOurPlugin,
      byOxlintNamespace: overlap.byOxlintNamespace,
    },
  };

  let previous: OverlapData | null = null;
  if (fs.existsSync(JSON_OUT)) {
    try {
      previous = JSON.parse(fs.readFileSync(JSON_OUT, 'utf8')) as OverlapData;
    } catch {
      previous = null;
    }
  }
  const diff = diffAgainstPrevious(data, previous);

  fs.mkdirSync(path.dirname(JSON_OUT), { recursive: true });
  fs.writeFileSync(JSON_OUT, JSON.stringify(data, null, 2) + '\n');
  fs.writeFileSync(MD_OUT, renderMarkdown(data, diff));

  // eslint-disable-next-line no-console
  console.log(`Wrote ${path.relative(REPO_ROOT, JSON_OUT)} and ${path.relative(REPO_ROOT, MD_OUT)}`);
  // eslint-disable-next-line no-console
  console.log(
    `Oxlint: ${data.oxc.totalRuleFiles} rules / ${data.oxc.namespaceCount} ns; ours: ${data.ours.totalRules} rules / ${data.ours.pluginCount} plugins; overlap: ${data.overlap.slugCount}.`,
  );

  if (diff && diff.newSlugs.length > 0) {
    // eslint-disable-next-line no-console
    console.warn(
      `New overlapping slugs detected: ${diff.newSlugs.join(', ')}. ` +
        `Each must have either a retirement plan or a justification article ` +
        `(see competitor_study_2026-05-09.md for the pattern).`,
    );
    if (args.strict) process.exit(1);
  }
}

if (process.argv[1] && process.argv[1].endsWith('audit-stock-corpus-overlap.ts')) {
  main();
}
