/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * Write one runnable lint config per exported rule.
 *
 * Every published number in this repo is supposed to ship with the command that
 * produced it. These files are that promise made literal: 566 configs, each
 * naming exactly one rule, each runnable by a stranger with no knowledge of our
 * tooling.
 *
 * They are thin on purpose — the file set, the parser and the exclusions live in
 * base.mjs, because three instruments here once measured the same rule against
 * three different file lists.
 *
 *   npx tsx scripts/gen-rule-configs.mts
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'benchmarks/configs');
fs.mkdirSync(OUT, { recursive: true });

let written = 0;
let plugins = 0;

for (const dir of fs.readdirSync(path.join(ROOT, 'packages')).filter((d) => d.startsWith('eslint-plugin-'))) {
  const entry = path.join(ROOT, 'packages', dir, 'dist/src/index.js');
  if (!fs.existsSync(entry)) continue;
  const prefix = dir.replace('eslint-plugin-', '');
  const mod = (await import(entry)) as Record<string, unknown>;
  // `rules` may sit on the namespace or on the default export; `configs` is a
  // separate named export. Taking each from where it actually is rather than
  // through `default ?? mod`, which silently yields the wrong object.
  const dflt = (mod.default ?? {}) as Record<string, unknown>;
  const rules = (mod.rules ?? dflt.rules ?? {}) as Record<string, unknown>;
  const names = Object.keys(rules);
  if (names.length === 0) continue;
  plugins += 1;

  for (const key of names) {
    // Two shapes of key, both legal, both of which broke the first version.
    //
    // Some plugins key their rules WITH the prefix already attached
    // (`maintainability/cognitive-complexity`), which yielded a rule id of
    // `maintainability/maintainability/…`. Strip it once.
    //
    // Others namespace by category (`react/jsx-key` inside react-features), so
    // the real rule id legitimately contains a slash. Only the FILENAME needs
    // flattening — the first version skipped 65 rules over this.
    const name = key.startsWith(`${prefix}/`) ? key.slice(prefix.length + 1) : key;
    const fileSafe = name.replace(/\//g, '__');
    fs.writeFileSync(
      path.join(OUT, `${prefix}__${fileSafe}.config.mjs`),
      `// Generated by scripts/gen-rule-configs.mts — do not edit by hand.
//
//   npx eslint --config benchmarks/configs/${prefix}__${fileSafe}.config.mjs \\
//              --no-config-lookup <path>
//
// One rule at \`error\` and nothing else, so a finding can only have come from
// ${prefix}/${name}.
import * as plugin from '../../packages/eslint-plugin-${prefix}/dist/src/index.js';
import { forRule } from './base.mjs';

export default forRule('${prefix}', '${name}', { '${name}': plugin.rules['${key}'] });
`,
    );
    written += 1;
  }
}

console.log(`\n  ${written} config(s) across ${plugins} plugin(s) → benchmarks/configs/\n`);
