#!/usr/bin/env -S npx tsx

/**
 * generate-oxlint-shims.mjs — Idempotent generator for oxlint JS-plugin adoption.
 *
 * For every Interlace plugin that has at least one rule, ensures three things
 * exist (creates them if missing, leaves them alone if already correct):
 *
 *   1. packages/eslint-plugin-<name>/src/oxlint.ts
 *      Tiny re-export so external consumers can wire `eslint-plugin-<name>/oxlint`.
 *
 *   2. packages/eslint-plugin-<name>/package.json `"./oxlint"` subpath in `exports`.
 *
 *   3. tools/oxlint-plugins/interlace-<short>.cjs
 *      In-repo shim that patches `@interlace/*` workspace resolution and loads
 *      the built plugin from `dist/packages/`.
 *
 * Also writes .agent/oxlint-jsplugins-manifest.json — a machine-readable map of
 * every plugin's shim path and per-rule oxlint-portability classification (used
 * by the CI gate, parity benchmark, and docs generators).
 *
 * Usage:
 *   tsx scripts/generate-oxlint-shims.ts              # write
 *   tsx scripts/generate-oxlint-shims.ts --check      # exit 1 on drift, no writes
 *   tsx scripts/generate-oxlint-shims.ts --json       # print summary as JSON
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execFileSync } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PACKAGES_DIR = path.join(ROOT, 'packages');
const SHIM_DIR = path.join(ROOT, 'tools', 'oxlint-plugins');
const MANIFEST_PATH = path.join(ROOT, '.agent', 'oxlint-jsplugins-manifest.json');

const args = new Set(process.argv.slice(2));
const CHECK_ONLY = args.has('--check');
const JSON_ONLY = args.has('--json');

const log = (...x) => { if (!JSON_ONLY) console.log(...x); };

// ── Templates ──────────────────────────────────────────────────────────

const OXLINT_TS_TEMPLATE = `/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * oxlint sub-export.
 *
 * Consumers wire oxlint to this entry via:
 *   { "jsPlugins": ["<PACKAGE>/oxlint"] }
 *
 * oxlint's JS plugin loader does \`require('<PACKAGE>/oxlint')\` and reads
 * \`.rules\` off the result. The compiled output of \`export = plugin\` is
 * \`module.exports = plugin\`, which gives oxlint the plugin object directly
 * (\`{ meta, rules }\`) — no wrapper, no \`.default\` indirection.
 *
 * Generated by scripts/generate-oxlint-shims.mjs. Do not edit by hand.
 */

import { plugin } from './index';

export = plugin;
`;

const SHIM_CJS_TEMPLATE = `/**
 * Oxlint JS Plugin Shim — <PACKAGE>
 *
 * Loads the built plugin from \`<pkg>/dist/\` (per-package layout used by the
 * Turborepo build), patching module resolution so workspace \`@interlace/*\`
 * deps resolve to compiled JS instead of TS source symlinks.
 *
 * Usage in .oxlintrc.json:
 *   "jsPlugins": ["./tools/oxlint-plugins/<SHIM_BASENAME>.cjs"]
 *
 * Prerequisites:
 *   npx turbo run build --filter=<PACKAGE>
 *
 * Generated by scripts/generate-oxlint-shims.mjs. Do not edit by hand.
 */

const path = require('path');
const Module = require('module');

const packagesDir = path.join(__dirname, '../../packages');
const devkitDist = path.join(packagesDir, 'eslint-devkit/dist/src');

const originalResolve = Module._resolveFilename;
Module._resolveFilename = function(request, parent, isMain, options) {
  if (request === '@interlace/eslint-devkit') {
    return path.join(devkitDist, 'index.js');
  }
  if (request === '@interlace/eslint-devkit/resolver') {
    return path.join(devkitDist, 'resolver.js');
  }
  return originalResolve.apply(this, arguments);
};

module.exports = require(path.join(packagesDir, '<PACKAGE>/dist/src/index.js'));
`;

// ── Helpers ───────────────────────────────────────────────────────────

function shortName(packageName) {
  return packageName.replace(/^eslint-plugin-/, '');
}

function shimBasename(packageName) {
  return `interlace-${shortName(packageName)}`;
}

// Reuse the audit script for rule discovery + classification so the manifest
// stays in lockstep with what the CI gate measures.
function loadPortabilityData() {
  // execFileSync with array args — no shell, no interpolation. The
  // `__dirname`-derived absolute path is now passed as a discrete arg, not
  // interpolated into a shell string (CodeQL:
  // `js/shell-command-injection-from-environment`).
  const out = execFileSync(
    'npx',
    ['tsx', path.join(__dirname, 'audit-rule-portability.ts'), '--json'],
    { encoding: 'utf-8', maxBuffer: 32 * 1024 * 1024 },
  );
  return JSON.parse(out);
}

// ── Drift tracking ────────────────────────────────────────────────────

const drift = []; // { kind, path, action }

function ensureFile(filePath, expectedContent) {
  // Single read captures both existence and content — eliminates the
  // existsSync → readFileSync → writeFileSync sequence the analyzer flagged
  // (CodeQL: `js/file-system-race`).
  let current = null;
  let exists = false;
  try {
    current = fs.readFileSync(filePath, 'utf-8');
    exists = true;
  } catch (e) {
    if (e.code !== 'ENOENT') throw e;
  }
  if (current === expectedContent) return 'unchanged';

  drift.push({ kind: 'file', path: filePath, action: exists ? 'updated' : 'created' });
  if (!CHECK_ONLY) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, expectedContent);
  }
  return exists ? 'updated' : 'created';
}

function ensureSubpathExport(pkgPath) {
  const raw = fs.readFileSync(pkgPath, 'utf-8');
  const json = JSON.parse(raw);
  const exports_ = json.exports || {};

  const desired = {
    types: './src/oxlint.d.ts',
    default: './src/oxlint.js',
  };

  const current = exports_['./oxlint'];
  const matches = current
    && current.types === desired.types
    && current.default === desired.default;

  if (matches) return 'unchanged';

  drift.push({ kind: 'package.json', path: pkgPath, action: current ? 'updated' : 'added' });
  if (!CHECK_ONLY) {
    json.exports = exports_;
    json.exports['./oxlint'] = desired;
    // Preserve trailing newline if present.
    const trailing = raw.endsWith('\n') ? '\n' : '';
    fs.writeFileSync(pkgPath, JSON.stringify(json, null, 2) + trailing);
  }
  return current ? 'updated' : 'added';
}

// ── Main ──────────────────────────────────────────────────────────────

const portability = loadPortabilityData();
const eligible = portability.filter(p => p.ruleCount > 0);

const manifestEntries = [];

for (const plugin of eligible) {
  const pkg = plugin.plugin;
  const pkgDir = path.join(PACKAGES_DIR, pkg);
  const indexTs = path.join(pkgDir, 'src', 'index.ts');
  if (!fs.existsSync(indexTs)) continue;

  const oxlintTs = path.join(pkgDir, 'src', 'oxlint.ts');
  const pkgJson = path.join(pkgDir, 'package.json');
  const shimPath = path.join(SHIM_DIR, `${shimBasename(pkg)}.cjs`);

  const oxlintTsContent = OXLINT_TS_TEMPLATE.replaceAll('<PACKAGE>', pkg);
  const shimContent = SHIM_CJS_TEMPLATE
    .replaceAll('<PACKAGE>', pkg)
    .replaceAll('<SHIM_BASENAME>', shimBasename(pkg));

  ensureFile(oxlintTs, oxlintTsContent);
  ensureSubpathExport(pkgJson);
  ensureFile(shimPath, shimContent);

  manifestEntries.push({
    package: pkg,
    short: shortName(pkg),
    shim: path.relative(ROOT, shimPath).replace(/\\/g, '/'),
    subpath: `${pkg}/oxlint`,
    ruleCount: plugin.ruleCount,
    rules: plugin.rules.map(r => ({
      name: r.name,
      portability: r.portability.oxlint,
      blockers: r.blockers.oxlint,
      isTypeAware: r.isTypeAware,
    })),
  });
}

// Preserve cross-regeneration state from the existing manifest:
//   - `runtimeRuleNames` snapshot is managed by verify-oxlint-shims.mjs and
//     mustn't be wiped here.
//   - `generatedAt` is preserved when nothing else changed, so re-runs on
//     a later day don't show drift just because the wall clock moved.
//     (Bug: was previously always set to `today`, which made `--check`
//     fail every day until someone re-ran the generator and committed it.)
const previous = (() => {
  if (!fs.existsSync(MANIFEST_PATH)) return undefined;
  try {
    return JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8')) as Record<string, unknown>;
  } catch {
    return undefined;
  }
})();
const previousRuntimeSnapshot = previous?.runtimeRuleNames;

// Build the manifest first with TODAY's date so we have something to
// compare against the prior on-disk version. Then, if every other field
// matches, keep the prior `generatedAt` to avoid spurious drift.
const today = new Date().toISOString().slice(0, 10);
const manifestBase = {
  generatedBy: 'scripts/generate-oxlint-shims.mjs',
  generatedAt: today,
  totalPlugins: manifestEntries.length,
  totalRules: manifestEntries.reduce((s, p) => s + p.ruleCount, 0),
  oxlintCompatible: manifestEntries.reduce(
    (s, p) => s + p.rules.filter(r => r.portability === 'compatible').length, 0),
  oxlintPartial: manifestEntries.reduce(
    (s, p) => s + p.rules.filter(r => r.portability === 'partial').length, 0),
  oxlintBlocked: manifestEntries.reduce(
    (s, p) => s + p.rules.filter(r => r.portability === 'incompatible').length, 0),
  plugins: manifestEntries,
  ...(previousRuntimeSnapshot ? { runtimeRuleNames: previousRuntimeSnapshot } : {}),
};

const generatedAt = (() => {
  if (!previous || typeof previous.generatedAt !== 'string') return today;
  const candidate = { ...manifestBase, generatedAt: previous.generatedAt };
  // Deep-equality check via canonical JSON. If nothing else changed,
  // keep the prior date.
  const prevCanonical = JSON.stringify({ ...previous });
  const cmpCanonical = JSON.stringify(candidate);
  return prevCanonical === cmpCanonical ? previous.generatedAt : today;
})();

const manifestObj = { ...manifestBase, generatedAt };

const manifestContent = JSON.stringify(manifestObj, null, 2) + '\n';
ensureFile(MANIFEST_PATH, manifestContent);

// ── Output ────────────────────────────────────────────────────────────

if (JSON_ONLY) {
  process.stdout.write(JSON.stringify({
    ...manifestObj,
    drift,
    mode: CHECK_ONLY ? 'check' : 'write',
  }, null, 2) + '\n');
} else {
  log('');
  log('═'.repeat(70));
  log('  OXLINT SHIM GENERATOR');
  log('═'.repeat(70));
  log('');
  log(`  Plugins processed:  ${manifestEntries.length}`);
  log(`  Rules total:        ${manifestObj.totalRules}`);
  log(`    compatible:       ${manifestObj.oxlintCompatible}`);
  log(`    partial:          ${manifestObj.oxlintPartial}`);
  log(`    blocked:          ${manifestObj.oxlintBlocked}`);
  log('');
  if (drift.length === 0) {
    log('  ✅ No drift — all generated files in sync.');
  } else {
    log(`  📝 ${drift.length} file(s) ${CHECK_ONLY ? 'would change' : 'changed'}:`);
    for (const d of drift) log(`     [${d.action}] ${path.relative(ROOT, d.path)}`);
  }
  log('');
}

if (CHECK_ONLY && drift.length > 0) {
  process.exit(1);
}
