/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * harvest-cases.mts — turn scan findings into cases somebody can rule on.
 *
 * ## Why this exists
 *
 * The suite has ~200 corpus fixtures under `benchmarks/rule-corpus/`, and they
 * look like independent evidence. They are not: every manifest says so in its
 * own header — "written from CWE semantics and real idiom, **not** from the
 * rule's own test file". Independent of the TESTS, still authored by us. Across
 * both corpora exactly 6 files cite a real repository.
 *
 * So a fixture corpus cannot raise the number of VERIFIED cases, however large
 * it grows. The only source of a shape nobody here invented is code somebody
 * else shipped, which means the real-source scan and nothing else.
 *
 * This reads the scan's per-rule samples, pulls the actual line and its
 * surroundings out of the clone cache, and writes them out grouped by rule so
 * each one can be read and ruled on. A finding becomes a case only after a
 * human says which it is — the point is to make that judgement cheap, not to
 * skip it.
 *
 *   npx tsx scripts/harvest-cases.mts             # every rule that fired
 *   npx tsx scripts/harvest-cases.mts <rule-id>   # one rule
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  readRealSourceInventory,
  staleNotice,
} from './lib/real-source-inventory.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CACHE = path.join(ROOT, 'benchmarks', '.real-source-cache');
const INVENTORY = path.join(ROOT, 'benchmarks', 'budgets', 'real-world-rule-inventory.json');
const OUT = path.join(ROOT, 'benchmarks', 'CANDIDATES.md');
const ONLY = process.argv[2];

type Inventory = {
  rules: Record<string, { count: number; repos: number; samples: string[] }>;
  reposScanned: number;
  filesLinted: number;
  generated: string;
};

// Refuse to harvest from a scan whose instrument we cannot vouch for. The
// candidates this produces become registry cases, and a case sourced from a
// stale scan cites a file:line that the current config may never have linted.
const { isCurrent, reason } = readRealSourceInventory(ROOT);
if (!isCurrent) {
  console.error(staleNotice(reason));
  console.error('    Harvesting from it would seed cases from a measurement nobody can reproduce.');
  process.exit(1);
}

const inventory = JSON.parse(fs.readFileSync(INVENTORY, 'utf8')) as Inventory;

/** The line a finding points at, plus one line either side for context. */
function excerpt(sample: string): { repo: string; file: string; line: number; text: string } | null {
  const at = sample.lastIndexOf(':');
  if (at === -1) return null;
  const rel = sample.slice(0, at);
  const line = Number(sample.slice(at + 1));
  const full = path.join(CACHE, rel);
  let source: string;
  try {
    source = fs.readFileSync(full, 'utf8');
  } catch {
    // A repository can be re-cloned or pruned between the scan and this run.
    // Saying so beats printing an empty excerpt that reads like a clean line.
    return null;
  }
  const lines = source.split('\n');
  const slug = rel.split('/')[0] ?? '';
  return {
    repo: slug.replace('__', '/'),
    file: rel.slice(slug.length + 1),
    line,
    text: (lines[line - 1] ?? '').trim().slice(0, 160),
  };
}

const wanted = Object.entries(inventory.rules)
  .filter(([id]) => ONLY === undefined || id === ONLY)
  .sort((a, b) => b[1].count - a[1].count);

const md: string[] = [
  '# Candidate cases',
  '',
  `Findings from the real-source scan of ${inventory.reposScanned} repositories`,
  `(${inventory.filesLinted} files, ${inventory.generated}), grouped by rule and ready to be`,
  'ruled on. Generated by `scripts/harvest-cases.mts` — regenerate, do not edit.',
  '',
  'A row here is **not** a verdict. It is a shape that occurred in code nobody',
  'here wrote, which is the one property our fixture corpora cannot have: every',
  '`benchmarks/rule-corpus/` manifest states it was written from CWE semantics',
  'rather than harvested, and across both corpora exactly 6 files cite a real',
  'repository.',
  '',
  'Ruling on a row means deciding TP or FP, then copying it into the rule’s test',
  'file with an `@source` line. That is what moves the verified count.',
  '',
];

let rows = 0;
for (const [rule, hit] of wanted) {
  const excerpts = hit.samples.map(excerpt).filter((e): e is NonNullable<typeof e> => e !== null);
  if (excerpts.length === 0) continue;
  md.push(`## \`${rule}\``, '', `${hit.count} findings across ${hit.repos} repositories.`, '');
  md.push('| where | line |', '|---|---|');
  for (const e of excerpts) {
    /**
     * Escaped plain text, not a code span. Harvested lines contain backticks —
     * template literals are common in exactly the code these rules fire on —
     * and a backtick cannot be escaped INSIDE a code span, so every such row
     * broke its own formatting.
     */
    const cell = e.text.replace(/[\\`*_{}[\]()#+\-.!|<>]/g, (c) => `\\${c}`) || '(blank)';
    md.push(`| \`${e.repo} ${e.file}:${e.line}\` | ${cell} |`);
    rows += 1;
  }
  md.push('');
}

md.splice(
  12,
  0,
  `**${wanted.length} rules · ${rows} candidate rows.**`,
  '',
);

fs.writeFileSync(OUT, `${md.join('\n')}\n`);
console.log(`  ${wanted.length} rules · ${rows} candidates → ${path.relative(ROOT, OUT)}`);
