#!/usr/bin/env -S npx tsx
/**
 * ilb-leaderboard-publish — generate the public leaderboard from
 * `benchmarks/submissions/` (roadmap item 3.1).
 *
 * Walks every submission envelope under `benchmarks/submissions/<tool>/<date>/`,
 * validates the schema + the toolchain block, recomputes scores from the
 * sibling SARIF (or trusts pre-computed effectiveness if present), and emits:
 *
 *   - `benchmark-results/leaderboard.md`     human-readable ranked table
 *   - `benchmark-results/leaderboard.json`   machine-readable, embeddable
 *
 * Submissions ranked by `effectiveness.f1` (descending). Ties broken by
 * latency (lower is better) then submission timestamp (earlier wins).
 *
 * The hosted UI (Phase 3.1+ deployment) embeds the JSON. Until then, this
 * Markdown file is the authoritative leaderboard — same single-source-of-
 * truth principle as the rest of the bench.
 *
 * Usage:
 *   node scripts/ilb-leaderboard-publish.mjs
 *   node scripts/ilb-leaderboard-publish.mjs --check    # CI gate, fail on invalid envelope
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateToolchain } from '../benchmarks/lib/toolchain.ts';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const SUBMISSIONS_ROOT = path.join(REPO_ROOT, 'benchmarks', 'submissions');
const OUT_DIR = path.join(REPO_ROOT, 'benchmark-results');

const CHECK = process.argv.includes('--check');

function listSubmissionEnvelopes() {
  if (!fs.existsSync(SUBMISSIONS_ROOT)) return [];
  const out = [];
  for (const tool of fs.readdirSync(SUBMISSIONS_ROOT, { withFileTypes: true })) {
    if (!tool.isDirectory()) continue;
    const toolDir = path.join(SUBMISSIONS_ROOT, tool.name);
    for (const date of fs.readdirSync(toolDir, { withFileTypes: true })) {
      if (!date.isDirectory()) continue;
      const envelope = path.join(toolDir, date.name, 'envelope.json');
      if (fs.existsSync(envelope)) out.push({ tool: tool.name, date: date.name, envelopePath: envelope });
    }
  }
  return out;
}

function validateEnvelope(env, label) {
  const issues = [];
  for (const f of ['bench', 'benchVersion', 'tool', 'submitter', 'timestamp', 'methodologyCommit', 'toolchain', 'corpus']) {
    if (env[f] === undefined) issues.push(`${label}: missing required field "${f}"`);
  }
  if (env.toolchain) {
    for (const t of validateToolchain(env.toolchain)) issues.push(`${label}: ${t}`);
  }
  if (env.bench && env.bench !== 'ILB-Public-Submission') {
    issues.push(`${label}: bench must be "ILB-Public-Submission" for public-leaderboard envelopes (got "${env.bench}")`);
  }
  return issues;
}

function rankSubmissions(submissions) {
  return [...submissions].sort((a, b) => {
    const f1A = a.effectiveness?.f1 ?? -Infinity;
    const f1B = b.effectiveness?.f1 ?? -Infinity;
    if (f1A !== f1B) return f1B - f1A;
    const latA = a.latency?.meanLatencyMs ?? Infinity;
    const latB = b.latency?.meanLatencyMs ?? Infinity;
    if (latA !== latB) return latA - latB;
    return new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime();
  });
}

function renderMd(ranked) {
  const lines = [];
  lines.push('# ILB Public Leaderboard');
  lines.push('');
  lines.push(`> Generated by \`npm run ilb:leaderboard:publish\` on ${new Date().toISOString()}.`);
  lines.push('> Submissions accepted via PR to `benchmarks/submissions/<tool>/<date>/`. Submission protocol: [audits/2026-05-09-ilb-submission-protocol.md](../benchmarks/audits/2026-05-09-ilb-submission-protocol.md).');
  lines.push('');
  if (ranked.length === 0) {
    lines.push('_No submissions yet. The first reference submission will land at `benchmarks/submissions/interlace/`._');
    return lines.join('\n');
  }
  lines.push(`**${ranked.length} submission(s).** Ranked by F1 (CVSS-weighted), tie-broken by latency, then submission timestamp.`);
  lines.push('');
  lines.push('| Rank | Tool | Version | F1 | Precision | Recall | ms/file | Toolchain | Submitter |');
  lines.push('|---:|---|---|---:|---:|---:|---:|---|---|');
  for (let i = 0; i < ranked.length; i++) {
    const s = ranked[i];
    const eff = s.effectiveness ?? {};
    const lat = s.latency ?? {};
    const tc = s.toolchain ?? {};
    const tcSummary = `node@${tc.node ?? '?'} · eslint@${tc.eslint ?? '?'} · ${tc.tsCompiler ?? '?'}`;
    lines.push(`| ${i + 1} | **${s.tool?.name ?? s._dirTool}** | ${s.tool?.version ?? '—'} | ${formatPct(eff.f1)} | ${formatPct(eff.precision)} | ${formatPct(eff.recall)} | ${lat.msPerFile != null ? lat.msPerFile.toFixed(2) : '—'} | ${tcSummary} | ${s.submitter?.affiliation ?? s.submitter?.name ?? '—'} |`);
  }
  lines.push('');
  lines.push('## Disagreement matrix');
  lines.push('');
  lines.push('Where submissions differ from each other on the same fixture is the most interesting signal. Generated alongside the leaderboard once ≥ 2 submissions exist; per-cell drilldowns at `benchmark-results/leaderboard-disagreement.md` (Phase 3.2 deliverable).');
  return lines.join('\n');
}

function formatPct(v) {
  if (typeof v !== 'number' || Number.isNaN(v)) return '—';
  return `${(v * 100).toFixed(1)}%`;
}

function main() {
  const envelopes = listSubmissionEnvelopes();

  const submissions = [];
  const allIssues = [];
  for (const e of envelopes) {
    let parsed;
    try { parsed = JSON.parse(fs.readFileSync(e.envelopePath, 'utf8')); }
    catch (err) { allIssues.push(`${e.envelopePath}: invalid JSON (${err.message})`); continue; }
    parsed._dirTool = e.tool;
    parsed._dirDate = e.date;
    const issues = validateEnvelope(parsed, path.relative(REPO_ROOT, e.envelopePath));
    if (issues.length) {
      allIssues.push(...issues);
      if (CHECK) continue; // strict mode skips invalid; non-CHECK still ranks them
    }
    submissions.push(parsed);
  }

  if (CHECK) {
    if (allIssues.length > 0) {
      console.error(`❌ ilb-leaderboard-publish --check: ${allIssues.length} issue(s)`);
      for (const i of allIssues.slice(0, 30)) console.error(`   • ${i}`);
      if (allIssues.length > 30) console.error(`   • ... ${allIssues.length - 30} more`);
      process.exit(1);
    }
    console.log(`✅ ilb-leaderboard-publish --check: ${envelopes.length} submissions valid`);
    return;
  }

  const ranked = rankSubmissions(submissions);
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(path.join(OUT_DIR, 'leaderboard.json'), JSON.stringify({ generatedAt: new Date().toISOString(), totalSubmissions: ranked.length, ranked }, null, 2) + '\n', 'utf8');
  fs.writeFileSync(path.join(OUT_DIR, 'leaderboard.md'), renderMd(ranked) + '\n', 'utf8');

  console.log(`ilb-leaderboard-publish: ${ranked.length} submissions ranked${allIssues.length ? ` (${allIssues.length} issue(s) — submissions still ranked but tagged)` : ''}`);
  console.log(`  wrote benchmark-results/leaderboard.{json,md}`);
}

main();
