#!/usr/bin/env -S npx tsx
/**
 * ilb-iso25010-report — quality-plugin crosswalk against ISO/IEC 25010:2023
 * (roadmap item 4.2). Sister to ilb-mappings-report.mjs (which covers the
 * security-vertical compliance frameworks). This one covers the *quality*
 * vertical — maintainability, reliability, modernization, conventions,
 * modularity, operability — against the ISO software-quality model.
 *
 * Resolution order per rule: meta.iso25010 → seed in iso-25010.json → none.
 *
 * Output: benchmark-results/iso25010-crosswalk.{json,md}.
 *
 * Usage:
 *   npm run ilb:iso25010:report
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const PACKAGES_ROOT = path.join(REPO_ROOT, 'packages');
const SEED = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'benchmarks', 'lib', 'mappings', 'iso-25010.json'), 'utf8'));
const OUT_DIR = path.join(REPO_ROOT, 'benchmark-results');

const QUALITY_PLUGINS = new Set(['maintainability', 'reliability', 'modernization', 'conventions', 'modularity', 'operability']);

function discoverPlugins() {
  if (!fs.existsSync(PACKAGES_ROOT)) return [];
  return fs.readdirSync(PACKAGES_ROOT, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name.startsWith('eslint-plugin-'))
    .map((e) => ({ pluginName: e.name.replace(/^eslint-plugin-/, ''), dir: path.join(PACKAGES_ROOT, e.name) }));
}

function extractIso(src) {
  // meta.iso25010: [{ characteristic: 'Maintainability', subCharacteristic: 'Modularity' }]
  const out = [];
  for (const m of src.matchAll(/\biso25010\s*[:=]\s*\[([\s\S]{0,500}?)\]/g)) {
    for (const o of m[1].matchAll(/\bcharacteristic\s*[:=]\s*['"`]([\w ]+)['"`][^}]*?subCharacteristic\s*[:=]\s*['"`]([\w ]+)['"`]/g)) {
      out.push({ characteristic: o[1], subCharacteristic: o[2] });
    }
  }
  return out;
}

function listRulesFor(plugin) {
  // Two layouts to support:
  //   1. Flat:        src/rules/<rule>/index.ts
  //   2. Categorical: src/rules/<category>/<rule>/index.ts
  const rulesDir = path.join(plugin.dir, 'src', 'rules');
  if (!fs.existsSync(rulesDir)) return [];
  const out = [];

  function visit(dir, baseRuleId) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, e.name);
      // Flat layout: a `<rule>.ts` file directly under src/rules/ (or any sub-dir).
      if (e.isFile() && /\.(ts|js)$/.test(e.name) && e.name !== 'index.ts' && e.name !== 'index.js') {
        const ruleName = e.name.replace(/\.(ts|js)$/, '');
        const ruleId = `${plugin.pluginName}/${baseRuleId ? `${baseRuleId}/${ruleName}` : ruleName}`;
        const direct = extractIso(fs.readFileSync(full, 'utf8'));
        const seed = SEED.exampleRuleMappings[ruleId]
          ?? SEED.exampleRuleMappings[`${plugin.pluginName}/${ruleName}`]
          ?? [];
        out.push({ ruleId, plugin: plugin.pluginName, mappings: direct.length > 0 ? direct : seed });
        continue;
      }
      if (!e.isDirectory()) continue;
      // Categorical-with-index layout
      const indexFile = ['index.ts', 'index.js'].map((f) => path.join(full, f)).find((p) => fs.existsSync(p));
      if (indexFile) {
        const ruleId = `${plugin.pluginName}/${baseRuleId ? `${baseRuleId}/${e.name}` : e.name}`;
        const direct = extractIso(fs.readFileSync(indexFile, 'utf8'));
        const seed = SEED.exampleRuleMappings[ruleId]
          ?? SEED.exampleRuleMappings[`${plugin.pluginName}/${e.name}`]
          ?? [];
        out.push({ ruleId, plugin: plugin.pluginName, mappings: direct.length > 0 ? direct : seed });
      } else {
        // Recurse for categorical layouts.
        visit(full, baseRuleId ? `${baseRuleId}/${e.name}` : e.name);
      }
    }
  }
  visit(rulesDir, '');
  return out;
}

function renderMd(rules) {
  const lines = [];
  lines.push('# ISO/IEC 25010:2023 — Quality Plugin Crosswalk');
  lines.push('');
  lines.push(`> Generated by \`npm run ilb:iso25010:report\` on ${new Date().toISOString()}.`);
  lines.push('> Maps every Interlace quality-plugin rule to one or more ISO 25010 characteristics. Used in compliance / RFP responses where buyers reference ISO directly.');
  lines.push('');

  // Coverage by characteristic
  const coverage = new Map();
  for (const r of rules) {
    for (const m of r.mappings) {
      const key = `${m.characteristic} → ${m.subCharacteristic}`;
      coverage.set(key, (coverage.get(key) ?? 0) + 1);
    }
  }
  lines.push('## Coverage by characteristic');
  lines.push('');
  lines.push('| Characteristic / sub-characteristic | Rules covering |');
  lines.push('|---|---:|');
  for (const [key, n] of [...coverage.entries()].toSorted((a, b) => b[1] - a[1])) {
    lines.push(`| ${key} | ${n} |`);
  }
  lines.push('');

  lines.push('## Per-plugin rule mappings');
  lines.push('');
  const byPlugin = new Map();
  for (const r of rules) {
    if (!QUALITY_PLUGINS.has(r.plugin)) continue;
    if (!byPlugin.has(r.plugin)) byPlugin.set(r.plugin, []);
    byPlugin.get(r.plugin).push(r);
  }
  for (const [plugin, list] of [...byPlugin.entries()].toSorted()) {
    lines.push(`### ${plugin}`);
    lines.push('');
    lines.push('| Rule | Characteristics |');
    lines.push('|---|---|');
    for (const r of list.toSorted((a, b) => a.ruleId.localeCompare(b.ruleId))) {
      const mapped = r.mappings.length > 0 ? r.mappings.map((m) => `${m.characteristic} (${m.subCharacteristic})`).join(' · ') : '— (needs annotation)';
      lines.push(`| \`${r.ruleId}\` | ${mapped} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function main() {
  const plugins = discoverPlugins();
  const rules = plugins.flatMap(listRulesFor);
  const qualityRules = rules.filter((r) => QUALITY_PLUGINS.has(r.plugin));
  const mapped = qualityRules.filter((r) => r.mappings.length > 0).length;

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const json = {
    generatedAt: new Date().toISOString(),
    summary: {
      qualityRules: qualityRules.length,
      mapped,
      coveragePct: qualityRules.length === 0 ? 0 : Math.round((mapped / qualityRules.length) * 100),
    },
    rules: qualityRules,
  };
  fs.writeFileSync(path.join(OUT_DIR, 'iso25010-crosswalk.json'), JSON.stringify(json, null, 2) + '\n', 'utf8');
  fs.writeFileSync(path.join(OUT_DIR, 'iso25010-crosswalk.md'), renderMd(qualityRules) + '\n', 'utf8');

  console.log(`ilb-iso25010-report: ${qualityRules.length} quality rules · ${mapped} mapped (${json.summary.coveragePct}%)`);
  console.log('  wrote benchmark-results/iso25010-crosswalk.{json,md}');
}

main();
