#!/usr/bin/env -S npx tsx
/**
 * ilb-kappa — compute Cohen's κ between two SARIF runs over the same corpus
 * (roadmap item 4.4). Used when an external reviewer (academic security lab,
 * security consultancy, independent auditor) has rated the same fixtures.
 *
 * Inputs: two SARIF v2.1.0 files. Output: JSON + Markdown report.
 *
 * Usage:
 *   node scripts/ilb-kappa.mjs --a interlace.sarif --b external-reviewer.sarif
 *   node scripts/ilb-kappa.mjs --a a.sarif --b b.sarif --out kappa-report
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { cohensKappa, sarifToRaters } from '../benchmarks/lib/stats-kappa.ts';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');

const ARG = (flag) => {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : null;
};

const A = ARG('--a');
const B = ARG('--b');
const OUT = ARG('--out') ?? path.join(REPO_ROOT, 'benchmark-results', 'kappa-report');

if (!A || !B) {
  console.error('usage: ilb-kappa --a <sarif> --b <sarif> [--out <path-prefix>]');
  process.exit(2);
}

const sarifA = JSON.parse(fs.readFileSync(A, 'utf8'));
const sarifB = JSON.parse(fs.readFileSync(B, 'utf8'));

const { raterA, raterB, items } = sarifToRaters(sarifA, sarifB);
const k = cohensKappa(raterA, raterB);

const passed = k.kappa >= 0.75; // SLO from roadmap item 4.4

console.log(`Cohen's κ on ${k.n} (file, line) items:`);
console.log(`  κ = ${k.kappa.toFixed(4)}  (${k.interpretation})  ${passed ? '✅ ≥ 0.75 SLO' : '❌ < 0.75 SLO'}`);
console.log(`  observed agreement: ${(k.observedAgreement * 100).toFixed(1)}%`);
console.log(`  expected agreement: ${(k.expectedAgreement * 100).toFixed(1)}%`);
console.log(`  categories: ${k.categories.length} (${k.categories.slice(0, 5).join(', ')}${k.categories.length > 5 ? ', ...' : ''})`);

fs.mkdirSync(path.dirname(OUT), { recursive: true });
const outJson = {
  generatedAt: new Date().toISOString(),
  inputs: { a: path.relative(REPO_ROOT, A), b: path.relative(REPO_ROOT, B) },
  ...k,
  passed,
  slo: 0.75,
};
fs.writeFileSync(`${OUT}.json`, JSON.stringify(outJson, null, 2) + '\n', 'utf8');

const md = renderMd(outJson);
fs.writeFileSync(`${OUT}.md`, md, 'utf8');

console.log(`wrote ${path.relative(REPO_ROOT, OUT)}.{json,md}`);
process.exit(passed ? 0 : 1);

function renderMd(o) {
  const l = [];
  l.push(`# Inter-rater agreement — Cohen's κ`);
  l.push('');
  l.push(`> Generated by \`ilb-kappa\` on ${o.generatedAt}.`);
  l.push(`> Comparing rater A (\`${o.inputs.a}\`) vs rater B (\`${o.inputs.b}\`).`);
  l.push('');
  l.push(`**κ = ${o.kappa.toFixed(4)}** — *${o.interpretation}* (Landis & Koch). SLO ≥ 0.75 (substantial).`);
  l.push('');
  l.push(`- N = ${o.n} items`);
  l.push(`- Observed agreement: ${(o.observedAgreement * 100).toFixed(1)}%`);
  l.push(`- Expected agreement: ${(o.expectedAgreement * 100).toFixed(1)}%`);
  l.push(`- Categories: ${o.categories.length}`);
  l.push('');
  if (o.categories.length <= 8) {
    l.push('## Confusion matrix');
    l.push('');
    l.push('| A \\ B | ' + o.categories.join(' | ') + ' |');
    l.push('|---|' + o.categories.map(() => '---:').join('|') + '|');
    for (const a of o.categories) {
      const row = [a];
      for (const b of o.categories) row.push(String(o.confusionMatrix[a][b]));
      l.push('| ' + row.join(' | ') + ' |');
    }
  } else {
    l.push('_Confusion matrix has > 8 categories; see JSON for full detail._');
  }
  return l.join('\n') + '\n';
}
