#!/usr/bin/env -S npx tsx
/**
 * ilb-provenance — rule ↔ real-CVE traceability (roadmap item 2.6).
 *
 * For every Interlace security rule, verify that ≥ 1 real CVE is documented
 * either in the rule's `meta.cveExamples` or in the seed corpus at
 * `benchmarks/lib/mappings/cve-examples.json`. Emits a coverage report and
 * a CI-checkable boolean: "every rule has at least one provenance link."
 *
 * Resolution order:
 *   1. `meta.cveExamples: ['CVE-YYYY-NNNNN', ...]` on the rule itself.
 *   2. Entry in `benchmarks/lib/mappings/cve-examples.json` keyed by ruleId.
 *
 * Output:
 *   - `benchmark-results/provenance.json`        machine-readable
 *   - `benchmark-results/provenance.md`          per-rule traceability table
 *
 * Usage:
 *   npm run ilb:provenance
 *   tsx scripts/ilb-provenance.ts --check     # CI gate: fail if any security rule has no CVE example
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const PACKAGES_ROOT = path.join(REPO_ROOT, 'packages');
const SEED_PATH = path.join(REPO_ROOT, 'benchmarks', 'lib', 'mappings', 'cve-examples.json');
const OUT_DIR = path.join(REPO_ROOT, 'benchmark-results');

const CHECK = process.argv.includes('--check');

const SECURITY_PLUGINS = new Set([
  'secure-coding', 'browser-security', 'node-security', 'crypto', 'jwt',
  'express-security', 'lambda-security', 'mongodb-security', 'nestjs-security',
  'vercel-ai-security', 'pg',
]);

const seed = JSON.parse(fs.readFileSync(SEED_PATH, 'utf8'));

function discoverPlugins() {
  if (!fs.existsSync(PACKAGES_ROOT)) return [];
  return fs.readdirSync(PACKAGES_ROOT, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name.startsWith('eslint-plugin-'))
    .map((e) => ({ pluginName: e.name.replace(/^eslint-plugin-/, ''), dir: path.join(PACKAGES_ROOT, e.name) }));
}

function extractCves(ruleSource) {
  const cves = new Set();
  for (const m of ruleSource.matchAll(/['"`](CVE-\d{4}-\d{4,7})['"`]/g)) cves.add(m[1]);
  return [...cves];
}

function listRulesForPlugin(plugin) {
  const rulesDir = path.join(plugin.dir, 'src', 'rules');
  if (!fs.existsSync(rulesDir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(rulesDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    for (const f of ['index.ts', 'index.js']) {
      const p = path.join(rulesDir, entry.name, f);
      if (!fs.existsSync(p)) continue;
      const ruleId = `${plugin.pluginName}/${entry.name}`;
      const ruleCves = extractCves(fs.readFileSync(p, 'utf8'));
      const seedCves = (seed.rules?.[ruleId] ?? []).map((e) => typeof e === 'string' ? e : e.cve);
      const all = [...new Set([...ruleCves, ...seedCves])];
      out.push({
        ruleId,
        plugin: plugin.pluginName,
        isSecurityPlugin: SECURITY_PLUGINS.has(plugin.pluginName),
        cveExamples: all,
        sources: { fromRule: ruleCves.length > 0, fromSeed: seedCves.length > 0 },
      });
      break;
    }
  }
  return out;
}

function main() {
  const rules = discoverPlugins().flatMap(listRulesForPlugin);

  const securityRules = rules.filter((r) => r.isSecurityPlugin);
  const withCves = securityRules.filter((r) => r.cveExamples.length > 0);
  const without = securityRules.filter((r) => r.cveExamples.length === 0);

  const summary = {
    totalSecurityRules: securityRules.length,
    rulesWithProvenance: withCves.length,
    coveragePct: securityRules.length === 0 ? 0 : Math.round((withCves.length / securityRules.length) * 100),
    rulesMissingProvenance: without.length,
  };

  if (CHECK) {
    if (without.length > 0) {
      console.error(`❌ ilb-provenance --check: ${without.length} security rules have no CVE example.`);
      for (const r of without.slice(0, 15)) console.error(`   • ${r.ruleId}`);
      if (without.length > 15) console.error(`   • ... ${without.length - 15} more`);
      console.error('');
      console.error('Add a CVE link via either:');
      console.error('  1. Annotate the rule meta with `cveExamples: ["CVE-YYYY-NNNNN"]`, or');
      console.error('  2. Add an entry to benchmarks/lib/mappings/cve-examples.json under .rules["<ruleId>"]');
      process.exit(1);
    }
    console.log(`✅ ilb-provenance --check: ${securityRules.length}/${securityRules.length} security rules have ≥ 1 CVE example.`);
    return;
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(path.join(OUT_DIR, 'provenance.json'), JSON.stringify({ generatedAt: new Date().toISOString(), summary, rules }, null, 2) + '\n', 'utf8');

  const lines = [];
  lines.push('# Rule Provenance — Real-CVE Traceability');
  lines.push('');
  lines.push(`> Generated by \`npm run ilb:provenance\` on ${new Date().toISOString()}.`);
  lines.push(`> Operationalizes roadmap item 2.6: every Interlace security rule has at least one real-world CVE it would have caught had it been running.`);
  lines.push('');
  lines.push(`**Coverage:** ${summary.rulesWithProvenance} of ${summary.totalSecurityRules} security rules (${summary.coveragePct}%)`);
  lines.push('');
  if (without.length > 0) {
    lines.push(`## Rules missing provenance (${without.length})`);
    lines.push('');
    for (const r of without) lines.push(`- \`${r.ruleId}\``);
    lines.push('');
  }
  lines.push('## Per-rule traceability');
  lines.push('');
  lines.push('| Rule | CVE Examples | Source |');
  lines.push('|---|---|---|');
  for (const r of securityRules.sort((a, b) => a.ruleId.localeCompare(b.ruleId))) {
    const links = r.cveExamples.map((c) => `[${c}](https://nvd.nist.gov/vuln/detail/${c})`).join(' · ') || '—';
    const src = r.sources.fromRule && r.sources.fromSeed ? 'rule+seed' : r.sources.fromRule ? 'rule' : r.sources.fromSeed ? 'seed' : '—';
    lines.push(`| \`${r.ruleId}\` | ${links} | ${src} |`);
  }
  fs.writeFileSync(path.join(OUT_DIR, 'provenance.md'), lines.join('\n') + '\n', 'utf8');

  console.log(`ilb-provenance: ${summary.rulesWithProvenance}/${summary.totalSecurityRules} security rules have provenance (${summary.coveragePct}%)`);
  console.log(`  wrote benchmark-results/provenance.{json,md}`);
}

main();
