#!/usr/bin/env -S npx tsx
/**
 * ilb-federated-aggregate — community wild-corpus federation (roadmap item 5.5).
 *
 * Today: 22 OSS repos in `scripts/ilb-wild.mjs` BENCHMARK_REPOS. With
 * federation: hundreds, contributed by the community. This aggregator
 * reads federated submissions under `benchmarks/federated/<contributor>/<repo>/`
 * and merges them into the public scorecard.
 *
 * Each federated submission is a JSON envelope (vocabulary-contract shape)
 * + a sibling SARIF result. The aggregator:
 *
 *   1. Validates the envelope (schema + toolchain block + methodologyCommit).
 *   2. Dedupes against canonical Wild repos (no double-counting).
 *   3. Computes findings/kLoC, plugin coverage %, top-rule list per repo.
 *   4. Emits `benchmark-results/federated-wild.{json,md}` — the aggregated view.
 *
 * Submissions accepted via PR to `benchmarks/federated/<contributor>/<repo>/`.
 * The protocol is documented in `benchmarks/audits/2026-05-09-federation-protocol.md`.
 *
 * Usage:
 *   npm run ilb:federated:aggregate
 *   node scripts/ilb-federated-aggregate.mjs --check    # CI gate
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateToolchain } from '../benchmarks/lib/toolchain.ts';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const FED_ROOT = path.join(REPO_ROOT, 'benchmarks', 'federated');
const WILD_REGISTRY = path.join(REPO_ROOT, 'scripts', 'ilb-wild.mjs');
const OUT_DIR = path.join(REPO_ROOT, 'benchmark-results');

const CHECK = process.argv.includes('--check');

function listSubmissions() {
  if (!fs.existsSync(FED_ROOT)) return [];
  const out = [];
  for (const contributor of fs.readdirSync(FED_ROOT, { withFileTypes: true })) {
    if (!contributor.isDirectory()) continue;
    const cdir = path.join(FED_ROOT, contributor.name);
    for (const repoEntry of fs.readdirSync(cdir, { withFileTypes: true })) {
      if (!repoEntry.isDirectory()) continue;
      const env = path.join(cdir, repoEntry.name, 'envelope.json');
      if (!fs.existsSync(env)) continue;
      out.push({ contributor: contributor.name, repo: repoEntry.name, envelopePath: env });
    }
  }
  return out;
}

function validateEnvelope(env, label) {
  const issues = [];
  for (const f of ['bench', 'benchVersion', 'tool', 'submitter', 'timestamp', 'methodologyCommit', 'toolchain', 'corpus', 'repo']) {
    if (env[f] === undefined) issues.push(`${label}: missing required field "${f}"`);
  }
  if (env.toolchain) for (const t of validateToolchain(env.toolchain)) issues.push(`${label}: ${t}`);
  if (env.bench && env.bench !== 'ILB-Wild-Federated') {
    issues.push(`${label}: bench must be "ILB-Wild-Federated" (got "${env.bench}")`);
  }
  return issues;
}

function loadCanonicalRepoSet() {
  if (!fs.existsSync(WILD_REGISTRY)) return new Set();
  const src = fs.readFileSync(WILD_REGISTRY, 'utf8');
  const re = /name:\s*['"]([\w.-]+)['"]/g;
  const out = new Set();
  let m;
  while ((m = re.exec(src)) !== null) out.add(m[1]);
  return out;
}

function aggregate(submissions) {
  const canonical = loadCanonicalRepoSet();
  const accepted = [];
  const skipped = [];
  for (const s of submissions) {
    const env = JSON.parse(fs.readFileSync(s.envelopePath, 'utf8'));
    const issues = validateEnvelope(env, path.relative(REPO_ROOT, s.envelopePath));
    if (issues.length) { skipped.push({ ...s, reason: issues[0], allIssues: issues }); continue; }
    if (canonical.has(env.repo?.name)) { skipped.push({ ...s, reason: `dedup: ${env.repo.name} already in canonical Wild registry` }); continue; }
    accepted.push({ ...s, env });
  }
  return { accepted, skipped, canonicalRepoCount: canonical.size };
}

function renderMd(agg) {
  const lines = [];
  lines.push('# Federated Wild Corpus');
  lines.push('');
  lines.push(`> Generated by \`npm run ilb:federated:aggregate\` on ${new Date().toISOString()}.`);
  lines.push('> Community-contributed Wild-bench runs from beyond the 22-repo canonical registry. Protocol: [audits/2026-05-09-federation-protocol.md](../benchmarks/audits/2026-05-09-federation-protocol.md).');
  lines.push('');
  lines.push(`**Canonical Wild repos:** ${agg.canonicalRepoCount}`);
  lines.push(`**Federated submissions accepted:** ${agg.accepted.length}`);
  lines.push(`**Federated submissions skipped:** ${agg.skipped.length}`);
  lines.push(`**Total wild-corpus reach:** ${agg.canonicalRepoCount + agg.accepted.length} repos`);
  lines.push('');
  if (agg.accepted.length > 0) {
    lines.push('## Federated repos');
    lines.push('');
    lines.push('| Contributor | Repo | LoC | Findings | per-kLoC | Plugins active | Submitter |');
    lines.push('|---|---|---:|---:|---:|---:|---|');
    for (const a of agg.accepted) {
      const e = a.env;
      const r = e.repo ?? {};
      const eff = e.effectiveness ?? {};
      lines.push(`| **${a.contributor}** | [${r.name ?? a.repo}](${r.url ?? '#'}) | ${(r.loc ?? '').toLocaleString?.() ?? '—'} | ${eff.findingCount ?? '—'} | ${eff.findingsPerKloc?.toFixed?.(2) ?? '—'} | ${eff.pluginsActive ?? '—'} | ${e.submitter?.name ?? '—'} |`);
    }
    lines.push('');
  }
  if (agg.skipped.length > 0) {
    lines.push('## Skipped submissions');
    lines.push('');
    for (const s of agg.skipped) lines.push(`- \`${s.contributor}/${s.repo}\` — ${s.reason}`);
  }
  return lines.join('\n');
}

function main() {
  const submissions = listSubmissions();
  const agg = aggregate(submissions);

  if (CHECK) {
    const fatalIssues = agg.skipped.filter((s) => !s.reason.startsWith('dedup'));
    if (fatalIssues.length > 0) {
      console.error(`❌ ilb-federated-aggregate --check: ${fatalIssues.length} invalid submission(s)`);
      for (const s of fatalIssues.slice(0, 15)) console.error(`   • ${s.contributor}/${s.repo}: ${s.reason}`);
      process.exit(1);
    }
    console.log(`✅ ilb-federated-aggregate --check: ${submissions.length} submissions valid (${agg.skipped.filter((s) => s.reason.startsWith('dedup')).length} dedup-skipped)`);
    return;
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(path.join(OUT_DIR, 'federated-wild.json'), JSON.stringify({ generatedAt: new Date().toISOString(), ...agg }, null, 2) + '\n', 'utf8');
  fs.writeFileSync(path.join(OUT_DIR, 'federated-wild.md'), renderMd(agg) + '\n', 'utf8');

  console.log(`ilb-federated-aggregate: ${agg.accepted.length} accepted · ${agg.skipped.length} skipped · canonical wild repos ${agg.canonicalRepoCount}`);
  console.log('  wrote benchmark-results/federated-wild.{json,md}');
}

main();
