/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * measure.mts — write a plain ESLint config, run the real CLI, report.
 *
 * This replaces an instrumented sweep that wrapped every rule's `context.report`
 * to capture nodes. That machinery produced six wrong answers in one day: it
 * resolved the wrong module export and silently skipped 26 of 30 plugins while
 * reporting zero findings; it retained ASTs until the process died; it needed a
 * Proxy, then `Object.create`, then `defineProperty`, because `context.report`
 * is read-only. Every one of those failures was in the instrument, not the rule.
 *
 * So there is no instrument here. The config it writes is an ordinary flat
 * config, the run is `npx eslint --format json`, and both are things a user
 * could do. The file stays on disk afterwards precisely so the number can be
 * reproduced by hand, which is the whole point of publishing a command
 * alongside a measurement.
 *
 *   npx tsx scripts/measure.mts --plugin=secure-coding
 *   npx tsx scripts/measure.mts --rule=secure-coding/no-redos-vulnerable-regex
 *   npx tsx scripts/measure.mts --plugin=reliability --preset=strict
 */
import { ESLint } from 'eslint';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CACHE = path.join(ROOT, 'benchmarks/.real-source-cache');
const CONFIGS = path.join(ROOT, 'benchmarks/configs');

const arg = (name: string) => process.argv.find((a) => a.startsWith(`--${name}=`))?.split('=')[1];
const rule = arg('rule');
const plugin = arg('plugin') ?? rule?.split('/')[0];
const preset = arg('preset') ?? 'recommended';
if (!plugin) {
  console.error('usage: measure.mts --plugin=<name> | --rule=<plugin>/<rule> [--preset=recommended]');
  process.exit(1);
}

const dist = path.join(ROOT, 'packages', `eslint-plugin-${plugin}`, 'dist/src/index.js');
if (!fs.existsSync(dist)) {
  console.error(`no build at ${path.relative(ROOT, dist)} — run turbo build first`);
  process.exit(1);
}

const label = rule ? rule.replace('/', '__') : `${plugin}__${preset}`;
const configFile = path.join(CONFIGS, `${label}.config.mjs`);

/**
 * `configs` is a NAMED export on these builds and `rules` lives on the default —
 * a plain `import plugin from` would silently get an object with no configs, and
 * a preset that reads as empty looks exactly like a clean result. The config
 * below imports the namespace and says which half it wants, in the open.
 */
const body = rule
  ? `rules: { '${rule}': 'error' },`
  : `rules: Object.fromEntries(Object.keys(interlace.configs['${preset}'].rules).map((r) => [r, 'error'])),`;

fs.mkdirSync(CONFIGS, { recursive: true });
fs.writeFileSync(
  configFile,
  `// Generated by scripts/measure.mts — an ordinary flat config, runnable by hand:
//   npx eslint --config ${path.relative(ROOT, configFile)} --no-config-lookup <files>
import * as interlace from '${dist}';
import tsParser from '@typescript-eslint/parser';

export default [
  {
    files: ['**/*.js', '**/*.jsx', '**/*.mjs', '**/*.cjs', '**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
    // Ignores are matched against the FULL path, so a bare '**/benchmarks/**'
    // also matches the corpus's own location under benchmarks/.real-source-cache
    // and silently excludes every file. The first run of this script reported 0
    // findings for all five rules for exactly that reason — which reads like
    // five perfect rules.
    //
    // Anchoring each pattern one level inside a repository directory keeps the
    // intent (skip a project's own tests, docs and vendored output) without the
    // pattern reaching up and eating the corpus root.
    ignores: [
      '**/node_modules/**', '**/*.min.js', '**/*.bundle.js', '**/*.chunk.js',
      '**/*.test.*', '**/*.spec.*',
      '*/*/dist/**', '*/*/build/**', '*/*/coverage/**', '*/*/vendor/**',
      '*/*/test/**', '*/*/tests/**', '*/*/__tests__/**', '*/*/fixtures/**',
      '*/*/docs/**', '*/*/examples/**', '*/*/benchmarks/**', '*/*/.yarn/**',
    ],
    languageOptions: { parser: tsParser, ecmaVersion: 2022, sourceType: 'module' },
    plugins: { '${plugin}': { rules: interlace.rules } },
    ${body}
  },
];
`,
);

console.log(`\n  config  ${path.relative(ROOT, configFile)}`);
console.log(`  target  ${rule ?? `${plugin}/${preset}`}\n`);

/**
 * The file list is built here rather than handed to ESLint as a directory.
 *
 * Passing a directory produced 38,966 files where every other instrument in
 * this repo sees 21,394, and 2,060 findings from 174 rules that belong to no
 * plugin under test — some other configuration was reaching the run. The same
 * config against a single explicit FILE is perfectly clean: one message, one
 * rule id. So the ambiguity is in directory traversal, and the fix is to stop
 * traversing.
 *
 * These are the exact exclusions used by ilb-real-source and case-ledger. Three
 * instruments, one file set, or their numbers are not comparable.
 */
const SKIP_DIR =
  /(^|\/)(node_modules|dist|build|\.next|\.nuxt|coverage|vendor|public|fixtures?|__fixtures__|test|tests|__tests__|spec|specs|e2e|benchmarks?|examples?|docs?)(\/|$)/;
const SKIP_FILE = /(\.(min|bundle|chunk)\.[cm]?jsx?|\.(test|spec)\.[cm]?[jt]sx?)$/;
const files: string[] = [];
const walk = (dir: string): void => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!SKIP_DIR.test(`/${path.relative(CACHE, full)}/`) && !entry.name.startsWith('.')) walk(full);
    } else if (/\.[cm]?[jt]sx?$/.test(entry.name) && !SKIP_FILE.test(entry.name)) {
      files.push(full);
    }
  }
};
walk(CACHE);

const started = Date.now();
const eslint = new ESLint({ overrideConfigFile: configFile, allowInlineConfig: false });
const results = await eslint.lintFiles(files);
const elapsed = ((Date.now() - started) / 1000).toFixed(0);

let loc = 0;
let linted = 0;
const byRule = new Map<string, number>();
const foreign = new Map<string, number>();
let unkeyed = 0;
for (const file of results) {
  linted += 1;
  try {
    loc += fs.readFileSync(file.filePath, 'utf8').split('\n').length;
  } catch {
    /* unreadable */
  }
  for (const message of file.messages) {
    // A null ruleId is ESLint reporting about itself — a parse error, or "no
    // matching configuration". Counting those as findings is a trap this repo
    // has already fallen into once.
    if (message.ruleId === null) {
      unkeyed += 1;
      continue;
    }
    // Count only what we asked for. A stray rule id means some other config
    // reached this run, and silently folding it into the total is how a number
    // stops describing the thing it is named after.
    if (!message.ruleId.startsWith(`${plugin}/`)) {
      foreign.set(message.ruleId, (foreign.get(message.ruleId) ?? 0) + 1);
      continue;
    }
    if (rule && message.ruleId !== rule) continue;
    byRule.set(message.ruleId, (byRule.get(message.ruleId) ?? 0) + 1);
  }
}

const findings = [...byRule.values()].reduce((a, b) => a + b, 0);
console.log(`  ${linted} files · ${(loc / 1e6).toFixed(2)}M lines · ${elapsed}s\n`);
console.log(`  FINDINGS          ${findings}`);
console.log(`  per 1,000 LOC     ${loc ? ((findings / loc) * 1000).toFixed(2) : '—'}`);
console.log(`  rules that fired  ${byRule.size}`);
if (unkeyed) console.log(`  parse errors      ${unkeyed}  (not counted as findings)`);
if (foreign.size) {
  const n = [...foreign.values()].reduce((a, b) => a + b, 0);
  console.log(`  FOREIGN RULES     ${n} from ${foreign.size} rule(s) not in this plugin — excluded`);
}

if (byRule.size > 1) {
  console.log(`\n  ${'findings'.padStart(9)}  rule`);
  for (const [id, n] of [...byRule].sort((a, b) => b[1] - a[1]).slice(0, 25)) {
    console.log(`  ${String(n).padStart(9)}  ${id}`);
  }
}
console.log('');
