#!/usr/bin/env -S npx tsx
/**
 * scaffold-mcp — generate MCP server packages for every Interlace security
 * plugin (roadmap item 3.4 — fleet rollout).
 *
 * Run once to create `packages/<plugin>-mcp/` for each entry below. Each
 * generated package is < 30 lines (package.json + src/index.mjs), all logic
 * lives in @interlace/eslint-mcp-base. Re-running is idempotent — overwrites
 * generated files but won't touch unrelated ones.
 *
 * Usage:
 *   node scripts/scaffold-mcp.mjs              # create all
 *   node scripts/scaffold-mcp.mjs --plugin browser-security
 *   node scripts/scaffold-mcp.mjs --dry-run    # print what would be created
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const PACKAGES_ROOT = path.join(REPO_ROOT, 'packages');

const ARG = (flag) => {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : null;
};
const ONLY_PLUGIN = ARG('--plugin');
const DRY_RUN = process.argv.includes('--dry-run');

// All security-vertical plugins that should expose MCP tools.
// Note: secure-coding-mcp already exists (the proof-of-concept); this script
// will refresh its files alongside the rest.
const FLEET = [
  { plugin: 'secure-coding',     packageDir: 'eslint-plugin-secure-coding' },
  { plugin: 'browser-security',  packageDir: 'eslint-plugin-browser-security' },
  { plugin: 'node-security',     packageDir: 'eslint-plugin-node-security' },
  { plugin: 'crypto',            packageDir: 'eslint-plugin-crypto' },
  { plugin: 'jwt',               packageDir: 'eslint-plugin-jwt' },
  { plugin: 'express-security',  packageDir: 'eslint-plugin-express-security' },
  { plugin: 'lambda-security',   packageDir: 'eslint-plugin-lambda-security' },
  { plugin: 'mongodb-security',  packageDir: 'eslint-plugin-mongodb-security' },
  { plugin: 'nestjs-security',   packageDir: 'eslint-plugin-nestjs-security' },
  { plugin: 'vercel-ai-security', packageDir: 'eslint-plugin-vercel-ai-security' },
  { plugin: 'pg',                packageDir: 'eslint-plugin-pg' },
];

function makePackageJson({ plugin, packageDir }) {
  return {
    name: `@interlace/${plugin}-mcp`,
    version: '0.1.0',
    description: `MCP server for the @interlace/eslint-plugin-${plugin} ESLint plugin. Exposes list_rules, audit_file, find_rule_violations, suggest_fix over stdio. Built on @interlace/eslint-mcp-base.`,
    license: 'MIT',
    type: 'module',
    main: './src/index.mjs',
    bin: { [`${plugin}-mcp`]: './src/index.mjs' },
    exports: { '.': './src/index.mjs' },
    files: ['src', 'README.md'],
    keywords: ['mcp', 'eslint', 'static-analysis', plugin, 'interlace', 'agent'],
    peerDependencies: { eslint: '>=8.0.0' },
    dependencies: {
      '@interlace/eslint-mcp-base': '*',
      '@modelcontextprotocol/sdk': '^1.0.0',
    },
  };
}

function makeIndexMjs({ plugin, packageDir }) {
  return `#!/usr/bin/env node
/**
 * @interlace/${plugin}-mcp — MCP server for @interlace/eslint-plugin-${plugin}.
 * Generated by scripts/scaffold-mcp.mjs. All logic in @interlace/eslint-mcp-base.
 */
import { startMcpServer } from '@interlace/eslint-mcp-base';

await startMcpServer({
  pluginName: '${plugin}',
  packageDir: '${packageDir}',
  rulePrefix: '${plugin}',
  serverName: '${plugin}-mcp',
  serverVersion: '0.1.0',
});
`;
}

function ensureFile(filePath, content) {
  if (DRY_RUN) {
    console.log(`[dry-run] write ${path.relative(REPO_ROOT, filePath)} (${content.length}B)`);
    return false;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function main() {
  const targets = ONLY_PLUGIN ? FLEET.filter((p) => p.plugin === ONLY_PLUGIN) : FLEET;
  if (targets.length === 0) {
    console.error(`scaffold-mcp: no targets matched "${ONLY_PLUGIN}"`);
    process.exit(1);
  }
  let createdPkgs = 0;
  let createdSrcs = 0;
  for (const t of targets) {
    const pkgDir = path.join(PACKAGES_ROOT, `${t.plugin}-mcp`);
    const pkgJsonPath = path.join(pkgDir, 'package.json');
    const srcPath = path.join(pkgDir, 'src', 'index.mjs');

    const pkgJson = JSON.stringify(makePackageJson(t), null, 2) + '\n';
    if (ensureFile(pkgJsonPath, pkgJson)) createdPkgs++;
    if (ensureFile(srcPath, makeIndexMjs(t))) createdSrcs++;

    if (!DRY_RUN) {
      try { fs.chmodSync(srcPath, 0o755); } catch {}
    }
  }
  console.log(`scaffold-mcp: ${targets.length} plugin(s) processed${DRY_RUN ? ' (dry-run)' : ''}; package.json written ${createdPkgs}, src/index.mjs written ${createdSrcs}`);
}

main();
