/**
 * Data layer for `/changelog`.
 *
 * Reads `src/data/changelog.json`, generated by
 * `apps/docs/scripts/sync-changelog.ts` from every workspace's `CHANGELOG.md`
 * plus the git tag that dates each release. The page never parses markdown.
 *
 * ## Why the page filters by package and not by kind
 *
 * Entries carry a `kind` (feature / fix / breaking / …) derived from the
 * changeset's conventional-commit prefix. That classification only exists for
 * releases made after the release-notes overhaul: of 1537 entries in the
 * corpus today, 1489 are `other` — prose summaries written before the badge
 * format, which cannot be retroactively classified without inventing facts
 * about them.
 *
 * A "filter by kind" control would therefore be a facet that hides 97% of the
 * page, which is worse than not offering it. Kind is shown per entry where it
 * is known and ignored where it is not, and the filter is by package — 32
 * values, every release has one, and "what changed in the plugin I use" is the
 * question a reader actually arrives with. When the corpus has enough
 * classified entries to make a kind facet useful, it can be added without
 * changing this shape.
 */

import changelog from '@/data/changelog.json';

export interface ChangelogEntry {
  kind: string;
  title: string;
  pr: number | null;
}

export interface ChangelogRelease {
  package: string;
  short: string;
  version: string;
  date: string | null;
  isApp: boolean;
  isPrivate: boolean;
  entries: ChangelogEntry[];
}

/** Releases per page. Classic pagination with URL state, per PAGINATION_PHILOSOPHY.md. */
export const RELEASES_PER_PAGE = 20;

/** Kinds we have a label for. Anything else renders without a badge. */
const KIND_LABELS: Record<string, string> = {
  breaking: 'Breaking',
  feature: 'Feature',
  fix: 'Fix',
  security: 'Security',
  perf: 'Performance',
  docs: 'Docs',
  chore: 'Maintenance',
  deps: 'Dependencies',
};

export function kindLabel(kind: string): string | null {
  return KIND_LABELS[kind] ?? null;
}

/**
 * A breaking change is the one kind worth calling out in a scannable list —
 * it is the only one that costs the reader work.
 */
export function isBreaking(release: ChangelogRelease): boolean {
  return release.entries.some((e) => e.kind === 'breaking');
}

export interface ChangelogQuery {
  /** 1-based. Out-of-range values clamp rather than 404 — a stale link still works. */
  page?: number;
  /** Unscoped package name, or undefined for all. */
  pkg?: string;
}

export interface ChangelogPage {
  releases: ChangelogRelease[];
  page: number;
  pageCount: number;
  total: number;
  /** Every package present in the corpus, for the filter. */
  packages: Array<{ short: string; name: string; count: number }>;
  totals: { releases: number; packages: number; entries: number };
}

const ALL = changelog.releases as ChangelogRelease[];

export function getChangelogPage(query: ChangelogQuery = {}): ChangelogPage {
  const filtered = query.pkg ? ALL.filter((r) => r.short === query.pkg) : ALL;

  const pageCount = Math.max(1, Math.ceil(filtered.length / RELEASES_PER_PAGE));
  // Clamp instead of erroring: `?page=99` from a stale link or a crawler
  // should show the last page, not a dead end.
  const page = Math.min(Math.max(1, query.page ?? 1), pageCount);
  const start = (page - 1) * RELEASES_PER_PAGE;

  const counts = new Map<string, { name: string; count: number }>();
  for (const release of ALL) {
    const seen = counts.get(release.short);
    if (seen) seen.count += 1;
    else counts.set(release.short, { name: release.package, count: 1 });
  }

  return {
    releases: filtered.slice(start, start + RELEASES_PER_PAGE),
    page,
    pageCount,
    total: filtered.length,
    packages: [...counts.entries()]
      .map(([short, v]) => ({ short, name: v.name, count: v.count }))
      .sort((a, b) => a.short.localeCompare(b.short)),
    totals: {
      releases: changelog.releaseCount,
      packages: changelog.packageCount,
      entries: changelog.entryCount,
    },
  };
}

/**
 * Releases for one package, newest first.
 *
 * Accepts the slug the docs MDX uses (`jwt-security`) as well as the full
 * package name (`eslint-plugin-jwt-security`) — the content tree names plugins
 * without the `eslint-plugin-` prefix, and rather than rewrite 26 MDX files to
 * match the data, the lookup absorbs both spellings.
 *
 * `limit` of 0 means every release. The plugin pages show a window because a
 * docs page is a reference for the *current* version; the full history is one
 * click away at `/changelog?pkg=…`.
 */
export function getPluginReleases(slug: string, limit = 0): ChangelogRelease[] {
  const wanted = new Set([slug, `eslint-plugin-${slug}`, `@interlace/${slug}`]);
  const matches = ALL.filter(
    (r) => wanted.has(r.short) || wanted.has(r.package),
  );
  return limit > 0 ? matches.slice(0, limit) : matches;
}

/** `2026-08-23T15:44:41-05:00` → `23 Aug 2026`. Null dates render as "unreleased". */
export function formatReleaseDate(iso: string | null): string {
  if (!iso) return 'Unreleased';
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    timeZone: 'UTC',
  });
}
