-- Schema, indexes, ratchet trigger, RLS, seed.
-- Replaces the file-based GHA stats storage in apps/docs/src/data/*.json.

create extension if not exists pgcrypto;

-- ─── Dimensions ─────────────────────────────────────────────────────────
create table public.plugins (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  slug        text not null unique,
  category    text not null check (category in ('security','quality','framework','react','architecture')),
  description text,
  created_at  timestamptz not null default now()
);
create index plugins_category_idx on public.plugins (category);

-- ─── Audit / observability ──────────────────────────────────────────────
create table public.ingest_runs (
  id            uuid primary key default gen_random_uuid(),
  workflow      text not null,
  started_at    timestamptz not null default now(),
  finished_at   timestamptz,
  rows_written  int,
  status        text not null check (status in ('success','partial','error','running')),
  error_message text,
  gha_run_url   text
);
create index ingest_runs_workflow_started_idx on public.ingest_runs (workflow, started_at desc);

-- ─── Daily facts ────────────────────────────────────────────────────────
create table public.plugin_daily_metrics (
  id                bigint generated by default as identity primary key,
  plugin_id         bigint not null references public.plugins(id) on delete cascade,
  observed_on       date not null,
  npm_downloads_d7  int,
  npm_downloads_d30 int,
  npm_version       text,
  github_stars      int,
  github_forks      int,
  rule_count        int,
  published         boolean default true,
  ingest_run_id     uuid references public.ingest_runs(id) on delete set null,
  unique (plugin_id, observed_on)
);
create index plugin_daily_metrics_observed_idx on public.plugin_daily_metrics (observed_on desc);

create table public.coverage_snapshots (
  id            bigint generated by default as identity primary key,
  plugin_id     bigint not null references public.plugins(id) on delete cascade,
  observed_on   date not null,
  coverage_pct  numeric(5,2),
  status        text check (status in ('production','beta','alpha')),
  total_lines   int,
  covered_lines int,
  ingest_run_id uuid references public.ingest_runs(id) on delete set null,
  unique (plugin_id, observed_on)
);

create table public.peer_health_snapshots (
  id              bigint generated by default as identity primary key,
  peer_name       text not null,
  observed_on     date not null,
  weekly_dl       int,
  open_issues     int,
  last_release_at timestamptz,
  ingest_run_id   uuid references public.ingest_runs(id) on delete set null,
  unique (peer_name, observed_on)
);

-- ─── External-source caches (latest-wins) ───────────────────────────────
create table public.external_articles (
  id           bigint generated by default as identity primary key,
  source       text not null,
  external_id  text not null,
  slug         text,
  title        text,
  description  text,
  author       text,
  url          text,
  published_at timestamptz,
  payload      jsonb not null,
  fetched_at   timestamptz not null default now(),
  unique (source, external_id)
);
create index external_articles_published_idx on public.external_articles (published_at desc);

create table public.external_tweets (
  id         bigint generated by default as identity primary key,
  tweet_id   text not null unique,
  payload    jsonb not null,
  photo_url  text,
  fetched_at timestamptz not null default now()
);

-- ─── Generic EAV for everything else ────────────────────────────────────
create table public.metric_snapshots (
  id            bigint generated by default as identity primary key,
  source        text not null,
  kind          text not null,
  dimension     text not null default '',
  observed_on   date not null,
  value         numeric(20,4),
  payload       jsonb,
  ingest_run_id uuid references public.ingest_runs(id) on delete set null,
  unique (source, kind, dimension, observed_on)
);
create index metric_snapshots_source_kind_idx on public.metric_snapshots (source, kind, observed_on desc);
create index metric_snapshots_observed_idx on public.metric_snapshots (observed_on desc);

-- ─── Storefront ratchet (the North Star) ────────────────────────────────
create table public.storefront_ratchet (
  kind           text primary key,
  bucket         text not null check (bucket in ('contributions','engagement','north_star')),
  current_value  bigint not null default 0,
  updated_at     timestamptz not null default now(),
  source_kinds   jsonb not null default '{}'::jsonb,
  display_label  text not null,
  display_unit   text,
  display_icon   text,
  display_order  int not null default 0,
  description    text,
  provenance_url text,
  weight         numeric(8,4) not null default 1.0
);

-- GREATEST trigger: current_value is monotonically non-decreasing at the row level.
create or replace function public.enforce_ratchet_monotonic()
returns trigger language plpgsql as $$
begin
  if TG_OP = 'UPDATE' then
    new.current_value := greatest(old.current_value, new.current_value);
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger storefront_ratchet_monotonic
before insert or update on public.storefront_ratchet
for each row execute function public.enforce_ratchet_monotonic();

-- ─── RLS ────────────────────────────────────────────────────────────────
alter table public.plugins               enable row level security;
alter table public.ingest_runs           enable row level security;
alter table public.plugin_daily_metrics  enable row level security;
alter table public.coverage_snapshots    enable row level security;
alter table public.peer_health_snapshots enable row level security;
alter table public.external_articles     enable row level security;
alter table public.external_tweets       enable row level security;
alter table public.metric_snapshots      enable row level security;
alter table public.storefront_ratchet    enable row level security;
-- service_role bypasses RLS automatically. anon gets access only via views in 0002
-- (views are created with security_invoker = off, so they read tables as the owner).

-- ─── Seed: plugins dimension ────────────────────────────────────────────
insert into public.plugins (name, slug, category, description) values
  ('eslint-plugin-browser-security',  'browser-security',  'security',     'Security-focused ESLint plugin for browser applications'),
  ('eslint-plugin-node-security',     'node-security',     'security',     'Security-focused ESLint plugin for Node'),
  ('eslint-plugin-secure-coding',     'secure-coding',     'security',     'Security-focused ESLint plugin with AI-parseable rules for detecting and preventing vulnerabilities'),
  ('eslint-plugin-vercel-ai-security','vercel-ai-security','security',     'Security-focused ESLint plugin for Vercel AI SDK'),
  ('eslint-plugin-mongodb-security',  'mongodb-security',  'security',     'Security-focused ESLint plugin for MongoDB & Mongoose'),
  ('eslint-plugin-pg',                'pg',                'security',     'ESLint plugin with security and best practices rules for the pg Node'),
  ('eslint-plugin-jwt',               'jwt',               'security',     'Security-focused ESLint plugin for JWT operations'),
  ('eslint-plugin-crypto',            'crypto',            'security',     '[DEPRECATED — use eslint-plugin-node-security]'),
  ('eslint-plugin-lambda-security',   'lambda-security',   'framework',    'Security-focused ESLint plugin for AWS Lambda and Middy applications'),
  ('eslint-plugin-express-security',  'express-security',  'framework',    'Security-focused ESLint plugin for Express'),
  ('eslint-plugin-nestjs-security',   'nestjs-security',   'framework',    'Security-focused ESLint rules for NestJS applications'),
  ('eslint-plugin-import-next',       'import-next',       'architecture', 'Drop-in replacement for eslint-plugin-import'),
  ('eslint-plugin-maintainability',   'maintainability',   'quality',      'ESLint rules for reducing cognitive load and ensuring code readability'),
  ('eslint-plugin-conventions',       'conventions',       'quality',      'ESLint rules for team-specific disciplinary patterns and code conventions'),
  ('eslint-plugin-reliability',       'reliability',       'quality',      'ESLint rules for runtime stability, fault tolerance, and type safety'),
  ('eslint-plugin-modularity',        'modularity',        'quality',      'ESLint rules for architecture, DDD patterns, and module isolation'),
  ('eslint-plugin-operability',       'operability',       'quality',      'ESLint rules for production behavior, resource hygiene, and log quality'),
  ('eslint-plugin-modernization',     'modernization',     'quality',      'ESLint rules for modernizing JavaScript to ES2022+ syntax'),
  ('eslint-plugin-react-features',    'react-features',    'react',        'ESLint React rules for modern react features, hooks, and patterns'),
  ('eslint-plugin-react-a11y',        'react-a11y',        'react',        'React accessibility ESLint plugin with LLM-optimized rules for WCAG 2')
on conflict (name) do nothing;

-- ─── Seed: storefront ratchet rows ──────────────────────────────────────
insert into public.storefront_ratchet
  (kind, bucket, display_label, display_unit, display_icon, display_order, description, provenance_url)
values
  ('contrib_commits',           'contributions', 'Commits authored',         'count',     'git-commit',         10, 'Public commits authored across @ofriperetz repos', 'https://github.com/search?q=author%3Aofriperetz+is%3Apublic&type=commits'),
  ('contrib_prs_merged',        'contributions', 'Pull requests merged',     'count',     'git-pull-request',   20, 'Merged PRs authored by @ofriperetz',                'https://github.com/search?q=author%3Aofriperetz+is%3Amerged&type=pullrequests'),
  ('contrib_releases',          'contributions', 'Releases shipped',         'count',     'package',            30, 'npm + GitHub releases across our packages',          'https://www.npmjs.com/~ofriperetz'),
  ('contrib_rules_shipped',     'contributions', 'ESLint rules shipped',     'count',     'shield-check',       40, 'Sum of rule counts across published @interlace plugins', 'https://www.npmjs.com/~ofriperetz'),
  ('contrib_articles_authored', 'contributions', 'Articles published',       'count',     'book-open',          50, 'Articles authored on dev.to + medium',               'https://dev.to/ofri'),
  ('eng_downloads_cumulative',  'engagement',    'Cumulative npm downloads', 'downloads', 'download',           10, 'Total npm downloads summed across all plugins, all days', 'https://www.npmjs.com/~ofriperetz'),
  ('eng_github_stars',          'engagement',    'GitHub stars',             'stars',     'star',               20, 'Stars across @interlace plugins on GitHub',          'https://github.com/ofriperetz'),
  ('eng_page_views_cumulative', 'engagement',    'Page views',               'views',     'eye',                30, 'Cumulative docs-site page views from Vercel Analytics', 'https://vercel.com/ofri-peretz/docs/analytics'),
  ('eng_devto_reactions',       'engagement',    'Dev.to reactions',         'reactions', 'heart',              40, 'Sum of positive reactions across articles',          'https://dev.to/ofri'),
  ('eng_tweet_engagement',      'engagement',    'Tweet engagement',         'count',     'twitter',            50, 'Likes + retweets + bookmarks on related tweets',     'https://twitter.com/search?q=interlace+OR+ofriperetz'),
  ('north_star_total',          'north_star',    'North Star',               'total',     'sparkles',            0, 'contributions_total + engagement_total — the single number going up', null)
on conflict (kind) do nothing;
