/**
 * Tests for require-tls-connection
 * CWE-295 — Require TLS for MongoDB connections in production
 *
 * Generated by: node scripts/generate-rule-tests.mjs
 * Standard: Engineering Standards §5 (side-by-side), §6 (≥5 valid + ≥5 invalid), §8 (RuleTester at describe level)
 */
import { RuleTester } from '@typescript-eslint/rule-tester';
import { describe, it, afterAll } from 'vitest';
import parser from '@typescript-eslint/parser';
import { requireTlsConnection } from './index';

/**
 * Every fixture imports mongoose, because the rules now abstain in files with
 * no Mongo in them. Wrapping the arrays rather than editing each fixture means
 * one cannot be left behind — a fixture missing the import would pass
 * vacuously on the gate instead of exercising the detection it was written
 * for. `output` and errors[].suggestions[].output are prefixed too, since
 * autofix fixtures assert the whole file back.
 */
// A SIDE-EFFECT import: satisfies the gate without reserving any binding, so
// fixtures that already declare `mongoose`/`db` do not redeclare.
const asMongo = (code: string): string => `import 'mongoose';\n${code}`;
type MongoSuggestion = { output?: string | null };
type MongoCase = {
  code: string;
  output?: string | null;
  errors?: ReadonlyArray<{ suggestions?: readonly MongoSuggestion[] } | string>;
};
const xmo = <T,>(cases: T[]): T[] =>
  cases.map((c) => {
    if (typeof c === 'string') return asMongo(c) as T;
    const test = c as MongoCase;
    return {
      ...c,
      code: asMongo(test.code),
      ...(typeof test.output === 'string' ? { output: asMongo(test.output) } : {}),
      ...(test.errors
        ? {
            errors: test.errors.map((e) =>
              typeof e === 'string' || !Array.isArray(e.suggestions)
                ? e
                : {
                    ...e,
                    suggestions: e.suggestions.map((s) =>
                      typeof s.output === 'string'
                        ? { ...s, output: asMongo(s.output) }
                        : s,
                    ),
                  },
            ),
          }
        : {}),
    } as T;
  });


RuleTester.afterAll = afterAll;
RuleTester.it = it;
RuleTester.itOnly = it.only;
RuleTester.describe = describe;

const ruleTester = new RuleTester({
  languageOptions: {
    parser,
    ecmaVersion: 2022,
    sourceType: 'module',
    parserOptions: { ecmaFeatures: { jsx: true } },
  },
});

describe('require-tls-connection', () => {
  describe('Valid Code', () => {
    ruleTester.run('valid - safe patterns', requireTlsConnection, {
      valid: xmo([
        // Unrelated code should not trigger
        {
          name: 'the driver is imported but nothing queries',
          code: `const x = 1;`,
        },
        // Array operations are safe
        {
          code: `const arr = [1, 2, 3];`,
        },
        // Non-targeted method calls are safe
        {
          code: `obj.safeMethod();`,
        },
        // Static property values are safe
        {
          code: `const config = { key: "static-value" };`,
        },
        // Properly configured connection
        {
          code: `mongoose.connect(uri, { tls: true });`,
        },
        // Quoted keys are the same config. Matching only identifier keys
        // reported these as missing TLS — a false positive on secure code,
        // and the reason the report used to carry no suggestion.
        {
          code: `mongoose.connect(uri, { 'tls': true });`,
        },
        {
          code: `mongoose.connect(uri, { "ssl": true });`,
        },
        {
          code: `mongoose.createConnection(uri, { 'ssl': true, w: 1 });`,
        },
        // Allowed in test files
        {
          code: `if (x == y) {}`,
          filename: 'test.spec.ts',
          options: [{"allowInTests":true}],
        },
      ]),
      invalid: [],
    });
  });

  describe('Invalid Code', () => {
    ruleTester.run('invalid - dangerous patterns', requireTlsConnection, {
      valid: [],
      invalid: xmo([
        // Triggers requireTls: no TLS configured
        {
          name: 'connect with no TLS option',
          code: `mongoose.connect('mongodb://localhost/db', { useNewUrlParser: true });`,
          errors: [{
        messageId: 'requireTls',
        suggestions: [{ messageId: 'suggestionAddTls', output: `mongoose.connect('mongodb://localhost/db', { useNewUrlParser: true, tls: true });` }],
      }],
        },
      ]),
    });
  });
describe('Suggestions', () => {
    ruleTester.run('suggestion - adds tls: true', requireTlsConnection, {
      valid: [],
      invalid: xmo([
        // Existing options object: merge the property in.
        {
          code: `mongoose.connect('mongodb://localhost/db', { useNewUrlParser: true });`,
          errors: [{
            messageId: 'requireTls',
            suggestions: [{
              messageId: 'suggestionAddTls',
              output: `mongoose.connect('mongodb://localhost/db', { useNewUrlParser: true, tls: true });`,
            }],
          }],
        },
        // Empty options object: replace it wholesale.
        {
          code: `mongoose.connect('mongodb://localhost/db', {});`,
          errors: [{
            messageId: 'requireTls',
            suggestions: [{
              messageId: 'suggestionAddTls',
              output: `mongoose.connect('mongodb://localhost/db', { tls: true });`,
            }],
          }],
        },
        // No options argument at all: append one.
        {
          code: `mongoose.connect('mongodb://localhost/db');`,
          errors: [{
            messageId: 'requireTls',
            suggestions: [{
              messageId: 'suggestionAddTls',
              output: `mongoose.connect('mongodb://localhost/db', { tls: true });`,
            }],
          }],
        },
        // Non-object second argument: no mechanical rewrite, no suggestion.
        {
          code: `mongoose.connect('mongodb://localhost/db', connectOptions);`,
          errors: [{ messageId: 'requireTls', suggestions: [] }],
        },
      ]),
    });
  });
});
