/**
 * Copyright (c) 2025 Ofri Peretz
 * Licensed under the MIT License. Use of this source code is governed by the
 * MIT license that can be found in the LICENSE file.
 */

/**
 * `AST_NODE_TYPES`, inlined.
 *
 * ponytail: this table was the last runtime dependency in the package. It came
 * from `@typescript-eslint/types` — 144 KB for what is, at runtime, 168
 * self-mapped strings (`{ Identifier: 'Identifier', ... }`) totalling a few KB.
 * Inlining it takes `@interlace/eslint-devkit` to ZERO runtime dependencies,
 * which is the property that actually matters for a package sitting underneath
 * every plugin in the ecosystem.
 *
 * The cast is load-bearing and deliberate. Upstream declares `AST_NODE_TYPES`
 * as a string `enum`, and TypeScript does NOT accept a string literal where an
 * enum member is expected — `const t: AST_NODE_TYPES.Identifier = 'Identifier'`
 * is an error. A plain `as const` object would therefore break every consumer
 * that builds node literals. Casting to `typeof Upstream` keeps the exported
 * type byte-identical to what consumers see today; only the runtime values are
 * ours. The type-only import is erased at compile time.
 *
 * `ast-node-types.test.ts` asserts this table against the real enum in both
 * directions, so an upstream addition or rename fails the build rather than
 * silently shipping a node type our rules can never match.
 */
import type { AST_NODE_TYPES as UpstreamASTNodeTypes } from '@typescript-eslint/utils';

const AST_NODE_TYPES_VALUES = {
  AccessorProperty: 'AccessorProperty',
  ArrayExpression: 'ArrayExpression',
  ArrayPattern: 'ArrayPattern',
  ArrowFunctionExpression: 'ArrowFunctionExpression',
  AssignmentExpression: 'AssignmentExpression',
  AssignmentPattern: 'AssignmentPattern',
  AwaitExpression: 'AwaitExpression',
  BinaryExpression: 'BinaryExpression',
  BlockStatement: 'BlockStatement',
  BreakStatement: 'BreakStatement',
  CallExpression: 'CallExpression',
  CatchClause: 'CatchClause',
  ChainExpression: 'ChainExpression',
  ClassBody: 'ClassBody',
  ClassDeclaration: 'ClassDeclaration',
  ClassExpression: 'ClassExpression',
  ConditionalExpression: 'ConditionalExpression',
  ContinueStatement: 'ContinueStatement',
  DebuggerStatement: 'DebuggerStatement',
  Decorator: 'Decorator',
  DoWhileStatement: 'DoWhileStatement',
  EmptyStatement: 'EmptyStatement',
  ExportAllDeclaration: 'ExportAllDeclaration',
  ExportDefaultDeclaration: 'ExportDefaultDeclaration',
  ExportNamedDeclaration: 'ExportNamedDeclaration',
  ExportSpecifier: 'ExportSpecifier',
  ExpressionStatement: 'ExpressionStatement',
  ForInStatement: 'ForInStatement',
  ForOfStatement: 'ForOfStatement',
  ForStatement: 'ForStatement',
  FunctionDeclaration: 'FunctionDeclaration',
  FunctionExpression: 'FunctionExpression',
  Identifier: 'Identifier',
  IfStatement: 'IfStatement',
  ImportAttribute: 'ImportAttribute',
  ImportDeclaration: 'ImportDeclaration',
  ImportDefaultSpecifier: 'ImportDefaultSpecifier',
  ImportExpression: 'ImportExpression',
  ImportNamespaceSpecifier: 'ImportNamespaceSpecifier',
  ImportSpecifier: 'ImportSpecifier',
  JSXAttribute: 'JSXAttribute',
  JSXClosingElement: 'JSXClosingElement',
  JSXClosingFragment: 'JSXClosingFragment',
  JSXElement: 'JSXElement',
  JSXEmptyExpression: 'JSXEmptyExpression',
  JSXExpressionContainer: 'JSXExpressionContainer',
  JSXFragment: 'JSXFragment',
  JSXIdentifier: 'JSXIdentifier',
  JSXMemberExpression: 'JSXMemberExpression',
  JSXNamespacedName: 'JSXNamespacedName',
  JSXOpeningElement: 'JSXOpeningElement',
  JSXOpeningFragment: 'JSXOpeningFragment',
  JSXSpreadAttribute: 'JSXSpreadAttribute',
  JSXSpreadChild: 'JSXSpreadChild',
  JSXText: 'JSXText',
  LabeledStatement: 'LabeledStatement',
  Literal: 'Literal',
  LogicalExpression: 'LogicalExpression',
  MemberExpression: 'MemberExpression',
  MetaProperty: 'MetaProperty',
  MethodDefinition: 'MethodDefinition',
  NewExpression: 'NewExpression',
  ObjectExpression: 'ObjectExpression',
  ObjectPattern: 'ObjectPattern',
  PrivateIdentifier: 'PrivateIdentifier',
  Program: 'Program',
  Property: 'Property',
  PropertyDefinition: 'PropertyDefinition',
  RestElement: 'RestElement',
  ReturnStatement: 'ReturnStatement',
  SequenceExpression: 'SequenceExpression',
  SpreadElement: 'SpreadElement',
  StaticBlock: 'StaticBlock',
  Super: 'Super',
  SwitchCase: 'SwitchCase',
  SwitchStatement: 'SwitchStatement',
  TSAbstractAccessorProperty: 'TSAbstractAccessorProperty',
  TSAbstractKeyword: 'TSAbstractKeyword',
  TSAbstractMethodDefinition: 'TSAbstractMethodDefinition',
  TSAbstractPropertyDefinition: 'TSAbstractPropertyDefinition',
  TSAnyKeyword: 'TSAnyKeyword',
  TSArrayType: 'TSArrayType',
  TSAsExpression: 'TSAsExpression',
  TSAsyncKeyword: 'TSAsyncKeyword',
  TSBigIntKeyword: 'TSBigIntKeyword',
  TSBooleanKeyword: 'TSBooleanKeyword',
  TSCallSignatureDeclaration: 'TSCallSignatureDeclaration',
  TSClassImplements: 'TSClassImplements',
  TSConditionalType: 'TSConditionalType',
  TSConstructSignatureDeclaration: 'TSConstructSignatureDeclaration',
  TSConstructorType: 'TSConstructorType',
  TSDeclareFunction: 'TSDeclareFunction',
  TSDeclareKeyword: 'TSDeclareKeyword',
  TSEmptyBodyFunctionExpression: 'TSEmptyBodyFunctionExpression',
  TSEnumBody: 'TSEnumBody',
  TSEnumDeclaration: 'TSEnumDeclaration',
  TSEnumMember: 'TSEnumMember',
  TSExportAssignment: 'TSExportAssignment',
  TSExportKeyword: 'TSExportKeyword',
  TSExternalModuleReference: 'TSExternalModuleReference',
  TSFunctionType: 'TSFunctionType',
  TSImportEqualsDeclaration: 'TSImportEqualsDeclaration',
  TSImportType: 'TSImportType',
  TSIndexSignature: 'TSIndexSignature',
  TSIndexedAccessType: 'TSIndexedAccessType',
  TSInferType: 'TSInferType',
  TSInstantiationExpression: 'TSInstantiationExpression',
  TSInterfaceBody: 'TSInterfaceBody',
  TSInterfaceDeclaration: 'TSInterfaceDeclaration',
  TSInterfaceHeritage: 'TSInterfaceHeritage',
  TSIntersectionType: 'TSIntersectionType',
  TSIntrinsicKeyword: 'TSIntrinsicKeyword',
  TSLiteralType: 'TSLiteralType',
  TSMappedType: 'TSMappedType',
  TSMethodSignature: 'TSMethodSignature',
  TSModuleBlock: 'TSModuleBlock',
  TSModuleDeclaration: 'TSModuleDeclaration',
  TSNamedTupleMember: 'TSNamedTupleMember',
  TSNamespaceExportDeclaration: 'TSNamespaceExportDeclaration',
  TSNeverKeyword: 'TSNeverKeyword',
  TSNonNullExpression: 'TSNonNullExpression',
  TSNullKeyword: 'TSNullKeyword',
  TSNumberKeyword: 'TSNumberKeyword',
  TSObjectKeyword: 'TSObjectKeyword',
  TSOptionalType: 'TSOptionalType',
  TSParameterProperty: 'TSParameterProperty',
  TSPrivateKeyword: 'TSPrivateKeyword',
  TSPropertySignature: 'TSPropertySignature',
  TSProtectedKeyword: 'TSProtectedKeyword',
  TSPublicKeyword: 'TSPublicKeyword',
  TSQualifiedName: 'TSQualifiedName',
  TSReadonlyKeyword: 'TSReadonlyKeyword',
  TSRestType: 'TSRestType',
  TSSatisfiesExpression: 'TSSatisfiesExpression',
  TSStaticKeyword: 'TSStaticKeyword',
  TSStringKeyword: 'TSStringKeyword',
  TSSymbolKeyword: 'TSSymbolKeyword',
  TSTemplateLiteralType: 'TSTemplateLiteralType',
  TSThisType: 'TSThisType',
  TSTupleType: 'TSTupleType',
  TSTypeAliasDeclaration: 'TSTypeAliasDeclaration',
  TSTypeAnnotation: 'TSTypeAnnotation',
  TSTypeAssertion: 'TSTypeAssertion',
  TSTypeLiteral: 'TSTypeLiteral',
  TSTypeOperator: 'TSTypeOperator',
  TSTypeParameter: 'TSTypeParameter',
  TSTypeParameterDeclaration: 'TSTypeParameterDeclaration',
  TSTypeParameterInstantiation: 'TSTypeParameterInstantiation',
  TSTypePredicate: 'TSTypePredicate',
  TSTypeQuery: 'TSTypeQuery',
  TSTypeReference: 'TSTypeReference',
  TSUndefinedKeyword: 'TSUndefinedKeyword',
  TSUnionType: 'TSUnionType',
  TSUnknownKeyword: 'TSUnknownKeyword',
  TSVoidKeyword: 'TSVoidKeyword',
  TaggedTemplateExpression: 'TaggedTemplateExpression',
  TemplateElement: 'TemplateElement',
  TemplateLiteral: 'TemplateLiteral',
  ThisExpression: 'ThisExpression',
  ThrowStatement: 'ThrowStatement',
  TryStatement: 'TryStatement',
  UnaryExpression: 'UnaryExpression',
  UpdateExpression: 'UpdateExpression',
  VariableDeclaration: 'VariableDeclaration',
  VariableDeclarator: 'VariableDeclarator',
  WhileStatement: 'WhileStatement',
  WithStatement: 'WithStatement',
  YieldExpression: 'YieldExpression',
} as const;

export const AST_NODE_TYPES =
  AST_NODE_TYPES_VALUES as unknown as typeof UpstreamASTNodeTypes;
