#!/usr/bin/env node
/**
 * @interlace/cli — one-command Interlace CLI (roadmap item 5.4).
 *
 * Subcommands:
 *
 *   interlace audit [path]
 *       Run all Interlace plugins (in `recommended` config) against the path.
 *       Default path: cwd. Defaults to flat-config + tsx loader so TS plugins
 *       resolve transparently.
 *
 *   interlace init
 *       Drop a starter `eslint.config.mjs` into the cwd, wired up with the
 *       Interlace recommended preset. Refuses to overwrite an existing config
 *       unless --force.
 *
 *   interlace bench
 *       Quick local bench (delegates to `npm run ilb:smoke`).
 *
 *   interlace mcp <plugin>
 *       Start the MCP server for a given plugin (e.g. `interlace mcp secure-coding`).
 *       Exposes the plugin's rules as agent-callable tools over stdio.
 *
 *   interlace --version | --help
 *
 * Design intent: the CLI is a *thin shim*. Every action delegates to existing
 * tooling (eslint, ilb scripts, MCP servers). The CLI's only job is to make
 * the entry point one word ("interlace ...") instead of a memorized recipe.
 */

import { spawn, execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const requireFromHere = createRequire(import.meta.url);
const HERE = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_VERSION = JSON.parse(fs.readFileSync(path.join(HERE, '..', 'package.json'), 'utf8')).version;

const HELP = `interlace v${PACKAGE_VERSION} — one-command Interlace ESLint ecosystem CLI

Usage:
  interlace audit [path]               Run all Interlace plugins against path (default: .)
  interlace audit --json [path]        Emit JSON instead of human-readable output
  interlace audit --sarif [path]       Emit SARIF v2.1.0 (consumable by GHAS, Defender, etc.)
  interlace audit --plugin <name>      Limit to one plugin (e.g. secure-coding, browser-security)

  interlace init                       Generate a starter eslint.config.mjs in the cwd
  interlace init --force               Overwrite existing config

  interlace bench                      Quick local bench (npm run ilb:smoke)

  interlace mcp <plugin>               Start the MCP server for <plugin> over stdio
                                       (e.g. interlace mcp secure-coding)

  interlace --version                  Print CLI version
  interlace --help                     This help text

Recommended first steps for a new project:
    cd your-project
    npx @interlace/cli init           # write eslint.config.mjs
    npx @interlace/cli audit          # lint everything
`;

function findRepoRoot(startDir) {
  let dir = startDir;
  for (let i = 0; i < 10; i++) {
    if (fs.existsSync(path.join(dir, 'eslint.config.mjs')) || fs.existsSync(path.join(dir, 'package.json'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}

function findEslintBin(repoRoot) {
  const candidate = path.join(repoRoot, 'node_modules', 'eslint', 'bin', 'eslint.js');
  return fs.existsSync(candidate) ? candidate : null;
}

const STARTER_CONFIG = `// Generated by \`interlace init\` — extend as you like.
// To preview the rules: \`interlace audit\`.

import secureCoding from '@interlace/eslint-plugin-secure-coding';
import nodeSecurity from '@interlace/eslint-plugin-node-security';
import browserSecurity from '@interlace/eslint-plugin-browser-security';

export default [
  {
    files: ['**/*.{js,mjs,cjs,ts,tsx,jsx}'],
    plugins: {
      'secure-coding':    secureCoding,
      'node-security':    nodeSecurity,
      'browser-security': browserSecurity,
    },
    rules: {
      ...secureCoding.configs?.recommended?.rules    ?? {},
      ...nodeSecurity.configs?.recommended?.rules    ?? {},
      ...browserSecurity.configs?.recommended?.rules ?? {},
    },
  },
];
`;

// ─── subcommands ───────────────────────────────────────────────────────────

function cmdAudit(args) {
  const idx = args.findIndex((a) => !a.startsWith('-'));
  const target = idx === -1 ? '.' : args[idx];
  const json = args.includes('--json');
  const sarif = args.includes('--sarif');
  const pluginIdx = args.indexOf('--plugin');
  const onlyPlugin = pluginIdx >= 0 ? args[pluginIdx + 1] : null;

  const repoRoot = findRepoRoot(process.cwd());
  const eslintBin = findEslintBin(repoRoot);
  if (!eslintBin) {
    console.error(`interlace: eslint not found in ${repoRoot}/node_modules. Run \`npm install\` (or use \`npx eslint\` directly).`);
    process.exit(1);
  }

  const eslintArgs = [
    eslintBin,
    '--no-error-on-unmatched-pattern',
    target,
  ];
  if (json)  eslintArgs.push('--format', 'json');
  if (sarif) eslintArgs.push('--format', '@interlace/eslint-formatter-sarif');
  if (onlyPlugin) {
    // best-effort: append a no-config-lookup with a plugin filter via env var; the rule selection itself stays config-driven
    process.env.INTERLACE_FILTER_PLUGIN = onlyPlugin;
  }

  const child = spawn('npx', ['tsx', ...eslintArgs], { cwd: repoRoot, stdio: 'inherit' });
  child.on('exit', (code) => process.exit(code ?? 0));
}

function cmdInit(args) {
  const force = args.includes('--force');
  const target = path.join(process.cwd(), 'eslint.config.mjs');
  if (fs.existsSync(target) && !force) {
    console.error(`interlace init: ${target} already exists. Use --force to overwrite.`);
    process.exit(1);
  }
  fs.writeFileSync(target, STARTER_CONFIG, 'utf8');
  console.log(`interlace init: wrote ${path.relative(process.cwd(), target)}`);
  console.log('');
  console.log('Next:  interlace audit');
}

function cmdBench(_args) {
  const repoRoot = findRepoRoot(process.cwd());
  try {
    execSync('npm run ilb:smoke', { cwd: repoRoot, stdio: 'inherit' });
  } catch (err) {
    process.exit(err.status ?? 1);
  }
}

function cmdMcp(args) {
  const plugin = args[0];
  if (!plugin) {
    console.error('interlace mcp: missing plugin. e.g. `interlace mcp secure-coding`');
    process.exit(2);
  }
  // Expect @interlace/<plugin>-mcp to be installed (by the user) or available via npx.
  const child = spawn('npx', ['--yes', `@interlace/${plugin}-mcp`], { stdio: 'inherit' });
  child.on('exit', (code) => process.exit(code ?? 0));
}

// ─── router ────────────────────────────────────────────────────────────────

function main() {
  const argv = process.argv.slice(2);
  if (argv.length === 0 || argv[0] === '--help' || argv[0] === '-h') { console.log(HELP); return; }
  if (argv[0] === '--version' || argv[0] === '-v') { console.log(PACKAGE_VERSION); return; }

  const [sub, ...rest] = argv;
  switch (sub) {
    case 'audit': return cmdAudit(rest);
    case 'init':  return cmdInit(rest);
    case 'bench': return cmdBench(rest);
    case 'mcp':   return cmdMcp(rest);
    default:
      console.error(`interlace: unknown command "${sub}". Try \`interlace --help\`.`);
      process.exit(2);
  }
}

main();
