#!/usr/bin/env node
/**
 * @interlace/cli — one-command Interlace CLI (roadmap item 5.4).
 *
 * Subcommands:
 *
 *   interlace audit [path]
 *       Run all Interlace plugins (in `recommended` config) against the path.
 *       Default path: cwd. Defaults to flat-config + tsx loader so TS plugins
 *       resolve transparently.
 *
 *   interlace init
 *       Drop a starter `eslint.config.mjs` into the cwd, wired up with the
 *       Interlace recommended preset. Refuses to overwrite an existing config
 *       unless --force.
 *
 *   interlace bench
 *       Quick local bench (delegates to `npm run ilb:smoke`).
 *
 *   interlace mcp …
 *       Retired. Use the official `@eslint/mcp` server — it discovers every
 *       ESLint plugin (ours included) from your config automatically. The
 *       subcommand still exists so older READMEs surface a clean redirect
 *       message instead of a crash.
 *       Exposes the plugin's rules as agent-callable tools over stdio.
 *
 *   interlace --version | --help
 *
 * Design intent: the CLI is a *thin shim*. Every action delegates to existing
 * tooling (eslint, ilb scripts, MCP servers). The CLI's only job is to make
 * the entry point one word ("interlace ...") instead of a memorized recipe.
 */

import { spawn, execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const requireFromHere = createRequire(import.meta.url);
const HERE = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_VERSION = JSON.parse(fs.readFileSync(path.join(HERE, '..', 'package.json'), 'utf8')).version;

const HELP = `interlace v${PACKAGE_VERSION} — one-command Interlace ESLint ecosystem CLI

Usage:
  interlace audit [path]               Run all Interlace plugins against path (default: .)
  interlace audit --json [path]        Emit JSON instead of human-readable output
  interlace audit --sarif [path]       Emit SARIF v2.1.0 (consumable by GHAS, Defender, etc.)
  interlace audit --plugin <name>      Limit to one plugin (e.g. secure-coding, browser-security)

  interlace init                       Generate a starter eslint.config.mjs in the cwd
  interlace init --force               Overwrite existing config

  interlace bench                      Quick local bench (npm run ilb:smoke)

  interlace mcp                        Retired — prints a redirect to @eslint/mcp.
                                       See https://eslint.interlace.tools/docs/integrations/claude-code

  interlace --version                  Print CLI version
  interlace --help                     This help text

Recommended first steps for a new project:
    cd your-project
    npx @interlace/cli init           # write eslint.config.mjs
    npx @interlace/cli audit          # lint everything
`;

function findRepoRoot(startDir) {
  let dir = startDir;
  for (let i = 0; i < 10; i++) {
    if (fs.existsSync(path.join(dir, 'eslint.config.mjs')) || fs.existsSync(path.join(dir, 'package.json'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}

function findEslintBin(repoRoot) {
  const candidate = path.join(repoRoot, 'node_modules', 'eslint', 'bin', 'eslint.js');
  return fs.existsSync(candidate) ? candidate : null;
}

const STARTER_CONFIG = `// Generated by \`interlace init\` — extend as you like.
// To preview the rules: \`interlace audit\`.

import secureCoding from '@interlace/eslint-plugin-secure-coding';
import nodeSecurity from '@interlace/eslint-plugin-node-security';
import browserSecurity from '@interlace/eslint-plugin-browser-security';

export default [
  {
    files: ['**/*.{js,mjs,cjs,ts,tsx,jsx}'],
    plugins: {
      'secure-coding':    secureCoding,
      'node-security':    nodeSecurity,
      'browser-security': browserSecurity,
    },
    rules: {
      ...secureCoding.configs?.recommended?.rules    ?? {},
      ...nodeSecurity.configs?.recommended?.rules    ?? {},
      ...browserSecurity.configs?.recommended?.rules ?? {},
    },
  },
];
`;

// ─── subcommands ───────────────────────────────────────────────────────────

function cmdAudit(args) {
  const idx = args.findIndex((a) => !a.startsWith('-'));
  const target = idx === -1 ? '.' : args[idx];
  const json = args.includes('--json');
  const sarif = args.includes('--sarif');
  const pluginIdx = args.indexOf('--plugin');
  const onlyPlugin = pluginIdx >= 0 ? args[pluginIdx + 1] : null;

  const repoRoot = findRepoRoot(process.cwd());
  const eslintBin = findEslintBin(repoRoot);
  if (!eslintBin) {
    console.error(`interlace: eslint not found in ${repoRoot}/node_modules. Run \`npm install\` (or use \`npx eslint\` directly).`);
    process.exit(1);
  }

  const eslintArgs = [
    eslintBin,
    '--no-error-on-unmatched-pattern',
    target,
  ];
  if (json)  eslintArgs.push('--format', 'json');
  if (sarif) eslintArgs.push('--format', '@interlace/eslint-formatter-sarif');
  if (onlyPlugin) {
    // best-effort: append a no-config-lookup with a plugin filter via env var; the rule selection itself stays config-driven
    process.env.INTERLACE_FILTER_PLUGIN = onlyPlugin;
  }

  const child = spawn('npx', ['tsx', ...eslintArgs], { cwd: repoRoot, stdio: 'inherit' });
  child.on('exit', (code) => process.exit(code ?? 0));
}

function cmdInit(args) {
  const force = args.includes('--force');
  const target = path.join(process.cwd(), 'eslint.config.mjs');
  if (fs.existsSync(target) && !force) {
    console.error(`interlace init: ${target} already exists. Use --force to overwrite.`);
    process.exit(1);
  }
  fs.writeFileSync(target, STARTER_CONFIG, 'utf8');
  console.log(`interlace init: wrote ${path.relative(process.cwd(), target)}`);
  console.log('');
  console.log('Next:  interlace audit');
}

function cmdBench(_args) {
  const repoRoot = findRepoRoot(process.cwd());
  try {
    execSync('npm run ilb:smoke', { cwd: repoRoot, stdio: 'inherit' });
  } catch (err) {
    process.exit(err.status ?? 1);
  }
}

function cmdMcp() {
  // Retired in 2026-05. We no longer ship per-plugin MCP servers — the
  // official `@eslint/mcp` discovers every ESLint plugin in your config
  // and gives Claude Code / Cursor the same tool surface for free.
  // See: apps/docs/content/docs/integrations/claude-code.mdx
  console.error(
    'interlace mcp: retired. Use the official ESLint MCP instead:\n' +
      '  1. npm install --save-dev eslint eslint-plugin-<plugin>\n' +
      '  2. Register `@eslint/mcp` with your agent (Claude Code, Cursor, etc.):\n' +
      '       { "command": "npx", "args": ["--yes", "@eslint/mcp"] }\n' +
      '  3. Restart the agent. Every installed plugin is exposed automatically.\n' +
      'Docs: https://eslint.interlace.tools/docs/integrations/claude-code',
  );
  process.exit(2);
}

// ─── doctor ────────────────────────────────────────────────────────────────

const sym = (s) => s === 'ok' ? '✅' : s === 'warn' ? '⚠ ' : '❌';

/**
 * `interlace doctor` — adoption-funnel debugger.
 * Walks every checkpoint a fresh user trips over (Node version, ESLint config,
 * installed plugins, MCP servers, telemetry, GitHub Action) and reports:
 *   ✅ ready        — works as expected
 *   ⚠ improve      — works but not optimal
 *   ❌ broken       — fix needed before the next step works
 *
 * Each finding ships with a one-line "fix" command the user can copy-paste.
 */
function cmdDoctor(_args) {
  const repoRoot = findRepoRoot(process.cwd());
  const checks = [];

  // 1. Node version
  const major = Number.parseInt(process.version.replace(/^v/, '').split('.')[0], 10);
  checks.push({
    name: 'Node version',
    status: major >= 22 ? 'ok' : major >= 18 ? 'warn' : 'fail',
    detail: `process.version=${process.version}`,
    fix: major >= 22 ? null : 'Upgrade to Node 22+ (active LTS). nvm install 22 && nvm use 22',
  });

  // 2. ESLint resolvable
  const eslintBin = findEslintBin(repoRoot);
  checks.push({
    name: 'ESLint installed',
    status: eslintBin ? 'ok' : 'fail',
    detail: eslintBin ? `at ${path.relative(repoRoot, eslintBin)}` : 'not found in node_modules',
    fix: eslintBin ? null : 'npm install --save-dev eslint',
  });

  // 3. eslint.config.mjs (or .ts / .js fallback) present
  const cfgCandidates = ['eslint.config.mjs', 'eslint.config.js', 'eslint.config.ts', '.eslintrc.json', '.eslintrc.cjs'];
  const cfg = cfgCandidates.find((c) => fs.existsSync(path.join(process.cwd(), c)));
  checks.push({
    name: 'ESLint config in cwd',
    status: cfg ? 'ok' : 'warn',
    detail: cfg ? `using ${cfg}` : 'no eslint.config.* found',
    fix: cfg ? null : 'interlace init   # writes a starter eslint.config.mjs',
  });

  // 4. Interlace plugins installed
  const FLEET = ['secure-coding', 'browser-security', 'node-security', 'crypto', 'jwt',
                 'express-security', 'lambda-security', 'mongodb-security', 'nestjs-security',
                 'vercel-ai-security', 'pg'];
  const installed = FLEET.filter((p) => fs.existsSync(path.join(repoRoot, 'node_modules', '@interlace', `eslint-plugin-${p}`)));
  checks.push({
    name: 'Interlace plugins installed',
    status: installed.length === 0 ? 'warn' : installed.length < 3 ? 'warn' : 'ok',
    detail: `${installed.length}/${FLEET.length} installed: ${installed.slice(0, 5).join(', ')}${installed.length > 5 ? ' ...' : ''}`,
    fix: installed.length === 0 ? 'npm install --save-dev @interlace/eslint-plugin-secure-coding @interlace/eslint-plugin-node-security @interlace/eslint-plugin-browser-security' : null,
  });

  // 5. SARIF formatter installed (optional but recommended)
  const sarif = fs.existsSync(path.join(repoRoot, 'node_modules', '@interlace', 'eslint-formatter-sarif'));
  checks.push({
    name: 'SARIF formatter installed',
    status: sarif ? 'ok' : 'warn',
    detail: sarif ? 'available' : 'not installed',
    fix: sarif ? null : 'npm install --save-dev @interlace/eslint-formatter-sarif',
  });

  // 6. ESLint MCP installed (optional, for agent integration)
  const eslintMcp = fs.existsSync(path.join(repoRoot, 'node_modules', '@eslint', 'mcp'));
  checks.push({
    name: 'ESLint MCP installed (for agent integration)',
    status: eslintMcp ? 'ok' : 'warn',
    detail: eslintMcp
      ? '@eslint/mcp present — agents (Claude Code, Cursor) can lint files via the official MCP'
      : '@eslint/mcp not installed (optional). Agents can still call it via npx; pre-installing avoids a cold-start delay.',
    fix: eslintMcp ? null : 'npm install --save-dev @eslint/mcp   # then register it in your agent\'s MCP config',
  });

  // 7. Telemetry status (informational only)
  const telemetryEnabled = process.env.INTERLACE_TELEMETRY === '1';
  const endpoint = process.env.INTERLACE_TELEMETRY_ENDPOINT;
  checks.push({
    name: 'Telemetry status (opt-in)',
    status: 'ok',
    detail: telemetryEnabled
      ? `enabled, sending to ${endpoint ?? '<no endpoint set!>'}`
      : 'OFF (default)',
    fix: null,
  });

  // 8. GitHub Action present (optional)
  const ghDir = path.join(repoRoot, '.github', 'workflows');
  const hasInterlace = fs.existsSync(ghDir) && fs.readdirSync(ghDir)
    .filter((f) => /\.ya?ml$/.test(f))
    .some((f) => fs.readFileSync(path.join(ghDir, f), 'utf8').includes('ofri-peretz/eslint/.github/actions/audit'));
  checks.push({
    name: 'GitHub Action wired in CI',
    status: hasInterlace ? 'ok' : 'warn',
    detail: hasInterlace ? 'workflow uses the Interlace audit action' : 'no workflow references the Interlace action',
    fix: hasInterlace ? null : 'Add `uses: ofri-peretz/eslint/.github/actions/audit@main` to a workflow under .github/workflows/',
  });

  // Render
  console.log(`interlace doctor — ${process.cwd()}`);
  console.log('');
  let fails = 0;
  let warns = 0;
  for (const c of checks) {
    console.log(`${sym(c.status)} ${c.name.padEnd(50)} ${c.detail}`);
    if (c.fix) console.log(`     fix:   ${c.fix}`);
    if (c.status === 'fail') fails++;
    else if (c.status === 'warn') warns++;
  }
  console.log('');
  console.log(`Summary — ${checks.length - fails - warns}/${checks.length} ready · ${warns} improve · ${fails} broken`);
  process.exit(fails > 0 ? 1 : 0);
}

// ─── router ────────────────────────────────────────────────────────────────

function main() {
  const argv = process.argv.slice(2);
  if (argv.length === 0 || argv[0] === '--help' || argv[0] === '-h') { console.log(HELP); return; }
  if (argv[0] === '--version' || argv[0] === '-v') { console.log(PACKAGE_VERSION); return; }

  const [sub, ...rest] = argv;
  switch (sub) {
    case 'audit':  return cmdAudit(rest);
    case 'init':   return cmdInit(rest);
    case 'bench':  return cmdBench(rest);
    case 'mcp':    return cmdMcp(rest);
    case 'doctor': return cmdDoctor(rest);
    default:
      console.error(`interlace: unknown command "${sub}". Try \`interlace --help\`.`);
      process.exit(2);
  }
}

main();
